### ISSUE TITLE
join the meeting with out requesting the mic and cam permissions

### ISSUE THREAD

**Issue by moislaieh** [miroslavpejic85/mirotalk#100]
### Feature request
join the meeting with out requesting the mic and cam permissions, so users can listen the conversation, when ever they want to join they click on the mic button which is gonna fire a function that request the mic permission, so with the cam .

that would be absolutely amazing and adding more trust to the service as users think nothing is going on behind the scenes

**Comment by miroslavpejic85** [comment]
Hello @moislaieh,

All WebRTC apps need you to give the audio & cam permissions to work properly.
Even google-meet before you join the room asks you to give permission to the microphone and the cam.

![permissions](https://user-images.githubusercontent.com/70838434/172998953-5ac95a06-2427-4b26-987f-2ea00a06e64e.png)

**Comment by moislaieh** [comment]
okay, cool man,
I know the mic and the cam are important for calling apps but
I was thinking of building a MERN app over it and turn it to a social app, but users don't trust apps that take permission when its not necessary (if they just join to chat for example), so I have to find a way to make it run with out asking permission or build the mesh from scratch

### thank you for sharing your project , I really learned lots of stuff by exploring it . ❤️

**Comment by miroslavpejic85** [comment]
I understand your point of view, Thanks to you I'm happy that you found MiroTalk useful! :)
