### ISSUE TITLE
Bug In Screen Sharing 

### ISSUE THREAD

**Issue by devsecops1solution** [miroslavpejic85/mirotalk#101]
Hi i found a bug in screen sharing option as you see in this picture i tested the online version in heroku and the offline version locally always the same bug
![Capture d’écran 2022-06-10 020252](https://user-images.githubusercontent.com/104401978/172964925-7546bc59-4864-4c41-a96c-46c22109ce22.png)

**Comment by miroslavpejic85** [comment]
Hello @devsecops1solution,

Not sure which bug? If you are sharing your screen to yourself it is normal that you see your duplicate screen n times. As for the message it's not a MiroTalk generated thing.

![screen](https://user-images.githubusercontent.com/70838434/172998705-8d42a640-fd31-4c32-b6d6-6892813a656b.png)

I tried it with Safari, Chrome, Firefox, Edge, Opera, Brave for me all seems ok.
Thank you.

**Comment by devsecops1solution** [comment]
Hi thank you for your reply so after testing this in my laptop (windows 10 core i7 , nvidia rtx) and also in my friend  laptop ( windows 10,intel , nvidia graphic card) we found the same probleme after screen sharing and clicking in the screen to make it bigger and watching it .
So here is a video i record it and i upload it in we-transfer 
_https://we.tl/t-sIXSL0znUD_
ps we tested the online version : _https://mirotalk.herokuap_

**Comment by devsecops1solution** [comment]
monday 6 june , we tested the previous version and it worked perfectly with all option , if you still have it i will be grateful so here is my e-mail  : devsecops1solution@gmail.com

**Comment by miroslavpejic85** [comment]
Hi @devsecops1solution, 

What I see is that you have clicked on your own screen to put it in full screen mode, not your friend's. As I told you this is normal unless you have 2 monitors and move the browser window to the other screen not shared. Usually if you have only one monitor you don't go to put yourself in full screen mode :) and it's normal what I see in the video. 

Usually the scenario is as following:

1. Join in the room from 2 different PC (PC-1 and PC-2)
2. PC-2 share a screen 
3. PC-1 click on shared PC-2 screen to see it on full screen mode.
4. PC-1 share a screen
5. PC-2 click on shared PC-1 screen to see it on full screen mode.

Anyway I improved little a screen sharing view if there are 2 participants in the same room:
https://github.com/miroslavpejic85/mirotalk/commit/2aaf5c7ff77d4a05f1f43df17f307b902db527cd
