### ISSUE TITLE
Live Video One To Many

### ISSUE THREAD

**Issue by devsecops1solution** [miroslavpejic85/mirotalk#102]
hi thanks for this wonderful project how can we perform a live video ( live broadcast like twitch)

**Comment by devsecops1solution** [comment]
for example i want to copy this meeting link "http://localhost:3000/join/streamerRoom1" + with the meeting name or id of the streamer 
and embedng it into a page with iframe for the purpose of performing live video like twitch

**Comment by miroslavpejic85** [comment]
Hi @devsecops1solution,

Thank you, I'm glad you like it!

The way MiroTalk is structured now I don't think it's possible, the idea of the app was that everyone can share their screens with everyone, that everyone can transfer files, chat, use the collaborative whiteboard, video call each other, and so on. 

If you have pleasure, join with us in the [Discord](https://discord.gg/rgGYfeYW3N) channel: ideas and suggestions, where we can all talk together. 

Thank you very much and have a nice weekend.
