### ISSUE TITLE
Change Nr. of Port

### ISSUE THREAD

**Issue by fwn0** [miroslavpejic85/mirotalk#105]
Can I change default port 3000 in MiroTalk with .env configuration ? I know, that it is possible in Peer-calls, Rocket.Chat, etc, but I found here only some discussion about possible config in server + client.js.

**Comment by miroslavpejic85** [comment]
Hi @fwn0,
Now you can change it from `.env` file : https://github.com/miroslavpejic85/mirotalk/commit/53e7e07f59065c7b14af3661e109518869c365e8
