### ISSUE TITLE
Please, add a 2K or QHD (2560 x 1440 pixels) quality setting

### ISSUE THREAD

**Issue by branches78** [miroslavpejic85/mirotalk#106]
### Feature request

Please, add a 2K (2560 x 1440 pixels) quality setting for users like me who own a generic webcam that supports up to that resolution, currently there is a QVGA, VGA, HD, FULL HD and a 4K quality and if choose 4K an error message appears saying the webcam doesn't support it.

I'm not sure what resolution supports the "default" one but it seems to VGA, however, I wonder if it's possible that the website autodetects the maximum quality and selects that automatically.

### Pros

The ability to have videocalls with the maximum resolution my camera supports.

**Comment by miroslavpejic85** [comment]
Hello @branches78,
If everyone was using the webcam at max resolution as default, everyone should have a great bandwidth (may not be optimal for mobile devices with 3G network, and so on..). I still added the possibility to set the `2k` resolution :  https://github.com/miroslavpejic85/mirotalk/commit/459f10c9bbd82d697f50ed0efc2524739863c839 ;)

**Comment by branches78** [comment]
It works perfectly, however, I was wondering if you could make it to autodetect the quality of the camera to avoid going there every time I want to make a video call and select the resolution I want, another useful tool is to have some kind of "stats for nerds" where we can check the resolution sent, the speed, the codec, etc., similar to this:

![image](https://user-images.githubusercontent.com/87671962/175051719-ec811b09-2ade-4696-8f89-e2c88a61709d.png)

Thank you.

**Comment by miroslavpejic85** [comment]
Hi @branches78, 

commit: https://github.com/miroslavpejic85/mirotalk/commit/f154b4047311110e56d52d84bfd149d20fb0d0b5

```js
forceCamMaxResolution = true // default 
```

This will make the browser use the maximum resolution available as default, `up to 4K`.

in case of a bad connection, you can decrease the resolution from the usual settings.

For the stats for nerds, what did you using for display this in the picture you sent?

**Comment by branches78** [comment]
> forceCamMaxResolution = true // default

Where should I add this?
 
> in case of a bad connection, you can decrease the resolution from the usual settings.

So it doesn't adapt to the internet speed automatically?

> For the stats for nerds, what did you using for display this in the picture you sent?

That's from Jitsi Meet (https://meet.jit.si/)

**Comment by branches78** [comment]
> I implemented it in the latest Commit, now as `default`, will be set the `maximum resolution` that the Cam supports.

Oh, I though you were asking me to add that as a syntax or something.

> Not for now.

I see, I hope it gets implemented in the not too distant future...

> I can add it in the future.

Thanks.

> Thank you for the suggestions and for trying MiroTalk.

You're welcome and thank you for your attention.

> Have a nice day.

You too.
