### ISSUE TITLE
Video and audio not working on laptop browser.

### ISSUE THREAD

**Issue by seekex21** [miroslavpejic85/mirotalk#108]
### Describe the bug

When We are using on laptop or desktop browser with different network. I mean if each participant connected via many different network meeting not working. If all participant connected via same network its working good. This problem came only on desktop browser. it's working on mobile browser. 

My meeting link is https://eyebogler.com/join/28433LuckyRat
### Desktop 

Please complete the following information:

 - Device or OS: Windows
 - Browser: Chrome
 - Version :Version 103.0.5060.114 (Official Build) (64-bit)

**Comment by miroslavpejic85** [comment]
Hi @seekex21,
You have this issue even with the latest version of MiroTalk? 
I see you are using the old one. 
Thank you.

**Comment by seekex21** [comment]
Hi @miroslavpejic85 
Thanks for quick reply. 
 I Have use you demo too my end, I found same problem on this.
Please seen my screenshot.

Thanks.

![image](https://user-images.githubusercontent.com/100364198/178249999-d72e2280-8edd-4132-8ebe-7b2cfe236414.png)

**Comment by miroslavpejic85** [comment]
Hi @seekex21, You are welcome. 

1. The pkm & pkm2 are in the different network?
2. pkm and pkm2 having OS Windows 10 or 11?
3.  Both having Browser chrome: 103.0.5060.114 (Official Build) (64-bit)?
4. Did you see any console error logs in the browser? (F12)?

Thanks.

**Comment by seekex21** [comment]
Hi @miroslavpejic85 ,
1. Yes pkm (laptop) is on my home wifi and pkm2 is my phone on mobile network.
2. No my laptop having windows and my phone is android.
3. Yes both device using Chrome Browser in my system chrome(103.0.5060.114) and my phone chrome version is 103.0.5060.71
4. any console error logs in the system browser.

Thanks.

**Comment by miroslavpejic85** [comment]
Hey @seekex21,

I did some cross-tests with iphone and android, browsers (safari, chrome, firefox, edge with 4g phone connection), and windows 10 (chrome browser with wifi connection), here everything works fine. 

I can't reproduce your case :(

1.  Even if you wait for a while (10-20 seconds), does the video always remain black?
2. On you laptop browser, please take a screenshot of the console logs (F12) and share me please.
3. It could also be that the Turn server for some reason is unable to handle your case - network, which is not dependent on MiroTalk. Also try disabling the firewall entirely in windows for testing, and let me know if anything changes? 

Thanks.

**Comment by seekex21** [comment]
Hi @miroslavpejic85 ,
I try to connect on your given link and I found some logs on my browser console. Please seen all my attached screenshots.

Thanks.
![image](https://user-images.githubusercontent.com/100364198/178418921-50377b16-d1da-435d-a2b2-046f884d37ee.png)
![image](https://user-images.githubusercontent.com/100364198/178418986-cd3f0cfd-9c32-4dcf-833f-c3fc781d65bd.png)
![image](https://user-images.githubusercontent.com/100364198/178419036-16955cab-8f9c-44d5-94eb-c9799d27a7e4.png)

**Comment by miroslavpejic85** [comment]
Hello @seekex21, Thank you for the logs.

connectionStatus: `failed`
- One or more of the [ICE](https://developer.mozilla.org/en-US/docs/Glossary/ICE) transports on the connection is in the failed state.

Reference:
- https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/connectionState
- https://developer.mozilla.org/en-US/docs/Glossary/ICE

As a [Turn server](https://webrtc.org/getting-started/turn-server) I currently use a free one [viagenie](http://numb.viagenie.ca/) take a look also [here](https://github.com/miroslavpejic85/mirotalk/blob/master/app/src/server.js#L314). 

You can Try to using a different Turn server and let me know if anything changes? 

For most WebRTC applications to function a Turn server is required for relaying the traffic between peers, since a direct socket is often not possible between the clients, that could be your case.

This is the current MiroTalk P2P logic:

![webrtc-P2P](https://raw.githubusercontent.com/miroslavpejic85/mirotalk/master/public/images/webrtc.png)

PS: If someone has the same issue, please report it to me here, and if with a different Turn server has it solved? If yes which one? 

Many Thanks.

**Comment by miroslavpejic85** [comment]
Hello @seekex21,

Can you please do this test: 

---

## Test StunServer

1. Goto: https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/
2. `STUN or TURN URI:` stun:stun.l.google.com:19302
3. Click on `Gather candidates`

![stun-ok](https://user-images.githubusercontent.com/70838434/180597225-600353a4-81e3-4c74-9249-b0ed203003ce.png)

We expect a `srflx` candidate type to show up, which would confirm that the Stun server is working properly!

---

## Test TurnServer

1. Goto: https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/
2. `STUN or TURN URI:` turn:numb.viagenie.ca
3. `TURN username:` miroslav.pejic.85@gmail.com
4. `TURN password:` mirotalkp2p
5. Click on `Gather candidates`

![turn-ok](https://user-images.githubusercontent.com/70838434/180597251-b34c2e7b-69b1-4bfb-9971-304a3491b56a.png)

In this case, you need to expect a `relay` candidate type to show up to confirm that is working successfully!

If Stun is ok, in most cases the P2P connection will be established.

If Turn is ko, but you need it (like your case) so the connection between peers can't be established. 

---

## Solution

The solution is to found a worked one.

Try also with:

```js
const iceServers = [
    {
        urls: "stun:openrelay.metered.ca:80",
    },
    {
        urls: "turn:openrelay.metered.ca:80",
        username: "openrelayproject",
        credential: "openrelayproject",
    },
    {
        urls: "turn:openrelay.metered.ca:443",
        username: "openrelayproject",
        credential: "openrelayproject",
    },
    {
        urls: "turn:openrelay.metered.ca:443?transport=tcp",
        username: "openrelayproject",
        credential: "openrelayproject",
    },
];
```

Let me know, thanks and have a nice weekend.

**Comment by miroslavpejic85** [comment]
PS: In [this commit](https://github.com/miroslavpejic85/mirotalk/commit/7a0bbfb075affbf76f075c6c80fc28ce9cbd3250) I added also the possibility to edit the `Stun` server in the `.env`, on default `stun:stun.l.google.com:19302`. So now both Stun and Turn can be configurable ;)

**Comment by miroslavpejic85** [comment]
I changed on Heroku the [Turn server](https://mirotalk.herokuapp.com/test?iceServers=[{"urls":"stun:stun.l.google.com:19302"},{"urls":"turn:openrelay.metered.ca:443","username":"openrelayproject","credential":"openrelayproject"}]) (openrelay)

Can you try please here and send me the feedback?

https://mirotalk.herokuapp.com/

Thank you so much.

**Comment by miroslavpejic85** [comment]
I confirm that viagenie Turn doesn't work, I have reproduced the issue Forcing MiroTalk to use only Turn as iceServers. Changed to openrelay, solved it.
