### ISSUE TITLE
Video sharing - only YT is possible like oembed ?

### ISSUE THREAD

**Issue by fwn0** [miroslavpejic85/mirotalk#109]
I tried to test sharing of YT video in chat; YT does work, but only like the embedded player, it is not a synced view for participants. Is it possible to create some embedded links for p2p streaming, for example Peertube or embedding of rtmp or hls streams ?

**Comment by miroslavpejic85** [comment]
Hi @fwn0, Thank you for trying MiroTalk P2P!
Currently it's possible to share YouTube videos, but I can extend it as in [MiroTalk SFU](https://github.com/miroslavpejic85/mirotalksfu) to share also mp4, webm, ogg videos and mp3 audio :)
For a sharing in real time you can use screen sharing options.

**Comment by fwn0** [comment]
Hi Miro,
this would be a cool extension, because this would be a nice merge with other functions of p2p streamable options. I know, your focus is on p2p video/audio talk, but with these extensions it could be possible to run media-streaming as all-in-one (p2p-miro-multimediamedia-chat-streamer :). Is it possible to run mirotalk in some p2p VPN (p2p in p2p), or is it independent in networks ?

**Comment by miroslavpejic85** [comment]
Hi @fwn0,
I actually share a YouTube video (can add .mp4 - .mp3 as well) by the URL, in this way:

1. A Participant share a URL, that can be for example:
 - https://www.youtube.com/watch?v=RT6_Id5-7-s (This is me 10 year agò, lol)
 - http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4
 - https://www.learningcontainer.com/wp-content/uploads/2020/02/Kalimba.mp3
2. A Iframe is opened in my side and also on all peers in the same room.
3. In the src of the iframe I put the shared URL.
4. The video or audio is autoplayed, anyone can stop, pause, resume, close a shared video/audio.

In this way I not need to broadcast the stream of the video (YouTube, mp4...) - audio (mp3) to all, Just using a html iframe :)

The only difference between broadcasting a video and the trick I use now, and that in the first case, only those who shared the video can pause, resume, play, close, in the second case everyone can do it, but at end the video or audio are always the same :)

You can also try MiroTalk P2P with VPN, as for the MiroTalk P2P logic, take a look at [here](https://github.com/miroslavpejic85/mirotalk/blob/master/public/images/webrtc.png).
If you have pleasure, join with us on [Discord](https://discord.gg/rgGYfeYW3N), we can talk about also there.

Thank you.

**Comment by miroslavpejic85** [comment]
Hey @fwn0.

Commit: https://github.com/miroslavpejic85/mirotalk/commit/3d1ccdb854b2b16f44bd9b37d77a00d636a00976

# Extended Video - Audio Sharing

Added possibility to streaming by URL also for video mp4, webm, ogg and mp3 audio!

# YouTube Sharing

![mirotalk-share-youtube-url](https://user-images.githubusercontent.com/70838434/178949480-d24611a6-9a07-4ba9-b09e-da61de6e3acb.png)
![mirotalk-share-youtube](https://user-images.githubusercontent.com/70838434/178949490-d95f7475-4c1b-4cf0-8751-c7f2a9802065.png)

# Video MP4 Sharing

![mirotalk-share-mp4-url](https://user-images.githubusercontent.com/70838434/178949519-f41713d6-990a-4e15-ae92-4ce77e106131.png)
![mirotalk-share-mp4](https://user-images.githubusercontent.com/70838434/178949535-2801dba2-f137-4ed5-a16b-3b14001816b3.png)

# Audio MP3 Sharing

![mirotalk-share-mp3-url](https://user-images.githubusercontent.com/70838434/178949560-eeee7fb2-edcd-4258-ac46-79529fd17730.png)
![mirotalk-share-mp3](https://user-images.githubusercontent.com/70838434/178949570-b1df74c9-8b77-44c2-bbb5-06ce0c86e0ec.png)

# Full Screen supported and other commands

![mirotalk-mp4-options](https://user-images.githubusercontent.com/70838434/178949588-dd68ef92-ae47-48ef-b86f-bfbef788cd33.png)
