### ISSUE TITLE
Video recording on Docker

### ISSUE THREAD

**Issue by franko108** [miroslavpejic85/mirotalk#111]
Hello, 

just downloaded the latest version in Docker.  
The "Recording" option seems not to work. The options about "Share screen" are opened when pressing "Record" button.   
Can you check that out?   

Also, with the screen sharing seems that share entire screen is not working, it creates endless loops of sharing. This looks as the problem with most of similar software. One window sharing is working properly.

Thank you,    
Best,   
Franko

**Comment by miroslavpejic85** [comment]
Hi Franko,

> The "Recording" option seems not to work. The options about "Share screen" are opened when pressing "Record" button.

This is correct, A long time ago the recording was done only to the webcam + audio, currently the window was opens like when you want to share the screen, allowing you to choose what you want to record (you just have more options).

For example you can recording a screen + audio, a window + audio and so on....

![mirotalk-chose-recording-oprions](https://user-images.githubusercontent.com/70838434/179399735-28308346-6c4c-49af-8783-d832b8c3507c.png)

> Also, with the screen sharing seems that share entire screen is not working, it creates endless loops of sharing. This looks as the problem with most of similar software. One window sharing is working properly.

If you have only one monitor and you share it, this is normal behavior, not a bug. Google meet and other similar apps do too.  :)

Thank you.

**Comment by miroslavpejic85** [comment]
Hi @franko108, If you have pleasure join us on [Discord](https://discord.gg/rgGYfeYW3N) on `help-and-support` channel for question like this. Thank you.

**Comment by franko108** [comment]
Hello, thank you for a quick response.  
Indeed, it works as you said, thanks for discord link as well.

**Comment by miroslavpejic85** [comment]
You are welcome Franco ;)
