### ISSUE TITLE
When joining a room from a direct link, a peer's avatar disappears

### ISSUE THREAD

**Issue by andrea78** [miroslavpejic85/mirotalk#112]
Hi Miroslav. 
Thanks for your great job. When joining a room from a direct link, a peer's avatar disappears and the camera and microphone status icons show as enabled when video and audio status is off.
How to reproduce it?
1. Open two browser windows and paste the direct link https://p2p.mirotalk.com/join?room=test&name=mirotalk&audio=0&video=0&screen=0&notify=0.
2. Now go back to the first browser window. You should see below.
![Screenshot 2022-07-29 at 23-14-34 Click the link to join this call](https://user-images.githubusercontent.com/461774/181846157-3e5cb647-2147-4883-9ff8-44b3aa9eeef2.png)

**Comment by miroslavpejic85** [comment]
Hi @andrea78, 
Thanks for your feedback, you are right, it will be fixed.

**Comment by miroslavpejic85** [comment]
@andrea78 It should all be fixed in the last commit, the management of the audio-video states was not correct.

**Comment by andrea78** [comment]
Yes, everything is working fine now. Thank you.
