### ISSUE TITLE
enablePeer

### ISSUE THREAD

**Issue by dotnethii** [miroslavpejic85/mirotalk#114]
please Add enablePeer in mirotalk 
on/off video and audio for peer
thanks

**Comment by miroslavpejic85** [comment]
Only the presenter (the first that join in the room, and the last one who remaining in the room [gets the presenter rules] ) can mute/hide/eject all or specified peers the other not.
More info about the implementation you can check here: https://github.com/miroslavpejic85/mirotalk/commit/4430f83765076449aa449fced51aafb602972971#commitcomment-81606100

Please for questions/discussions join with us on [Discord](https://discord.gg/rgGYfeYW3N)
Thank you.
