### ISSUE TITLE
Save username in local storage

### ISSUE THREAD

**Issue by regmibijay** [miroslavpejic85/mirotalk#115]
### Feature request

Saving username in local storage might be a really benificial feature as

### Pros

users will not have to enter name everytime

### Additional context

I am not sure if this feature exists, but I think writing username to local storage or as a cookie would definitely make (at least mine) experience better, as entering same name again and again feels repetitive.

**Comment by miroslavpejic85** [comment]
Hello @regmibijay, 
This feature is already implemented here: https://github.com/miroslavpejic85/mirotalk/commit/ff0968fe413e3c4df973b3a82226bfa2121af56a 
Thank you.
