### ISSUE TITLE
On Mobile Screen Sharing Not enough

### ISSUE THREAD

**Issue by vincentpricex** [miroslavpejic85/mirotalk#117]
### Feature request

When you share the screen on the computer mobile user can't select or make full screen. It stays small.. make ppl blind..

### Pros

-

### Additional context

Need to be update

**Comment by miroslavpejic85** [comment]
Hello @vincentpricex,

If you click on the full screen button on mobile, you will be able to see the PC sharing screen on mobile full screen. 

Can you confirm? 

Thank you.

![mobile-full-screen](https://user-images.githubusercontent.com/70838434/190100096-9a7784b2-176c-4a1e-ae39-da7dc348c54d.png)

**Comment by vincentpricex** [comment]
I was going to add ss. It suck just like your screen and that button not working. 
Device : iPhone X
Connection : LTE
System : IOS 15.6.1

As can see i already click that button and null respond , Check it out.

![ccb9f5ae-e7bb-4d02-b792-297a22b0124b](https://user-images.githubusercontent.com/49900792/190101169-030bb4e6-85df-40fa-a735-0bf413d33ec6.jpg)

**Comment by miroslavpejic85** [comment]
Thank you, so the issue is on the Iphone devices. It will be fixed.

**Comment by miroslavpejic85** [comment]
After researching a bit around, Unfortunately using Safari (seems also with other browser too) on an iPhone, doesn't support the [fullscreen API](https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API). So I'm going to hide this button for now on mobile iOS, and looking for an alternative solution if exsist.

**Comment by vincentpricex** [comment]
Sounds a like plan. In my opinion this kind p2p scripts i guess always getting problem with browsers.. I wish developing a app for it would be great solution for that.. Anyway i think you will get around it.
