### ISSUE TITLE
Trun server with static-auth-secret

### ISSUE THREAD

**Issue by alpha856** [miroslavpejic85/mirotalk#118]
Hello,
I think it's better to add  use-auth-secret option and static-auth-secret for custom Turn server setup in mirotalk config file.

**Comment by miroslavpejic85** [comment]
Hello @alpha856,
What you means?
On `.env` file you can setup your own Turn/Stun server like [coturn](https://github.com/coturn/coturn) and set the credential.
Join with us on [discord](https://discord.gg/rgGYfeYW3N) and you can write as well on `idea and suggestions` channel.
Thank you.

**Comment by alpha856** [comment]
I can't setup Turn server in .env file with static-auth-secret and must setup with old user pass method.

**Comment by miroslavpejic85** [comment]
I think you can, check the last part of this article (`Time-Limited Credentials Mechanism`)
https://meetrix.io/blog/webrtc/coturn/installation.html

**Comment by TheSiman** [comment]
Hello @miroslavpejic85,
could the time-limited password generation be built into mirotalk? Synapse does the same thing, [where it uses shared turn secret to generate and serve time-limited password to users](https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html?highlight=turn_shared_secret#turn_shared_secret) on the fly.

I think that's what @alpha856 had in mind.

S.

**Comment by Hamid-Najafi** [comment]
Hello,
I have same problem,
I must edit our coturn configuration to support user pass method. (its configured using auth-secret)
and its not recommended to use both user-pass and auth-secret credential with coturn...

**Comment by nebulade** [comment]
Hi I am currently looking to package mirotalk for Cloudron and I am facing the same issue. On Cloudron we use coturn with 
```
use-auth-secret
static-auth-secret=<uniquesecret>
```
instead of username/password.

Tracing the code a bit, I guess maybe at https://github.com/miroslavpejic85/mirotalk/blob/3140fef7928aa331f0a68a886e8cdc0f88c8d0f0/app/src/server.js#L138 an option to pass in that secret instead of username/password then it has to be handled differently later in the code?

Not an expert on the topic, so maybe what @miroslavpejic85 suggested can craft a username/password pair already, but I couldn't read that out of the proposed link.

**Comment by AlbanDAVID** [comment]
For those a little bit lost (as I was). I wrote this article : https://wiki.lenuagemagique.com/doku.php?id=unable_to_use_lt-cred-mech_webrtc_and_static-auth-secret_restapi_at_the_same_time

**Comment by programster** [comment]
Sorry to bring up an old issue, but did this get concluded in the end? I can't tell from reading the template env file if the `TURN_SERVER_CREDENTIAL` setting:.

![Image](https://github.com/user-attachments/assets/caf904ff-4580-4703-9fbf-7e258b836489)

...is expected to be a static password for a user (`lt-cred-mech`), or if it is the shared secret from properly securing a TURN server using as described in the previous post using the `use-auth-secret` security method instead.
