### ISSUE TITLE
Chat Bug

### ISSUE THREAD

**Issue by Ronald-2** [miroslavpejic85/mirotalk#119]
Hey @miroslavpejic85,
while chatting on this app I noticed that there is a security risk. People can start up HTML codes in the chat.
Like ```<img src onerror="alert('hacked!')"/>```  will alert the user. I think this is known as XSS vulnerability.

**Comment by miroslavpejic85** [comment]
Hello @Ronald-2, 
I solved it some time ago [here](https://github.com/miroslavpejic85/mirotalk/issues/103) I made a few changes in the chat, But it doesn't execute in attendee chat, only on your side, it's shouldn't be a risk.

**Comment by miroslavpejic85** [comment]
PS: Try now please, I made a small change in [this commit](https://github.com/miroslavpejic85/mirotalk/commit/dfa5aaff1512de0f4caa14e7ecd2cf8c31ae2677). Thank you.
