### ISSUE TITLE
Add a custom hex color picker in whiteboard color options

### ISSUE THREAD

**Issue by anshuman2166AppproDev** [miroslavpejic85/mirotalk#12]
Mirotalk is seriously growing fastly along with best features, I saw even whiteboard got implemented. It was really good but, it would have been good if it had cutom hex color picker

**Comment by miroslavpejic85** [comment]
Yeah Thanks, Yesterday I made a first draft, 
this implementation will also be made soon.

**Comment by anshuman2166AppproDev** [comment]
Awesome 😎

**Comment by anshuman2166AppproDev** [comment]
Aceept my pull for donate button

**Comment by anshuman2166AppproDev** [comment]
Please 🥺

**Comment by miroslavpejic85** [comment]
done: https://github.com/miroslavpejic85/mirotalk/commit/7546de83ef08d4897fbf9e6236b39ef59e5c779b

**Comment by miroslavpejic85** [comment]
Regarding `Donate` button is nice, 
i answered you here: https://github.com/miroslavpejic85/mirotalk/pull/11#issuecomment-828653612
