### ISSUE TITLE
Wonderful Script.

### ISSUE THREAD

**Issue by mackiexx** [miroslavpejic85/mirotalk#123]
This is a very nice project. i will like to suggest that people who are on live videos can be shown on the homepage and the user who goes on live can choose strictly by invite or public can join. that way, users who might need audience for gaming will get it. and there should be option for users to just join and request for video if they want but they can just be the audience

**Comment by miroslavpejic85** [comment]
Hello @mackiexx ,

Thank you, I'm glad you like it :)

Please join with us on [Discord](https://discord.gg/rgGYfeYW3N) 
- channel `ideas-and-suggestions`

Have a nice day.
