### ISSUE TITLE
Please read--Name NOT updating...

### ISSUE THREAD

**Issue by SirRomeo9029** [miroslavpejic85/mirotalk#124]
Hello Miroslav Pejic,
I wanted to report a bug that when you change your name, it **doesn't update the name (or avatar) in the chat or the captions section**. [Here Take a look (video)](https://user-images.githubusercontent.com/118411677/202341004-665fb1eb-ec34-4f7c-8a47-76e185df6141.webm)

Thank You.

<hr>

**Comment by miroslavpejic85** [comment]
Hello @SirRomeo9029,
Thank you for the report, it should be fixed.
