### ISSUE TITLE
Chat is not working.

### ISSUE THREAD

**Issue by Fandoser** [miroslavpejic85/mirotalk#125]
### Describe the bug

The messages that are sent through the chat don't reach the recipient. All the options that are inside the chatbox are not operational: send emoticons, share images, send private messages or send files. Although sharing youtube links is working.

### To Reproduce

Open the chatbox and try to send any message, file, etc

### Expected behavior

Everyone in the room should get the messages, files, etc

### Desktop - Mobile

Please complete the following information:

I've tested it on different devices, computer and smartphones

 - Device or OS: Android MIUI 12, 13. LineageOS Android 12. Virtual Emulator Android 9. 
 - Browser: Brave, Opera, Chrome
 - Version: Lastest

### Additional context

I have installed mirotalk on my own website and some features aren't working. I don't think I have installed it incorrectly, I have followed all the steps carefully.
Another aspect to highlight is that you necessarily have to activate your camera and microphone to enter a room. If you don't do it, it doesn't allow you to access.

**Comment by miroslavpejic85** [comment]
Hello @Fandoser,

> I have installed mirotalk on my own website and some features aren't working. I don't think I have installed it incorrectly, I have followed all the steps carefully.

Regarding the chat:

1. Are you alone in the room when you try to send messages... or there also some participants? 
2. It also happens in the [official live demo](https://p2p.mirotalk.com) too? 

> Another aspect to highlight is that you necessarily have to activate your camera and microphone to enter a room. If you don't do it, it doesn't allow you to access.

For now you can access without activate your cam (maybe some users don't have a webcam) but nowadays everyone has a built-in microphone.

Giving permissions doesn't mean that the webcam and microphone will be used, before entering the room, you can always disable them at will.

![mirotalk-no-cam-microphone](https://user-images.githubusercontent.com/70838434/202928459-b39d4658-8c12-4bfb-897a-8a540f3c5b74.png)

PS: I see that you created an account 2 hours ago, that you didn't even fork the project, please, remember to respect the `AGPLv3` License too. Thank you for understanding.

**Comment by Fandoser** [comment]
Thanks for replying!

> 1. Are you alone in the room when you try to send messages... or there also some participants?
> 2. It also happens in the [official live demo](https://p2p.mirotalk.com/) too?

1. I think it's not possible to send messages if you are alone in the chat. However, there were 2 participants in the room, I was testing to see how it worked.
2. The last time I tried it worked. I'm going to test it again.

> For now you can access without activate your cam (maybe some users don't have a webcam) but nowadays everyone has a built-in microphone.
> 
> Giving permissions doesn't mean that the webcam and microphone will be used, before entering the room, you can always disable them at will.

I wasn't able to enter any room if I didn't have both permissions enabled. The page constantly reloaded and wouldn't let me in until I enabled the camera and microphone.

> PS: I see that you created an account 2 hours ago, that you didn't even fork the project, please, remember to respect the AGPLv3 License too. Thank you for understanding.

I didn't quite get this. Why do you want me to fork the project?

**Comment by miroslavpejic85** [comment]
> he last time I tried it worked. I'm going to test it again.

Please test always the [official live demo](https://p2p.mirotalk.com), and if you have your own instance, make sure to be aligned with the last commits and If you see changes in the commits on server side (server.js) remember also to restart your instance of MiroTalk.

> I wasn't able to enter any room if I didn't have both permissions enabled. The page constantly reloaded and wouldn't let me in until I enabled the camera and microphone.

Not really, as you can see, I allowed the join room if someone not has at all the webcam in this commit: https://github.com/miroslavpejic85/mirotalk/issues/110

<img width="1401" alt="mirotalk-no-cam" src="https://user-images.githubusercontent.com/70838434/202988402-d0953cfd-122f-43db-850d-b67e9e7729d6.png">

<img width="1401" alt="mirotalk-join" src="https://user-images.githubusercontent.com/70838434/202988414-9ad4929b-d6f6-46b6-9b28-50ed76e56f6a.png">

> I didn't quite get this. Why do you want me to fork the project?

If you want to use MiroTalk in your private project and customise it, you need to respect the AGPLv3 license. Check the condition of License in the README.

PS: You can join also with us on 👉 [Discord](https://discord.gg/rgGYfeYW3N) 👈, ask also if you have questions, doubts etc, before to open issue here, and make sure that is really related to MiroTalk P2P Live demo.

However, I tested it on android, and for me the chat work well.

Thank you and have a nice day.

**Comment by Fandoser** [comment]
> Please test always the [official live demo](https://p2p.mirotalk.com/), and if you have your own instance, make sure to be aligned with the last commits and If you see changes in the commits on server side (server.js) remember also to restart your instance of MiroTalk.

Yes, I did tested the first time and if this document is still valid: https://github.com/miroslavpejic85/mirotalk/blob/master/docs/self-hosting.md
I think I've set it up everything correctly.

> If you want to use MiroTalk in your private project and customise it, you need to respect the AGPLv3 license. Check the condition of License in the README.

I am far from being able to work on a project as complex as the one you have created. It's not my intention.
I thought it was necessary to set it up the application on my own website since you had said that mirotalk was only a demo version to test its features.

I have tried miratalk again and still have the problem of not receiving chat messages.

I've tested it on these two devices:
Brave for windows desktop 
Firefox for android 12

I haven't been able to send a message, emoticon, etc

Thanks for the invitation to your discord group. I'll try to register and join as soon as I can.

**Comment by miroslavpejic85** [comment]
> I've tested it on these two devices:
> Brave for windows desktop
> Firefox for android 12

I tested it on MiroTalk live demo and seems ok.

![mirotalk-win10-android](https://user-images.githubusercontent.com/70838434/203024965-9df9e8c5-7655-4cb9-884a-3d3d5bce4df1.PNG)

> I think I've set it up everything correctly on my website.

I don't know, you can send me on Discord in private the link of your instance of MiroTalk, so I can take a look.


> Thanks for the invitation to your discord group. I'll try to register and join as soon as I can.

Good, you are welcome, so I'm going to close this task.
