### ISSUE TITLE
P2P + SFU

### ISSUE THREAD

**Issue by SirRomeo9029** [miroslavpejic85/mirotalk#127]
Hey @miroslavpejic85, 
So I was thinking of opening a pull request to this repository. And before opening the request I wanted to test my edits, and it didn't work. After an hour of staring at code, I tried it again and it did worked!!

Soon I realized it was some type of error in STUN/TURN server. And I thought of adding a hybrid WebRTC system in MiroTalk, an SFU and P2P (if WebRTC Mesh fails, SFU takes over). I tried to add in the SFU with [MediaSoup](https://mediasoup.org) but it actually didn't work.

Is there a way we can add a hybrid system to Mirotalk (if WebRTC Mesh fails then SFU takes its place)?  

Thank You,

Note: My English is not the best...I hope you get my point of hybrid system!

**Comment by miroslavpejic85** [comment]
Hello @SirRomeo9029 and welcome! :) 

> Is there a way we can add a hybrid system to Mirotalk (if WebRTC Mesh fails then SFU takes its place)? 

Currently not, this version is strictly P2P, if you want to try SFU, check out the [MiroTalk SFU project here](https://github.com/miroslavpejic85/mirotalksfu)

The [Difference here](https://github.com/miroslavpejic85/mirotalksfu/issues/14#issuecomment-932701999)

Please join with us on [Discord](https://discord.gg/rgGYfeYW3N), for questions, discussions like this one.

Thank you and have a nice day.
