### ISSUE TITLE
Discussion...

### ISSUE THREAD

**Issue by SirRomeo9029** [miroslavpejic85/mirotalk#129]
Hey @miroslavpejic85,
I'm not sure if you are aware and if the LICENSE allows you to, but one of your sponsors (LuvLounge) is using the exact copy of your code in their website without giving you credits.

You can find it here --> [https://p2p.luvlounge.ca/](https://p2p.luvlounge.ca/) . If you scroll down and click 'Join,' nothing will happen. But if you go to [https://p2p.luvlounge.ca/newcall](https://p2p.luvlounge.ca/newcall) and then click 'Join,' you will see. Also, only this link ([https://p2p.luvlounge.ca/join/7169dd05-aa0a-4144-87f0-8593c14492ce](https://p2p.luvlounge.ca/join/7169dd05-aa0a-4144-87f0-8593c14492ce)) will get you in a meeting, everything else (such as [https://p2p.luvlounge.ca/join/some-room](https://p2p.luvlounge.ca/join/some-room)) will lead you to the home page.

There are some buttons/functions deleted (like raise hand) while some were added but the main architecture is the same. 

If you like, go to the 'Inspect' option (right click and the button will be at the end of the menu) and then click sources on the top bar. Navigate yourself to js/client.js to see the code for that file.

Thank You

**Comment by miroslavpejic85** [comment]
Hi @SirRomeo9029,
For discussions, please join us on [Discord](https://discord.gg/rgGYfeYW3N). 
However everything is in order, I customized that site, and it is in compliance with the commercial license ;)
