### ISSUE TITLE
Allow Permission is Not Showing 

### ISSUE THREAD

**Issue by chowdhurysoumalya** [miroslavpejic85/mirotalk#13]
[https://mirotalk.herokuapp.com/](https://mirotalk.herokuapp.com/)
When I am Trying to Join any Room It Should Ask For Microphone and camera permission 
But It is Not Asking 

Again and again it is Giving Access Denied  

Please Help me 

I am attaching The Screen Shot Of It
![Screenshot (13)](https://user-images.githubusercontent.com/46195122/116703569-108b3f00-a9e8-11eb-94c5-ad6f77541332.png)

**Comment by miroslavpejic85** [comment]
Hi @livingloves, welcome!
Maybe you didn't give permission the first time by mistake, try this
Both for Camera and Microphone.
![image](https://user-images.githubusercontent.com/70838434/116709917-76200100-a9d1-11eb-8532-127f42f240c2.png)

**Comment by Jaideep25** [comment]
@miroslavpejic85  actually in some cases, this doesn't show up because you can block access to camera system wide so it doesn't show the pop-up... @livingloves  try to check whether you have blocked camera and microphone system wide! Thanks!

**Comment by miroslavpejic85** [comment]
I added that the getUserMedia error type is displayed: https://github.com/miroslavpejic85/mirotalk/commit/3f8d04f5bfc5b7ca2d10fb08606a67307be62a5d
<img width="527" alt="getUserMediaError" src="https://user-images.githubusercontent.com/70838434/119194565-8f254a80-ba83-11eb-86eb-819af9eb5a7b.png">

**Comment by Jaideep25** [comment]
Yup xD, more cool! 😋

**Comment by Extarys** [comment]
Should it work if I only have a microphone plugged in? I'm with some folks on a Mozilla channel and we are trying to figure out what is going on. Some people say it works, some don't.

I understand this might not be a mirotalk issue but any help to make this work is welcome.

**Comment by Jaideep25** [comment]
Hey @Extarys  welcome!
Actually mirotalk needs both audio and webcam, otherwise it doesn't work, please do check if you have disabled webcam and mic access systemwide or your browser... 
Thanks! Hope it helps!

**Comment by Extarys** [comment]
Thanks! I don't have a webcam so that is the problem - cat ate the wire. Also the error is "The request is not allowed by the user agent or the platform in the current context.". Could we change the error so it's a little bit more precise? I've been troubleshooting my firefox setup for at least an hour :stuck_out_tongue_closed_eyes:

**Comment by Jaideep25** [comment]
Ah sad to know that your cat ate up the wire 😂😂, I'll let @miroslavpejic85 know about the enhancement! ;)

**Comment by miroslavpejic85** [comment]
Hey @Extarys welcome! 🙂
So your cat has eaten the webcam wire and mirotalk won't start? 😅
As for the error you see on that page after `Access Denied`, It's `not writed by me`, but it's the `getUserMedia Api error` if `something wrong` as you can see here: https://github.com/miroslavpejic85/mirotalk/blob/master/www/js/client.js#L1365 . I can improve that to not print only the `error.message` but all the `error` maybe it's better ...
Here you can found the common `getUserMedia` errors: https://blog.addpipe.com/common-getusermedia-errors/

**Comment by miroslavpejic85** [comment]
Done: https://github.com/miroslavpejic85/mirotalk/commit/62d4a66ab426bc0f1515e79c548c6b54cddb5c60

**Comment by miroslavpejic85** [comment]
@Extarys @Jaideep25 
Do I have to do something else for this task or do we close it? 🙂

**Comment by Jaideep25** [comment]
Nope you can close it! Problem was solved!
