### ISSUE TITLE
make isHttps configurable from env variables

### ISSUE THREAD

**Issue by shekspir55** [miroslavpejic85/mirotalk#130]
### Feature request

Add env variable for isHttps parameter. The current approach doesn't seem very intuitive and I spent about an hour diving into documentation trying to understand how to enable self-signed certs. 

### Pros

While using docker or any other deployment I don't want to dive into changing any source codes.

I can create a PR if you wish.

Thank you for the great work!

**Comment by shekspir55** [comment]
Also docker image in the hub seems outdated

**Comment by miroslavpejic85** [comment]
Hello @shekspir55,

You are right, [done](https://github.com/miroslavpejic85/mirotalk/commit/8432f3c0cfeb6c014357a3c471aea3b85a703d9a)

> Also docker image in the hub seems outdated

The [official docker image](https://hub.docker.com/r/mirotalk/p2p) is always updated to the latest changes on GitHub, the [live demo](https://p2p.mirotalk.com) uses that image.

I'm glad you like the project and thank you for the feedback.

Have a good day.
