### ISSUE TITLE
Selfhosting Mirotalk but Camera/Microphone permission settings are blocked in Microsoft Edge (108)

### ISSUE THREAD

**Issue by tigerinus** [miroslavpejic85/mirotalk#131]
### Describe the bug

Unable to enable Camera/Microphone permission. (See the screenshot below.)

### To Reproduce

Just followed the steps on my own VM in the cloud.

### Screenshots

![image](https://user-images.githubusercontent.com/7172560/209169226-0a8d56fa-139c-4831-a10d-4643753e53ca.png)

### Desktop - Mobile

Please complete the following information:

 - Device or OS: Windows
 - Browser: Microsoft Edge
 - Version: 108

### Additional context

```env
# Enable self-signed certs (app/ssl)

HTTPS=false

# Signaling Server listen port

PORT=3000

# Ngrok
# 1. Goto https://ngrok.com
# 2. Get started for free 
# 3. Copy YourNgrokAuthToken: https://dashboard.ngrok.com/get-started/your-authtoken

NGROK_ENABLED=true
NGROK_AUTH_TOKEN=<masked>

# Stun
# Check: https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/

STUN=stun:stun.l.google.com:19302

# Turn
# Recommended: https://github.com/coturn/coturn
# Check: https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/

TURN_ENABLED=false
TURN_URLS=turn:YourTurnServer
TURN_USERNAME=YourTurnUsername
TURN_PASSWORD=YourTurnPassword

# API
# The response will give you a entrypoint / Room URL for your meeting.
# curl -X POST "http://localhost:3000/api/v1/meeting" -H  "authorization: mirotalk_default_secret" -H  "Content-Type: application/json"

API_KEY_SECRET=mirotalk_default_secret

# Survey URL 
# Using to redirect the client after close the call (feedbacks, website...)

SURVEY_ENABLED=true
SURVEY_URL=https://www.questionpro.com/t/AUs7VZq00L

# Sentry (optional)
# 1. Goto https://sentry.io/
# 2. Create account
# 3. Goto Settings/Projects/YourProjectName/Client Keys (DSN)

SENTRY_ENABLED=false
SENTRY_DSN=YourClientKeyDSN
SENTRY_TRACES_SAMPLE_RATE=1.0

# Slack Integration (optional)
# 1. Goto https://api.slack.com/apps/
# 2. Create your app
# 3. On Settings - Basic Information - App Credentials chose your Signing Secret
# 4. Create a Slash Commands and put as Request URL: https://your.domain.name/slack

SLACK_ENABLED=false
SLACK_SIGNING_SECRET=YourSlackSigningSecret

# Auto deploy on Railway
# https://railway.app/new/template/mirotalk?referralCode=mirotalk
```

**Comment by miroslavpejic85** [comment]
No MiroTalk related issues here,

Please, not open issues for  questions, help and support, but join with us on [Discord](https://discord.gg/rgGYfeYW3N).

Channels:
    - help & supports

Thank you for understanding.

**Comment by miroslavpejic85** [comment]
PS: Tested the official live demo, on VM, Windows 10, Microsoft Edge: Version 108.0.1462.54 (Build official) (64 bit), no issues found.

<img width="908" alt="mirotalk-p2p-win-10-edge-latest" src="https://user-images.githubusercontent.com/70838434/209192585-8d17c997-5e1e-48b3-a27c-d376a8878a60.png">

**Comment by tigerinus** [comment]
Have u tried a selfhosted mirotalk on a local device?

**Comment by miroslavpejic85** [comment]
> Have u tried a selfhosted mirotalk on a local device?

Check out also [this documentation](https://github.com/miroslavpejic85/mirotalk/blob/master/docs/ngrok.md)
