### ISSUE TITLE
[Feedback] Too many external traffic even in selfhosted environment

### ISSUE THREAD

**Issue by tigerinus** [miroslavpejic85/mirotalk#132]
![image](https://user-images.githubusercontent.com/7172560/209171494-f9f406ad-4eff-4df5-a666-fb9193f2b79b.png)

To maximize privacy protection:

- Would be nice to include any necessary dependencies in the container .
- Traffic to Google Analytics/Translate would be unnecessary.

**Comment by miroslavpejic85** [comment]
Please, not open issues for feedback, questions, help and support, but join with us on [Discord](https://discord.gg/rgGYfeYW3N) channels: help & supports - idea & suggestions
Thank you for understanding.
