### ISSUE TITLE
admin can turn users on/off

### ISSUE THREAD

**Issue by dotnethii** [miroslavpejic85/mirotalk#134]
Users' cameras and microphones must be turned off when logging in. Please admin can turn users' cameras and microphones on and off And on.

**Comment by miroslavpejic85** [comment]
Hello @dotnethii,

For privacy, i can't force to turn ON a guest audio or video. As initiator of the room i can mute audio or hide video of all the guests or specified one. 

So the guests, by show of hands and consent of the initiator, can activate by yourself their own audio or camera.

What I could possibly do is to send a notice that I would like to enable the audio of a specific participant, and then he will decide if want do it, even if I don't see the usefulness, when I can say it verbally during the meeting if necessary, or seeing who has their hand raised.

Join with us on [Discord](https://discord.gg/rgGYfeYW3N) - channel: `ideas and suggestions` and we can talk about.

Thank you.
