### ISSUE TITLE
Hanging on please allow camera or microphone when running from docker

### ISSUE THREAD

**Issue by ghamandipp** [miroslavpejic85/mirotalk#136]
```
Error
client.js:1599 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getUserMedia')
    at initEnumerateAudioDevices (client.js:1599:10)
    at initEnumerateDevices (client.js:1562:11)
    at Socket.handleConnect (client.js:881:15)
    at Emitter.emit (index.mjs:136:20)
    at Socket.onconnect (socket.js:415:14)
    at Socket.onpacket (socket.js:318:26)
    at Emitter.emit (index.mjs:136:20)
    at manager.js:207:18
```

**Comment by ghamandipp** [comment]
![image](https://user-images.githubusercontent.com/21212816/213645956-a3bb8828-b936-4d63-bf07-2db4b2c099a4.png)

**Comment by miroslavpejic85** [comment]
Hello @ghamandipp,
I'm not able to reproduce it, using the latest official images on my Local PC.

<img width="1318" alt="mirotalk-p2p-docker-latest" src="https://user-images.githubusercontent.com/70838434/213761772-9de1370f-a776-4321-a22e-3bb65f7251db.png">

<img width="852" alt="mirotalk-p2p-docker-latest-ok" src="https://user-images.githubusercontent.com/70838434/213761826-6a1e71d3-f159-4638-a5bd-64fd5cf00f4e.png">

Try exposing it in `https` as well.
Ps: Join with us [Discord](https://discord.gg/rgGYfeYW3N) - channel help & support, here you can also found answers.
Thank you and have a good day.

**Comment by jediwarpraptor** [comment]
Having this exact same issue.  Does the server require an externally addressable IP (my ISP is behind CGNAT)
