### ISSUE TITLE
random users in private messgaing

### ISSUE THREAD

**Issue by professionalNoob123** [miroslavpejic85/mirotalk#137]
### Describe the bug

There are undefined/unidentified users seen in a locked meeting room.

### To Reproduce

1. Go to a meeting (any room)
2. Click on lock meeting
3. Make someone else join it...
4. Go to chat box
5. click the private messaging button
6. See error

### Expected behavior

I expected to only see one person in private messaging but I am able to see 2 (undefined users).

### Screenshots

![Screenshot 2023-02-09 9 04 40 PM](https://user-images.githubusercontent.com/124847745/217982521-105f5079-ad3a-45c0-985a-9da152cc7c34.png)

### Desktop - Mobile

Please complete the following information:

 - Device or OS: Mac, windows
 - Browser Chrome, Safari
 - Version: Big Sur, Windows 10

**Comment by miroslavpejic85** [comment]
Hello @professionalNoob123, Can you try now, Thank you!
