### ISSUE TITLE
Screensharing and Raise hand

### ISSUE THREAD

**Issue by Jaideep25** [miroslavpejic85/mirotalk#14]
Hi @miroslavpejic85 !
As you had told I have made the issue, some modifications you can do as follows!

- Could you please do something like, when you screenshare, and turn your video off, the screen share should still work, and the video shouldn't turn on, when you stop sharing.
- And when you raise your hand the video should get highlighted, because, if someone's video's bg is green, and when they raise their hand, it won't be seen clearly.

Hoping you can add these in your code! Waiting for your reply!
Regards.

**Comment by miroslavpejic85** [comment]
Hi @Jaideep25, 
Thanks for the tips. 
I'll improve that part.

**Comment by miroslavpejic85** [comment]
@Jaideep25 - For the raise hand, I added the black background, pulsate effect, and sound notification: https://github.com/miroslavpejic85/mirotalk/commit/c13f1b867dd14420157624af007d77ab0e5d8146

**Comment by Jaideep25** [comment]
Woah amazing!! You're really amazing!

**Comment by miroslavpejic85** [comment]
@Jaideep25 - For the screen sharing, i solved in this way: https://github.com/miroslavpejic85/mirotalk/commit/fa92415ca639ee6aebae2fe4464a6bdde5ad0bed

**Comment by Jaideep25** [comment]
Oh not bad! You're clever!

**Comment by anshuman2166AppproDev** [comment]
Epic sir @miroslavpejic85 😊

**Comment by Jaideep25** [comment]
Ikr! So, I can close the comment? @miroslavpejic85
