### ISSUE TITLE
camera and microphone are not recognized

### ISSUE THREAD

**Issue by eleaner** [miroslavpejic85/mirotalk#141]
### Describe the bug

I implemented mirotalk in my domain
when trying to run it, I get this - while access camera and microphone are allowed
![image](https://user-images.githubusercontent.com/5169203/222575927-19922968-0b0a-4d9b-acc5-598c5b7484b1.png)

### To Reproduce

I am not sure
running chrome Version 110.0.5481.100 (Official Build) (x86_64) 
on OSX 12.6.2 (21G320)

### Expected behavior

I should be able to join the call

### Screenshots

see above

### Desktop - Mobile

see above

### Additional context

it seems to be working from my phone

**Comment by miroslavpejic85** [comment]
Hello @eleaner,

Have you checked to make sure another app isn't using the webcam or microphone in the background? Do you use Skype or something similar? If so, close the other apps and retry. 

Thank you.

**Comment by eleaner** [comment]
thank you
I am not sure what happened, but it suddenly started working
I will keep an eye on it.

is there a place I could simply ask some quesitons?

**Comment by miroslavpejic85** [comment]
You are welcome!

> is there a place I could simply ask some quesitons?

Yes please, join with us on [Discord](https://discord.gg/rgGYfeYW3N) where you can also find many answers and interact with others.

**Comment by eleaner** [comment]
done, questions asked
