### ISSUE TITLE
api_key_secret 

### ISSUE THREAD

**Issue by majidjamhsidi** [miroslavpejic85/mirotalk#142]
hi i have a few question 

1) how get api_key_secret ?

2)this software work in localhost:3000 after clone as git , but after upload on server , show message please allow camera or mic and don't show any thing and don't work !!!!

3) Is this software completely free? or need pay

**Comment by miroslavpejic85** [comment]
Hello @majidjamhsidi,

1. Is specified in the .env file (API_KEY_SECRET)
2. Expose it on HTTPS, all documentations are provided in the README.md - docs/self-hosting.md
3. It's free under `AGPLv3` license, also specified in the README.md

Please, for questions join with us on [Discord](https://discord.gg/rgGYfeYW3N)
Thank you.

**Comment by majidjamhsidi** [comment]
hi @miroslavpejic85 . 

I did not get my answer !!!

1) my question is : where can I get the api_secret_key ? Is it necessary to have this code ? 
2) i am use ssl !!! https://karaconnect.ir

best regurd @miroslavpejic85

**Comment by Jaideep25** [comment]
Hello @majidjamhsidi,
Please go through this https://github.com/miroslavpejic85/mirotalk/blob/master/README.md#L189 .

Thanks.

**Comment by majidjamhsidi** [comment]
hi @Jaideep25 . 

I asked a few questions , but you are send read me !!! why send read me ? Do you think I did not read the read me file ? 

If you don't know the answer to my question , please don't send anything .

**Comment by miroslavpejic85** [comment]
Thanks @Jaideep25 ❤️ 

@majidjamhsidi Please try to be kind to those who try to help you in their own way, simply Jaideep25 wanted to point out that if you read the whole **README** well you can find the answers both what **api_key_secret** is for, and **how to install MiroTalk P2P correctly on your VPS or dedicated server**. If the problem you mentioned in point 2 does not concern the official live demo: https://p2p.mirotalk.com, you are probably missing something in your installation. Without even providing us the console logs of the browser, on which VPS - OS and more information about, how do you think someone can help you, simply saying it doesn't work :)

For questions about the project, you can join with us on discord, where you can interact with other people and often find answers without even having to open issues here, which are usually for confirmed bugs or some requests that we can also discuss first in the channel ideas and suggestions in the forum. Type too many exclamation marks and mention n. times the same person, I'm telling you from experience, it doesn't help :)

I'll try to answer you anyway:

> my question is : where can I get the api_secret_key ? Is it necessary to have this code?

The api_secret_key is used for MiroTalk API, to prevent unauthorized calls to the API endpoint in case you don't want them to be public, documentation about it can be found here

An example API call from curl:

```bash
curl -X POST "https://p2p.mirotalk.com/api/v1/meeting" -H "authorization: mirotalk_default_secret" -H "Content-Type: application/json"
```

The response will give you an entrypoint/Room random URL for your meeting, where authorization: API_KEY_SECRET is specified in the .env file. More calls from different languages you can found also [here](https://github.com/miroslavpejic85/mirotalk/tree/master/app/api)

> i am using ssl !!! https://karaconnect.ir

Not just SSL is enough, is the server started? What do you see in the server side log console? What do you see in the client side log console? Following the logs you can trace the cause of the problem and did you follow the step by step documentation provided here?

Thank you for understanding and I wish you a good evening.

**Comment by majidjamhsidi** [comment]
Hello again  . I tried and uploaded the site to the server. I did the work with pm2. Currently, the site comes up with http and on port 3000:

http://live.karainfo.ir:3000

But, when I set .htaccess as follows »

RewriteEngine On

# Redirect HTTP to HTTPS
RewriteCond %{HTTPS} off
RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

# Serve static files directly (if needed)
# Replace '/public' with the directory where your static files are located
RewriteCond %{REQUEST_URI} !^/public
RewriteRule ^(.*)$ public/$1 [L]

# Proxy requests to Express.js application
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ http://live.karainfo.ir:3000/$1 [P]


The site gives 404. what is the reason ? How can I activate the site with https(ssl)?

**Comment by majidjamhsidi** [comment]
resolve top error with remove /$1 in htaccess .


 but now returning error  :

Your clock is behind

my computer time and date is ok ???!!!! 


how resolve this ?
