### ISSUE TITLE
Zoom function during screen sharing

### ISSUE THREAD

**Issue by l4rm4nd** [miroslavpejic85/mirotalk#145]
### Feature request

Microsoft Teams provides a zoom feature for meeting participants during a screen sharing event.

### Pros

Especially when sharing from an ultrawide monitor, some meeting participants are overwhelmed by the shared screen size. Although the screen sharer may just select a better input for sharing, e.g. only a specific window, it would be great to have a zoom feature.

Participants would then be able to zoom into the shared screen to inspect a specific area in more detail.

**Comment by miroslavpejic85** [comment]
Hello @l4rm4nd, 
Added zoom video in-out functionality.

<img width="413" alt="mirotalk-zoom-in-out" src="https://user-images.githubusercontent.com/70838434/224266895-c1eeaccb-f5ca-42c4-9043-f9a9174ce0a0.png">

**Comment by l4rm4nd** [comment]
Hi @miroslavpejic85,

good first addition. I still get some bugs though:

- if you fullscreen a screen share now, the whole video flickers. This was not the case beforehand. Guess this is a bug.
- although we are able to zoom into a screenshare now, we are locked in center view. So we cannot decide where we want to zoom in. So it would be great if the user can choose the zoom area of the shared screen. For example if we want to inspect the top left of a screen share in more detail.

**Comment by Jaideep25** [comment]
Hey @l4rm4nd ,
How about we fix that issue by adding a draggable hand cursor into the video? 👀 (the drag and drop cursor)
It would be easier for the person to navigate on their own ;)
Thanks !

**Comment by l4rm4nd** [comment]
> by adding a draggable hand cursor into the video

Sure, if this allows dragging the screenshare to a prefered area. 

> I'm not able to reproduce the flickering screen

Just tried it again. Did not occur to me again. May have been a temporare browser bug. Will observe whether it occurs again or not. Thanks for verifying.

**Comment by miroslavpejic85** [comment]
Hi @l4rm4nd & @Jaideep25 

> I'm not able to reproduce the flickering screen error as you described, maybe @miroslavpejic85 could? 😅

I'm not able too :)

> although we are able to zoom into a screenshare now, we are locked in center view. So we cannot decide where we want to zoom in. So it would be great if the user can choose the zoom area of the shared screen. For example if we want to inspect the top left of a screen share in more detail.

> How about we fix that issue by adding a draggable hand cursor into the video? 👀 (the drag and drop cursor)
It would be easier for the person to navigate on their own ;)

I'm looking at something like this: https://codepen.io/stack-findover/pen/VwPgQQr, but don't want to lose the functionality when clicking the video element to going to full screen...

**Comment by Jaideep25** [comment]
Hey,
Okay so to handle that,
Double click will be reserved to zoom-in/out & for dragging image within the div (take a look at this ~ https://codepen.io/jonathan/pen/abNGbE)
Single click as usual for full screen ;)
Thanks !

**Comment by miroslavpejic85** [comment]
> Double click will be reserved to zoom-in/out

Added zoom-in/out on mouse wheel, I think is better and fastest way to do it on desktop devices.

Now we missing only to move with the mouse when video zoomed in to the desired area and i think we're there.

**Comment by miroslavpejic85** [comment]
At present, we have implemented zooming in and out on video using the mouse wheel, with corresponding buttons available in the video menu (by default, these buttons are disabled). Currently, our zoom functionality operates at the center of the video. `If there is a need for more specific zooming in particular areas` of the content, here the snippet from where start on and improve:


```js
    video.addEventListener('wheel', (e) => {
        e.preventDefault();

        if (isVideoOf(id) || isVideoPrivacyMode(video)) return;

        // Calculate the cursor position within the video
        const rect = video.getBoundingClientRect();
        const cursorX = e.clientX - rect.left;
        const cursorY = e.clientY - rect.top;

        // Adjust the zoom speed here (you can change this value)
        const scaleFactor = e.deltaY > 0 ? 0.9 : 1.1;

        // Calculate the new scale
        zoom *= scaleFactor;

        // Set minimum and maximum zoom levels if needed
        zoom = Math.max(1, Math.min(15, zoom));

        // Set the new scale for the video
        video.style.transformOrigin = `${cursorX}px ${cursorY}px`;
        video.style.transform = `scale(${zoom})`;
    });
```
@l4rm4nd `If there is NOT a need for more specific zooming in particular areas` we can close this task ;)
Thank you and have a great day.

**Comment by l4rm4nd** [comment]
Hi @miroslavpejic85 ,

thanks for the update. 

Personally, I would like to have a more specific zoom feature where the zoom happens based on the mouse position in the screen share. So people would be able to zoom anywhere in the screen share to inspect details. 

The current implementation is great so far but the center zoom only is limiting. Maybe someone finds time to implement this.

Cheers!

**Comment by miroslavpejic85** [comment]
@l4rm4nd Done: I'm sticking with the `default` setting for `zooming at the cursor position`, but there's also the option to configure the zoom center mode on `client.js`.

```js
/**
 * Determines the video zoom mode.
 * If set to true, the video zooms at the center of the frame.
 * If set to false, the video zooms at the cursor position.
 */
const ZOOM_CENTER_MODE = false;
```

Have a great weekend.

**Comment by mostafa321** [comment]
on **_Safari_** Apple or IOS production server always give me error "**Websocket connection to wss://xxxxxxxx failed: there was a bad response from the server**"

Appreciate your support
