### ISSUE TITLE
Feature(s) Request: Admin Control & History

### ISSUE THREAD

**Issue by ashadanver** [miroslavpejic85/mirotalk#149]
First off, great project! 
Its feature rich and easy to get going.

Was looking for something like  this for a small office LAN (and occasionally WAN), but that would need to have admin control over who can create rooms or re-visit old ones. This is to prevent users from creating too many rooms and eating up the bandwidth and data quota from the ISP. 

Similarly, would love to have a record of the meeting for attendance taking, and stats.

Thanks

**Comment by miroslavpejic85** [comment]
Hello @ashadanver,

> First off, great project!
> Its feature rich and easy to get going.

Thank you, i'm glad you liek it!

> Was looking for something like this for a small office LAN (and occasionally WAN), but that would need to have admin control over who can create rooms or re-visit old ones. This is to prevent users from creating too many rooms and eating up the bandwidth and data quota from the ISP.

[MiroTalk WEB](https://github.com/miroslavpejic85/mirotalkwebrtc) it's created for that porpuses.

You can always enable the host protection on MiroTalk P2P in the .env file to not allow unauthorised access.
More about the logic is explained [here](https://github.com/miroslavpejic85/mirotalk/commit/285c92605585bf204996dc0bade9b3e7c62d75df#commitcomment-103108955)

> Similarly, would love to have a record of the meeting for attendance taking, and stats.

This could be done in MiroTalk WEB not here, as MiroTalk P2P is made only for video conferences that you can embeed in any website or app with few lines of code.

Please join with us on [Discord](https://discord.gg/rgGYfeYW3N) , there is a channel -> `ideas and suggestions`, where we can talk about the topic.

Thank you.

**Comment by ashadanver** [comment]
Thanks.
Ill check it out
