### ISSUE TITLE
Link view output

### ISSUE THREAD

**Issue by aloproducao** [miroslavpejic85/mirotalk#15]
Hello, thanks for the amazing software

it would be interesting to have an output url for each suitable video so that you could use this project called vingester to convert to NDI, https://github.com/rse/vingester/
.
Individual video outputs will help with video integration with youtube for example, this output should not have camera and audio calls to avoid permission issues.

**Comment by Jaideep25** [comment]
@aloproducao  can you speak english?

**Comment by miroslavpejic85** [comment]
For the moment I close this task but I have marked it for the future, at the moment there are `other priorities`.
Remember this too: https://github.com/miroslavpejic85/mirotalk/issues/4
