### ISSUE TITLE
Join room without audio and/or video connection

### ISSUE THREAD

**Issue by kainy** [miroslavpejic85/mirotalk#150]
### Feature request

Some time we want just send text or file, instead of comunicate via video or audio, asking for device  permission on joining a room （maybe they were just comming in via a link clicking） , will persuade some people , especially conditions when the network not good 

### Pros

Ask for device permission when members click video button, maybe more comfortable for people who are first use microtalk；
And maybe bootup faster without video and audio device connection?

### Additional context

Mybe make it a configurable option 😄

**Comment by vRobM** [comment]
agreed, right now it refuses to let a browser join if there is no audio/video when it is a view only client.

**Comment by miroslavpejic85** [comment]
> Agreed @kainy, right now it refuses to let a browser join if there is no audio/video

Without the video, you should be able to join, but not without the audio at the moment.
