### ISSUE TITLE
Stopping screen share automatically enables webcam

### ISSUE THREAD

**Issue by l4rm4nd** [miroslavpejic85/mirotalk#151]
### Describe the bug

If a user joins a MiroTalk web meeting, he is free to enable or disable the webcam.

Let's assume someone specifically disables the webcam.

If the user now starts a screen share, the screen will be shared to other participants as intended. However, as soon as the screen sharing process is terminated, the user's webcam defaults to be enabled. This is a privacy issue, as the webcam was previously disabled.

### To Reproduce

1. Join a web meeting
2. Disable video/webcam
3. Start screen sharing
4. Terminate screen sharing

You'll notice that the webcam was automatically enabled after terminating the screen share.

### Expected behavior

Terminating a screen share should not default to enable the user's webcam. Instead, the user's choice must be respected. So if the webcam was disabled beforehand, it should stay disabled after a screen sharing session. Maybe default to the video state "disabled" per default. Users can just enable the webcam anyway.

**Comment by miroslavpejic85** [comment]
Hi @l4rm4nd, I should have fixed it, can you check please. Thank you!

**Comment by l4rm4nd** [comment]
Properly fixed. Can confirm that the video is disabled after terminating a screen share.

Thanks!
