### ISSUE TITLE
Original sound quality (add a sound profile combo?)

### ISSUE THREAD

**Issue by dmitryos** [miroslavpejic85/mirotalk#153]
### Feature request

Would it be possible to add a _sound profile_(? combo) on join to select normal (current) sound processing (with echo cancelling, etc) and let's say no processing at all or even add 4800kHz freq and stereo as an option?

### Pros

Use this for music lesson

### Additional context

Great job! All the best,
Dmitry

**Comment by miroslavpejic85** [comment]
Hello @dmitryos

> Great job! All the best

Thank you for the feedback! :)

> Would it be possible to add a sound profile(? combo) on join to select normal (current) sound processing (with echo cancelling, etc) and let's say no processing at all or even add 4800kHz freq and stereo as an option?

If I understand correctly, you can do this, by making the `audio constraints` configurable for your needs. [Check out this](https://blog.addpipe.com/audio-constraints-getusermedia/) and the method in `client.js` -> [getAudioConstraints()](https://github.com/miroslavpejic85/mirotalk/blob/master/public/js/client.js#L3788) 

Please, if you have pleasure, join with us on [Discord](https://discord.gg/rgGYfeYW3N) on channel `ideas-and-suggestions`, where we can also talking about all together! 

Thank you and have a good day!

**Comment by miroslavpejic85** [comment]
Available on discord if you need more information. Thank you.
