### ISSUE TITLE
Almost over 9000

### ISSUE THREAD

**Issue by cesarkohl** [miroslavpejic85/mirotalk#154]
Hey Miro,

I stumbled upon Mirotalk today and I am flabbergasted by the client.js file. I looked at all files in the repo and came to the conclusion that this piece of code has a lot of quality in it.

Honestly, could you explain why is this project mostly functional? Why haven't you used OOP? And why not have multiple files to explode this gigantic and amazing client.js file?

Maybe the answer is related to your past experiences which I'd love to know more about.

Sincerely,
Cesar

**Comment by miroslavpejic85** [comment]
Hello @cesarkohl 

> I stumbled upon Mirotalk today and I am flabbergasted by the client.js file. I looked at all files in the repo and came to the conclusion that this piece of code has a lot of quality in it.

Thank you so much, I appreciate your feedback!

> Honestly, could you explain why is this project mostly functional? Why haven't you used OOP? And why not have multiple files to explode this gigantic and amazing client.js file?

I totally agree with you, initially the project was small, now it has grown a lot and a nice refactoring should be done, to exploding the client.js into smaller units (OOP), making everything more readable and easier to maintain. It was started during the pandemic period, when I didn't know anything about nodejs or WebRTC :) I often used google-meet for video conferencing working from home, and I wanted to create my own alternative without depending on anyone else. Thus, MiroTalk P2P was born, which has a WebRTC mesh structure that is easier to build for anyone starting out with this technology, followed by [MiroTalk SFU](https://github.com/miroslavpejic85/mirotalksfu), [MiroTalk C2C](https://github.com/miroslavpejic85/mirotalkc2c), and [MiroTalk WEB](https://github.com/miroslavpejic85/mirotalkwebrtc).

For any questions, concerns or suggestions, you can join us on [Dscord](https://discord.gg/rgGYfeYW3N) or you can email me any time at miroslav.pejic.85@gmail.com.

Thank you again and have a great day.

**Comment by cesarkohl** [comment]
"I wanted to create my own alternative without depending on anyone else." This is the way!

That makes sense! Alright, I'll join the Discord server, thanks for the invite!
