### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by Micraow** [miroslavpejic85/mirotalk#155]
## Discord chat

Join with us on Discord and ask questions, create discussion, leave feedback.

- https://discord.gg/rgGYfeYW3N

I encountered a problem: I set the turn server to my own in the configuration file, but after NPM started, it did not work. It continued to use the default server, but it was not accessible.

**Comment by miroslavpejic85** [comment]
Hello @Micraow,

Make sure to copied the env.template in `.env` and the edited the `.env` file?
Yes pelase, for questions like this, use the [forum](https://discord.gg/rgGYfeYW3N), instead to open issue here.
Thank you!
