### ISSUE TITLE
No Host in meeting!

### ISSUE THREAD

**Issue by professionalNoob123** [miroslavpejic85/mirotalk#156]
Hey @miroslavpejic85 ! 
### Describe the bug

The bug is --> when there are more than 2 peers and then the host leaves, there is no host in the meeting. Thus, no one is able to lock/unlock the room (and other things only host can do).

### To Reproduce

1. Create a new meeting (ex. Room: 1234)
2. Make 2+ peers join (ex. Room: 1234, connected peers: 4 [including host])
3. Make the host disconnect (person who created the meeting [step 1])
4. No one is the host, no one can lock/unlock room and other host only functions (like eject all)

### Expected behavior

Expected someone else to become the host when the first person leaves.

### Desktop - Mobile

Please complete the following information:

 - Device or OS: iOS, Android, Mac, Windows
 - Browser: Safari, Chrome, Opera

**Comment by miroslavpejic85** [comment]
Hello @professionalNoob123,
> Expected someone else to become the host when the first person leaves.

The last one that remain in the meeting, become the host.

**Comment by professionalNoob123** [comment]
> PS: I don't think giving the roles of host to a random one is the best thing, also because when I leave the room I don't have to worry about it who should I give permission to eject the others and so on. I don't see it as a bug, and I'd rather keep this current logic, what do you think?

Yes, you shouldn't give the role of host to a random one. Though, let's say I'm in a meeting (as host) and connected to 3 other peers, and the room is unlocked (default). Then I disconnect due to internet issues... thus there is no host and the room is unlocked. Which could lead to someone else joins the meeting (ex. peer name: Joe) which may be a security issue because nobody can control him (Joe).

**Comment by miroslavpejic85** [comment]
> Yes, you shouldn't give the role of host to a random one. Though, let's say I'm in a meeting (as host) and connected to 3 other peers, and the room is unlocked (default). Then I disconnect due to internet issues... thus there is no host and the room is unlocked. Which could lead to someone else joins the meeting (ex. peer name: Joe) which may be a security issue because nobody can control him (Joe).

A ok, got it, I will think about how to solve this behavior. Thank you!

**Comment by miroslavpejic85** [comment]
Hello @professionalNoob123,

It should be fixed now.

Test:

1. Join room with 4 different peers, username (User-1, User-2, User-3, User-4)
2. The User-1 is the presenter
3. Exit room with User-1
4. Join again with User-1 and you can see its again presenter.

> **Note** The presenter (host) is identified by:

- `peer_ip` (Public IPv4)
- `peer_name` (Your name on join room)
- `peer_uuid` (UUID4 autogenerated and stored on browser localStorage)

**Comment by professionalNoob123** [comment]
Great! Everything works good. 

Though I have a doubt... VPN's. If a user has a VPN enabled from a service like NordVPN, the IP address can get changed on every refresh of the page. Moreover there are browsers with this same functionality `as default` too (like Opera).

Thus, I don't think User-1 will be the presenter (host) in that case.
