### ISSUE TITLE
What is a reason for querying extreme-ip-lookup.com on client side? + (is api.ipify.org required too?) 

### ISSUE THREAD

**Issue by phpony** [miroslavpejic85/mirotalk#159]
Hello!

Found out that client.js is making the request to https://extreme-ip-lookup.com/json/ when you join the room:

There's the config option:
https://github.com/miroslavpejic85/mirotalk/blob/b7cd692cd18cff969539b3edbf0f66cd60e21351/public/js/client.js#L28-L29

There's the function using it:
https://github.com/miroslavpejic85/mirotalk/blob/b7cd692cd18cff969539b3edbf0f66cd60e21351/public/js/client.js#L765-L777

Here we pass peerGeo obtained from 3rd-party to sever in connection payload:
https://github.com/miroslavpejic85/mirotalk/blob/b7cd692cd18cff969539b3edbf0f66cd60e21351/public/js/client.js#L1442-L1444

Here we completely ignore it:
https://github.com/miroslavpejic85/mirotalk/blob/f2d70ee75da786e809f7b73b86eda62fec271e3c/app/src/server.js#L650-L670

By default if you do not provide any API key extreme-ip-lookup.com is returning dummy data. My uBlock is blocking this host and this doesn't break anything. Also because it's not used anywhere on server side, I've removed this peerGeo from payload completely on my local instance without any problems. The IP is still provided by api.ipify.org from myWanIP variable.

Seems like querying extreme-ip-lookup.com is either some old obsolete code or something planned for future versions? And even if it will be used in future - I don't think the sever in any form should trust any peerGeo data requested from 3rd-party on client side, because it can easily be forged. It would be better to rely on geoip-lite on server side then.

So, for now it looks like we're slowing down the initial connect by waiting for 3rd-party request to extreme-ip-lookup.com for.. nothing?..

P.S. Maybe it would be better to get rid of api.ipify.org too and to just rely on remote ip on server side...

**Comment by miroslavpejic85** [comment]
Hey @phpony!

Thanks a lot, I agree with you, removed all `unnecessary/unused code`.

**Comment by miroslavpejic85** [comment]
@phpony Now I remember why I used extreme-ip-lookup on the client side :) It was a simple hack to not pay for the API key, as with the key=demo2 using it on the client side, you always get the info, while if you use that key on the server side, no.
Try this one: https://extreme-ip-lookup.com/json/?key=demo2 
Since I've been asking about that feature in the MiroTalk forum, I was thinking of bringing it back... or using geoid-lite on server side, but got less info compared to extreme.

**Comment by miroslavpejic85** [comment]
Found the alternative: https://www.geojs.io/docs/v1/endpoints/geo/ this works on server side as well.

**Comment by miroslavpejic85** [comment]
Make it as optional if someone need (default `false`)
```ini
# IP lookup
# Using GeoJS to get more info about peer by IP
# Doc: https://www.geojs.io/docs/v1/endpoints/geo/

IP_LOOKUP_ENABLED=false # true or false
```
