### ISSUE TITLE
Unable to Grant Camera or Microphone Access in the App; Loading Error

### ISSUE THREAD

**Issue by AnuragNishad12** [miroslavpejic85/mirotalk#160]
Description:
When attempting to use the app, there is an issue preventing the user from granting camera or microphone access. Instead of providing the necessary permissions, the app remains stuck in a loading state, impeding its functionality. This problem hinders users from utilizing features that rely on camera or microphone functionality, severely impacting their ability to engage fully with the app's intended purpose.

Steps to Reproduce:

Launch the app on the device.
Reach a point where camera or microphone access is required.
Observe that the app prompts the user to grant access.
Proceed to grant access.
Notice that the app does not proceed past the loading screen or remains stuck in a perpetual loading state.
Confirm that camera or microphone access has not been granted successfully.
Expected Behavior:
Upon granting camera or microphone access in the app, the loading screen should progress smoothly, allowing users to utilize the respective functionalities associated with the camera or microphone. The app should then display the intended features or content without any further delays or errors.

Actual Behavior:
Instead of progressing after granting the necessary permissions, the app fails to advance past the loading screen. The loading state persists, preventing users from using the camera or microphone features within the app. This loading issue persists until the app is closed or the device is restarted.

Impact:
The inability to grant camera or microphone access and the subsequent loading error greatly impairs the app's functionality. Users are unable to perform actions that require camera or microphone usage, such as capturing photos or videos, recording audio, or engaging in video calls. The lack of these essential features severely limits the overall user experience and undermines the usefulness of the app.

<img width="629" alt="Screenshot 2023-05-15 134335" src="https://github.com/miroslavpejic85/mirotalk/assets/124987038/a00782b9-6585-46ac-a33f-af6a4f7c3fd9">

**Comment by miroslavpejic85** [comment]
Hello @AnuragNishad12,

I'm not able to reproduce it, tested on Safari, Chrome, Firefox, Edge, Brave, Opera ...

Can you please: 
1. Specify the OS 
2. Specify the Browser used (make sure is updated to latest version)
3. Paste here, if there are related errors in the browser console logs?

>**Note** Make sure you've really given the app permission to use Microphone and Camera.

<img width="895" alt="allow-camera-mic" src="https://github.com/miroslavpejic85/mirotalk/assets/70838434/68cb27a2-06aa-43a1-8ee1-268c5b381ebc">


Join with us on official [forum](https://discord.gg/rgGYfeYW3N) where we can talking all together, here you can also found many answers, and interact with the community too, before to open issues here.

Thank you!

**Comment by AnuragNishad12** [comment]
1.Specify the OS
Windows

2.Specify the Browser used (make sure is updated to latest version)
Chrome Brower


Paste here, if there are related errors in the browser console logs?
<img width="601" alt="image" src="https://github.com/miroslavpejic85/mirotalk/assets/124987038/57964a38-5040-41d7-bca1-1069e8438747">

**Comment by miroslavpejic85** [comment]
As i can see the client is trying to connect to 127.0.0.1 (change to `localhost`), and `io` is not defined (I assume you are modifying the source code). Please, not open issues here if is not releated to the [official live demo](https://p2p.mirotalk.com), and use the forum instead. Thank you for understanding.
