### ISSUE TITLE
Deploying to railway

### ISSUE THREAD

**Issue by dimityrivanov** [miroslavpejic85/mirotalk#162]
Is anyone having experience on deplying this repo with the docker file on railway succesfully I can see there is a demo on the read me but for some reason everything is working except video and audio.

https://mirotalk.up.railway.app/ -> Is there any guide what I need to do because my assumption was that if there is an docker is all I have to run. Maybe the default google turn server is not ok...

**Comment by miroslavpejic85** [comment]
Hello @dimityrivanov,

Please, for questions, use the [discord-forum](https://discord.gg/rgGYfeYW3N), here you can also founds many answers.

Anyway, you can use the [railway-template](https://railway.app?referralCode=mirotalk) 
In the environments made sure to set also the TURN part, you can follow [this doc](https://github.com/miroslavpejic85/mirotalk/blob/master/docs/coturn.md) on how to install your own.

> **Note** A TURN server is used to relay traffic if a direct peer-to-peer connection fails and is required for most WebRTC applications since a direct connection is often not possible between two clients that aren't on the same network. 

You can self-hosting it on your VPS or VDS, following [this doc](https://github.com/miroslavpejic85/mirotalk/blob/master/docs/self-hosting.md) or expose it from your local PC on HTTPS and make reachable from outside following [this doc](https://github.com/miroslavpejic85/mirotalk/blob/master/docs/ngrok.md).

BR. Miroslav
