### ISSUE TITLE
Document Picture-in-Picture

### ISSUE THREAD

**Issue by endaquigley** [miroslavpejic85/mirotalk#163]
### Feature request

Document Picture-in-Picture (with feature detection).

### Pros

At the moment PIP is limited to one video element.

### Additional context

https://developer.chrome.com/docs/web-platform/document-picture-in-picture

**Comment by miroslavpejic85** [comment]
@endaquigley Done: https://www.dropbox.com/s/rkvhla9w0lto7cn/mirotalk-multi-pip.mp4?dl=0

**Comment by endaquigley** [comment]
@miroslavpejic85 - ahh, I was talking about using the Document Picture-in-Picture API (the ability to float multiple videos).

<img width="362" alt="Screenshot 2023-06-14 at 10 02 15" src="https://github.com/miroslavpejic85/mirotalk/assets/753515/870816d3-de51-4a36-80cb-4e061c6eff5e">

Here's another example provided in the article:

![01rnT7Ev3CyWHLykbmWd](https://github.com/miroslavpejic85/mirotalk/assets/753515/513d123e-c998-47a5-9085-8a03646a8fe4)

**Comment by miroslavpejic85** [comment]
Hi @endaquigley, It seems like you've already worked on this, and I'd really appreciate it if you could submit a Pull Request (PR). Thank you so much!

**Comment by endaquigley** [comment]
Hey @miroslavpejic85, no problem - I should have a PR ready with that in the next few days.
