### ISSUE TITLE
Grammatical error

### ISSUE THREAD

**Issue by dillfrescott** [miroslavpejic85/mirotalk#164]
https://github.com/miroslavpejic85/mirotalk/blob/1f72114b8f7bbfc697922079762c768339dff6c2/public/js/client.js#L680

There is a grammatical error in this line. It should read: `Show me when I receive a new message`.

**Comment by miroslavpejic85** [comment]
Hey thank you! Do you want to send a PR for this?

**Comment by dillfrescott** [comment]
Sure! I can in a little bit!

Also there are a few grammar mistakes on the front page, I can try to fix some of those later on if I get the chance!

**Comment by miroslavpejic85** [comment]
This would be great! Thank you :)

**Comment by dillfrescott** [comment]
https://github.com/miroslavpejic85/mirotalk/pull/165
