### ISSUE TITLE
Audio very low

### ISSUE THREAD

**Issue by karthi6556** [miroslavpejic85/mirotalk#166]
I am facing audio low (volume very low) while connecting through android (chrome browser) to other devices.Basically android device getting this problem, but it works fine with iphone (IOS).Then android to android audio and video perfect.Please anyone guide me to resolve this issue.

**Comment by miroslavpejic85** [comment]
Please, For questions, discussions, help & support, use the forum https://discord.gg/rgGYfeYW3N

Thank you!
