### ISSUE TITLE
Can you support modifying chatgpt base_ URL, supporting chatgpt for proxy openai

### ISSUE THREAD

**Issue by surfboy2000** [miroslavpejic85/mirotalk#170]
### Feature request

Can you support modifying chatgpt base_ URL, supporting chatgpt for proxy openai

### Pros

Because sometimes, it is not possible to access the chatgpt server

### Additional context

thanks

**Comment by miroslavpejic85** [comment]
Hello @surfboy2000,

In your `.env` add the new variable `CHATGPT_BASE_PATH`.
On default is https://api.openai.com/v1/, change it according to your need.

```ini
# ChatGPT/OpenAI
# 1. Goto https://platform.openai.com/
# 2. Create your account
# 3. Generate your APIKey https://platform.openai.com/account/api-keys

CHATGPT_ENABLED=true
CHATGPT_BASE_PATH=https://api.openai.com/v1/
CHATGTP_APIKEY=YourOpenAiApiKey
CHATGPT_MODEL=text-davinci-003
CHATGPT_MAX_TOKENS=1000
CHATGPT_TEMPERATURE=0
```
I like the Additional context :)
