### ISSUE TITLE
[Bug]: Needs a round borders to image

### ISSUE THREAD

**Issue by Bhuminandan** [miroslavpejic85/mirotalk#174]
Meet the team section has a image of a FULL STACK DEVELOPER that has rectangular shape which disturbs the User  experince of the overall Website
A clear and concise description of what the bug is the full stack developer image needs to have some border radius to make it more UX friendly

### To Reproduce

1. Go to 'https://p2p.mirotalk.com/'
2. Scroll down to 'the meet the team section'
3. See image of the fll stack developer

### Expected behavior
Should have some border to make the ui better

### Screenshots

screenshots to help explain your problem.

![Imag radius](https://github.com/miroslavpejic85/mirotalk/assets/134225833/aa7cae69-65ce-4710-ac69-553e2072f0c3)

### Desktop - Mobile

Please complete the following information:

 - Device or OS: [Windows]
 - Browser [Chrome]

**Comment by miroslavpejic85** [comment]
<img width="479" alt="miro-rounded-img" src="https://github.com/miroslavpejic85/mirotalk/assets/70838434/e112861f-aaa3-4a68-a8b7-a4b2278a7007">

**Comment by Bhuminandan** [comment]
Dear @miroslavpejic85 ,

Thank you so much for your warm and encouraging response! I'm truly honored to have the opportunity to contribute to MiroTalk and be a part of your community.

I'm thrilled to join the forum discussion channel and contribute to the ongoing conversation about UI/UX enhancements for MiroTalk. Your kind words about the potential impact of my insights mean a lot to me, and I'm eager to share my thoughts to help create an even better user experience.

I genuinely appreciate your gratitude for my initial contribution, and I wanted to express that I'm looking forward to contributing more in the future. Being part of a community that values collaboration and innovation is truly inspiring, and I'm excited to learn from other community members as well.

Once again, thank you for this opportunity. I'm excited to actively participate in the discussions and contribute to the growth of MiroTalk. Here's to continued collaboration and making MiroTalk the best it can be!
