### ISSUE TITLE
[FEAT]: Custom Sroll Bar

### ISSUE THREAD

**Issue by Bhuminandan** [miroslavpejic85/mirotalk#175]
### Feature request
Having a custom-styled scrollbar on the landing page would enhance its visual appeal compared to the traditional default scrollbar.

### Pros
Here are some possible advantages of doing :-
- Aesthetic enhancement
- Brand consistency
- Improved user experience
- Highlighting important content
- Responsive design
- Personalization
- Creative expression
- Potential accessibility improvement

### Additional context

Regular Scrollbar :-

![Regular Scrollbar](https://github.com/miroslavpejic85/mirotalk/assets/134225833/785305de-af17-4d8b-a9de-61bd4ee42718)

New Custome Styled :- 

![New Customized Scrollbar](https://github.com/miroslavpejic85/mirotalk/assets/134225833/7bb448e7-5982-4bcf-857f-9ed5730d3529)

**Comment by Bhuminandan** [comment]
@miroslavpejic85 I've already forked this repository and made the necessary additions as discussed. I'm excited about the changes I've made and believe they could be beneficial to the project.

Would it be possible for me to receive permission to create a pull request so that these additions can be reviewed and potentially merged into the main project?

**Comment by miroslavpejic85** [comment]
Hey @Bhuminandan, Yes of course!

I truly appreciate your willingness to contribute and help improve the project. Your efforts are invaluable, and I'm looking forward to receiving your pull requests. Thank you so much for your dedication and support!. Let's work together to make this project even better!
