### ISSUE TITLE
Not able to receive file when someone send a file using Send-File

### ISSUE THREAD

**Issue by mohan43u** [miroslavpejic85/mirotalk#178]
### Describe the bug

There is no way to receive the file when someone send a file using Send-File

### To Reproduce

1. Establish session with two participant
2. First participant send a file using `Send-File` icon in the toolbar specific to second participant
3. First participant gets file sent successfully message
4. Second participant receives first participant is sending a file but there is not way for the second participant to accept the file or the file was not automatically received and stored in second participant's storage.

### Expected behavior

Second participant should be able to receive the file successfully

### Screenshots

![mirotalk-send-file-sending](https://github.com/miroslavpejic85/mirotalk/assets/80481/0a0dce45-49b9-4014-90eb-2b8a32a4e281)
![mirotalk-sendfile-receiving](https://github.com/miroslavpejic85/mirotalk/assets/80481/c9f1f11e-3010-46c9-aee8-050a78b1f428)

### Desktop - Mobile

Please complete the following information:

 - Device or OS: Linux (Receiver), Android (Sender)
 - Browser: Firefox (Receiver), Firefox (Sender)
 - Version: 116.0.2 (Receiver), 116.2.0 (Sender)

**Comment by miroslavpejic85** [comment]
Hello @mohan43u,

Thank you for bringing this to our attention. It appears that there is a bug in Firefox. Even after setting `dc.binaryType` to `arraybuffer`, Firefox continues to treat it as a `Blob`. I will investigate this matter further and try to find a way to work around this issue. Notably, other browsers such as Chrome, Safari, Opera, Edge... do not seem to experience this problem.
