### ISSUE TITLE
Make a new folder 📁 ! I wanna give away dogemeet sources

### ISSUE THREAD

**Issue by anshuman2166AppproDev** [miroslavpejic85/mirotalk#18]
Please make a new folder in repo, I want to give dogemeet sources

**Comment by miroslavpejic85** [comment]
Hey @anshuman2166AppproDev, 
Do you have a repo of `dogemeet` on GitHub?
If Yes just paste the link here and anyone can see that version of `mirotalk` customized by you ;)

**Comment by anshuman2166AppproDev** [comment]
https://github.com/anshuman2166AppproDev/Doge-Meet-Sources/

Sources are here @miroslavpejic85

**Comment by miroslavpejic85** [comment]
Good job, thanks for sharing the source 🙂
