### ISSUE TITLE
Auth Using Clerk plz plz

### ISSUE THREAD

**Issue by dramaticcosmetics** [miroslavpejic85/mirotalk#183]
### Feature request

Please add Clerk Auth it will really help please plz plz.

### Pros

auth will help the app to be more secure.

**Comment by miroslavpejic85** [comment]
I'm not sure what you mean by "Clerk Auth," However MiroTalk has host authentication (disabled by default). 
You can find more information about this in the [following link](https://github.com/miroslavpejic85/mirotalk/commit/285c92605585bf204996dc0bade9b3e7c62d75df#commitcomment-103108955).
For any future requests or discussions, please consider using the [forum](https://discord.gg/rgGYfeYW3N) where we can all engage in a comprehensive conversation. 
Thank you.

**Comment by dramaticcosmetics** [comment]
thank you for the reply, i know that you already added an
authentication but i want an auth that will save the users information like
email and password which they can create by themselves and then login.
thank you please keep me in touch

**Comment by miroslavpejic85** [comment]
## MiroTalk WEB

Check out [MiroTalk WEB](https://github.com/miroslavpejic85/mirotalkwebrtc) (NB: MiroTalk P2P is one of the five distinct MiroTalk projects)

![mirotalk-web](https://github.com/miroslavpejic85/mirotalk/assets/70838434/45dbaa9d-e4c2-4907-9692-fd30813417b6)

MiroTalk WEB is a platform that allows for the management of an unlimited number of users. Each user must register with their email, username, and password, after which they gain access to their personal dashboard. Within the dashboard, users can manage their rooms and schedule meetings using the desired version of MiroTalk on a specified date and time. Invitations to these meetings can be sent via email, shared through the web browser, or sent via SMS.
