### ISSUE TITLE
bug-wrong message with Tippy is displayed when whiteboard is open

### ISSUE THREAD

**Issue by malay5** [miroslavpejic85/mirotalk#184]
### To Reproduce

1. Go to a meeting
2. Click on the whiteboard button
3. Move cursor over whiteboard button
4. See the message, Open the Whiteboard

### Expected behavior

It should be stating, close the whiteboard

### Desktop - Mobile

Please complete the following information:

 - Device or OS: Windows
 - Browser: Chrome

**Comment by malay5** [comment]
Please assign this issue to me under hacktoberfest. I would like to solve the issue

**Comment by miroslavpejic85** [comment]
Hey malay5, sure, thanks for the contribution.
