### ISSUE TITLE
WebSocket connection to 'wss://PUBLIC_DOMAIN/socket.io/?EIO=4&transport=websocket' failed

### ISSUE THREAD

**Issue by ongkyokta** [miroslavpejic85/mirotalk#190]
Hi,

I have issue allow camera or microphone always still loading. with this error :
websocket.js:87 WebSocket connection to 'wss://PUBLIC_DOMAIN/socket.io/?EIO=4&transport=websocket' failed

![image](https://github.com/miroslavpejic85/mirotalk/assets/89344382/54dd584b-6382-4744-a61e-2a0481f64810)

can someane help ?

**Comment by miroslavpejic85** [comment]
Hello, Please for questions, help and support I encourage you to utilize the [forum](https://discord.gg/rgGYfeYW3N). Your cooperation is greatly appreciated. Thank you for your understanding.
