### ISSUE TITLE
Implement Husky for Codebase Improvement

### ISSUE THREAD

**Issue by Tholkappiar** [miroslavpejic85/mirotalk#192]
### Feature request

I propose adding Husky , eslint to enhance the code quality in this repository.

### Pros
Husky ensures code quality by running scripts before Git commits and pushes, and Prettier automates code formatting for consistent style.
### Additional context

**Steps:**
- Install Husky , eslint into project dependencies.
- Set up Husky to run Prettier on pre-commit and pre-push hooks.

_PS_ : **I'm eager to work on this. Please assign this issue to me.**

**Comment by miroslavpejic85** [comment]
Hey Tholkappiar,

Thank you for your attention to the pull request. I'd like to extend an invitation to join our [official forum](https://discord.gg/rgGYfeYW3N), where we host a dedicated channel for sharing `ideas & suggestions`. It's a great space for us to collaborate and discuss various topics.

As of now, we're utilizing [Prettier](https://prettier.io), and we've set up a specific configuration file named `.prettierrc.js`.

Just a quick heads-up, as mentioned in the README, before making commits, we execute the following command:

```bash
npm run lint
```

This command ensures the same formatting without relying on git, streamlining the process.

I hope this clarifies the workflow a bit more!
