### ISSUE TITLE
Add "SURVEY**" and "REDIRECT**" as Query parameters

### ISSUE THREAD

**Issue by sabatale** [miroslavpejic85/mirotalk#196]
### Feature request

Would it be also possible to add the following as query parameters?

```
SURVEY_ENABLED=true # true or false
SURVEY_URL=https://www.questionpro.com/t/AUs7VZq00L
REDIRECT_ENABLED=false # true or false
REDIRECT_URL='https://p2p.mirotalk.com'
```

`?survey=false&survey_url=https://google.com&redirect=false&&redirect_url=https://google.com`

### Pros

Match .env variables with query parameters, similarly to _user_auth_ and so on.

### Additional context

N/A

**Comment by miroslavpejic85** [comment]
Hello @sabatale, we currently prefer to maintain the configurability of these variables within the server environment. If you find the need for such customization in your private project, the development process should be relatively swift. Feel free to reach out to me anytime at miroslav.pejic.85@gmail.com. Thank you and have a great weekend.
