### ISSUE TITLE
/test tests wrong ICE servers

### ISSUE THREAD

**Issue by plague-doctor** [miroslavpejic85/mirotalk#197]
### Describe the bug

Calling `https://talk.mydomain.tld/test` shows:
```
[
    {
        "urls": "stun:stun.l.google.com:19302"
    },
    {
        "urls": "turn:a.relay.metered.ca:443",
        "username": "e8dd65b92c62d3e36cafb807",
        "credential": "uWdWNmkhvyqTEswO"
    }
]
```
even if my own ICE has been defined:
```
2023-12-01 22:12:27.358] [server] settings {
  iceServers: [
    { urls: 'stun:coturn.mydomain.tld:5349' },
    {
      urls: 'turn:coturn.mydomain.tld:5349',
      username: 'user',
      credential: 'password'
    }
  ],
```

### Expected behaviour

Test the ICE servers configured with my instance of mirotalk.

 - Version `mirotalk@1.2.5 start` running in Docker

**Comment by dmitryos** [comment]
One can use a query string parameters to provide testing swrvers. If we test already configured servers in the system then probably we don't want to expose them on the result page if someone opens this pageb

**Comment by plague-doctor** [comment]
Agreed. Those creds/servers should be obfuscated, but still, I would like to check my own configuration.

**Comment by dmitryos** [comment]
https://docs.mirotalk.com/coturn/installation/

Bottom  section has the way to test your swrvers if it helps...

**Comment by plague-doctor** [comment]
Of course there is. It is not a problem that one cannot find the information or the way to verify it by different means. The problem is, that is it very confusing when one tries to verify connection to the ICE servers and suddenly sees completely different configuration... 
I just opened `.../test` and it shows something I have not configured. It took me a while to figure out it was just a fake data.

**Comment by miroslavpejic85** [comment]
Hello @plague-doctor,

For illustrative purposes, the Turn demo server credentials have been directly embedded in the test page, featuring a predefined monthly limit of 50GB. However, as @dmitryos wisely points out, it is strongly discouraged to expose your personal Turn username and password through the MiroTalk P2P URL of your instance at:

https://your-domain.com/test

To test your Turn server without exposing your credentials, you can use the Query URL as specified in the documentation:

https://docs.mirotalk.com/coturn/installation/

```plaintext
# Default listening port

https://p2p.mirotalk.com/test?iceServers=[{"urls":"stun:coturn.mydomain.tld:3478"},{"urls":"turn:coturn.mydomain.tld:3478","username":"your.username","credential":"your.password"}]

# TLS listening port

https://your-domain.com/test?iceServers=[{"urls":"stun:coturn.mydomain.tld:5349"},{"urls":"turn:coturn.mydomain.tld:5349","username":"your.username","credential":"your.password"}]
```

For instance, you can use the following test URL (replace with your own credentials):

https://your-domain.com/test?iceServers=[{"urls":"stun:stun.l.google.com:19302"},{"urls":"turn:a.relay.metered.ca:443","username":"your.username","credential":"your-password"}]

For any future questions or discussions, let's hop over to the forum instead. It's a great space for all of us to chat before diving into things here. Just to clarify, this isn't a bug, but more of a small misunderstanding about using the test page. Thanks a bunch for your understanding! 🙌

Wishing you all a fantastic weekend ahead! 

Cheers,
Miroslav

**Comment by yogo1212** [comment]
the turn credentials might not be leaked to callers of the `/test` endpoint but they sure are leaked to mirotalk..

<img width="1199" height="305" alt="Image" src="https://github.com/user-attachments/assets/13fae668-7990-45f8-8639-25364ecb092a" />
