### ISSUE TITLE
what is google cloud run configuration ?

### ISSUE THREAD

**Issue by muratluwi** [miroslavpejic85/mirotalk#199]
hello, 

Mirotalk SFU can not start google cloud run.

camera and microphone not loaded

seems : 
<img width="826" alt="Ekran Resmi 2023-12-09 13 32 58" src="https://github.com/miroslavpejic85/mirotalk/assets/152687143/79ef25d9-14a0-4f39-819c-cd2cdfc8e43f">

**Comment by miroslavpejic85** [comment]
Hello @muratluwi,

1. The screenshot provided pertains to the [MiroTalk SFU](https://github.com/miroslavpejic85/mirotalksfu) project not this one!

2. For any inquiries and support, please utilize the MiroTalk [community forum](https://discord.gg/rgGYfeYW3N).

Your understanding and cooperation are greatly appreciated.
Thank you!
