### ISSUE TITLE
Way of receiving message

### ISSUE THREAD

**Issue by filipenevs** [miroslavpejic85/mirotalk#2]
**Congratulations on the project, it is incredible...**

But I think that when the message is received it shouldn't come as an input, if the person is going to reply, they need to delete the received message and then write again. **I think it ruins the UX.**

> Sorry for the english. I used Google Translator

**Comment by miroslavpejic85** [comment]
Hi filipenevs!
Nice to meet you and thank you so much!
I know and You right, will be fixed, the project is not finished.
Your english is perfect translated :)

**Comment by miroslavpejic85** [comment]
Solved, next step I plan to create a chat-box, to keep track of messages on the UX side.
