### ISSUE TITLE
Cannot head audio from other person

### ISSUE THREAD

**Issue by roberto-sartori-gl** [miroslavpejic85/mirotalk#201]
## Describe the bug

With a self-hosted instance, I cannot head the voice of the other person.
The other person cannot hear me.

In the settings, the microphone seems to be working as when I talk the 'audio bar' moves, but no voice is heard on the other side of the call.

## To reproduce

Initiate a call and no audio is heard.

## Expected behavior

Audio should be heard :)

## Desktop - Mobile

Please complete the following information:

 - Device or OS: Fedora/Ubuntu
 - Browser: Chrome
 - Version: 117

## Additional context

I'm self hosting using docker.
I did a 'docker pull mirotalk/p2p:latest' today (December 13 2023) and the issue remains.

People can join the meeting from inside or outside my network, but no audio can be heard.

**Comment by miroslavpejic85** [comment]
Hello @roberto-sartori-gl, 
Did you encounter the same behavior in our [official live demo](https://p2p.mirotalk.com)?

**Comment by miroslavpejic85** [comment]
Good, it appears there might be a slight hiccup in your installation process. 
Fret not! Our comprehensive MiroTalk documentation has you covered with a detailed self-hosting guide. 
Navigate to [this link](https://docs.mirotalk.com/mirotalk-p2p/self-hosting/) for a meticulous step-by-step walkthrough.

For assistance and vibrant discussions around MiroTalk projects, our dedicated forum awaits your presence. 
Join the conversation [here](https://discord.gg/rgGYfeYW3N) to connect with our community and receive support.

We greatly appreciate your collaborative spirit. 

Thank you for the feedback! 🚀
