### ISSUE TITLE
FR: Support screensharing on iOS (and Android)

### ISSUE THREAD

**Issue by AG-Studio-600** [miroslavpejic85/mirotalk#205]
# Feature request

I was experimenting with MiroTalk on my iPad, and I realised I couldn't screenshare on there.

## Steps I've Taken

I tried to request a desktop site. No luck there. I also unjoined and rejoined many meeting rooms (because I thought that it was a bug of one room), however none of them supported screensharing. So I assume it's a missing feature on iOS (and probably Android) devices.

## Pros

This'll help if you want to quickly share something on a mobile device rather than going on desktop, joining the meeting, and sharing the screen. It also adds some extra convenience.

## Additional context

This was tested on the Orion browser on my iPad.

**Comment by miroslavpejic85** [comment]
Certainly! Here's a refined version of your message:
The `getDisplayMedia` API is currently not supported on mobile devices. For detailed information on browser compatibility, please refer to [this page](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getDisplayMedia#browser_compatibility).

Before opening an issue here, we recommend checking the [community forum](https://discord.gg/rgGYfeYW3N) where you may find answers and discussions related to your query. Your collaboration and engagement in the forum are appreciated.

Thank you for your understanding and cooperation.
