### ISSUE TITLE
`OpenAI is not defined` error when using ChatGPT

### ISSUE THREAD

**Issue by TheBlueSky** [miroslavpejic85/mirotalk#206]
# Bug Report

`IMPORTANT`: We primarily use GitHub as an issue tracker. Just open an issue here if you have encountered a bug in MiroTalk.
If you have `ideas, suggestions, questions, doubts` about MiroTalk or `need support`, please use the MiroTalk Forum instead:

👉 [https://discord.gg/rgGYfeYW3N](https://discord.gg/rgGYfeYW3N)

## Describe the bug

I am installed MiroTalk using the latest Docker image, `mirotalk/p2p:latest`, and configure the ChatGPT section with my API Key, while leaving the rest of the settings as is:
```
CHATGPT_ENABLED=true
CHATGPT_BASE_PATH=https://api.openai.com/v1/
CHATGTP_APIKEY=MyApiKey
CHATGPT_MODEL=gpt-3.5-turbo-instruct
CHATGPT_MAX_TOKENS=1000
CHATGPT_TEMPERATURE=0
```
When I enable ChatGPT in that chat window and send a message, the server crashes with the following error message:
```
mirotalk  | /src/app/src/server.js:704
mirotalk  |                     if (error instanceof OpenAI.APIError) {
mirotalk  |                                          ^
mirotalk  |
mirotalk  | ReferenceError: OpenAI is not defined
mirotalk  |     at Socket.<anonymous> (/src/app/src/server.js:704:42)
mirotalk  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
By looking at the [source code](https://github.com/miroslavpejic85/mirotalk/blob/2de13390365fd70165b39a933b069307e219ea05/app/src/server.js#L704), it seems that `OpenAI` being `undefined` masks the original error. So, it isn't clear what is actually failing.

## To reproduce

1. Create a Docker Compose file like the one below these steps
2. Download `.env.template` file from [this](https://github.com/miroslavpejic85/mirotalk/blob/2de13390365fd70165b39a933b069307e219ea05/.env.template) repo into the same directory as the Docker Compose file, and rename it to `.env`
3. Update ChatGPT section in the `.env` file as shown in the bug description section above (you may also need to update other configurations, such as host)
4. Run the container with `docker compose up -d && docker compose logs -f`, so that you see the logs
5. Navigate to the application, enter a room, open the chat window, enable ChatGPT, and post a message
6. See error in the logs

```yaml
services:
  mirotalk:
    image: mirotalk/p2p:latest
    container_name: mirotalk
    hostname: mirotalk-docker
    volumes:
        - ./.env:/src/.env:ro
    ports:
      - 3000:3000/tcp
    privileged: false
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
```

## Expected behavior

* If there is an error in the configuration or an error from OpenAI, I expect to see it in the logs
* `OpenAI` for some reason is undefined, while it should be at this point based on the fact that it is enabled and has the needed configuration. The code [here](https://github.com/miroslavpejic85/mirotalk/blob/2de13390365fd70165b39a933b069307e219ea05/app/src/server.js#L200) should have taken care of this.
* The expected behaviour is that I do not get an error and get ChatGPT response instead :)

## Screenshots

![image](https://github.com/miroslavpejic85/mirotalk/assets/807685/ad9a7731-a4c3-4ffd-baf5-e508c1186d01)

## Desktop - Mobile

Please complete the following information:

 - Device or OS: Windows
 - Browser: Brave (1.61.120) and Vivaldi (6.5.3206.55)
 - App Version: 1.2.75

## Additional context

-

**Comment by miroslavpejic85** [comment]
Hello @TheBlueSky,
Thank you for the update. I've made a small adjustment. 
Please check your server console for any potential errors that can help you to identifying the issue.

**Comment by TheBlueSky** [comment]
Thanks for the quick resposne, @miroslavpejic85.
Now I can see the real error behind it, which is 429 `insufficient_quota` 😬
