### ISSUE TITLE
Deploying in heroku

### ISSUE THREAD

**Issue by kevzs311** [miroslavpejic85/mirotalk#21]
hello, i have a bit trouble when deploying it in heroku, how can i deploy it? do i need to 
const myPeer = new Peer(undefined, {
  host: '/',
  port: '443'
})

**Comment by Jaideep25** [comment]
Hey welcome @kevzs311, could you please tell how are you deploying using CLI, or using GITHUB?

Actually am just giving a suggestion, you can use railway.app, it's much faster, and better than heroku!

**Comment by kevzs311** [comment]
> Hey welcome @kevzs311, could you please tell how are you deploying using CLI, or using GITHUB?
> 
> Actually am just giving a suggestion, you can use railway.app, it's much faster, and better than heroku!

i use CLI to deploy it... wait let me try the railway.app thanks!
btw. do i need to configure some codes to deploy in railway?

**Comment by Jaideep25** [comment]
@kevzs311  actually, for railway the easiest way is to 1st put on github, then open railway and connect with github, then in variables section put a variable named as PORT, put it's value as 300, after that you're done! open the deploy link they gave!

**Comment by Jaideep25** [comment]
@kevzs311  if you want to deploy to heroku using cli, I'll show you how to do it... 

- **`heroku login`**
- **`heroku git:clone -a "HERE TYPE THE APP NAME YOU GAVE"`**
- **`cd "THE APP NAME"`**
- **`git add -A`**
- **`git commit -a "make it better"`**
- **`git push heroku master`**

And at last it'll deploy your changes!!

**Comment by miroslavpejic85** [comment]
Hi @kevzs311! Thank for using mirotalk and welcome!
If you use Heroku, remember to go in to your app `settings on heroku` and also add `Reveal Config Vars`:
```
HEROKU_ENVIRONMENT = prod
NGROK_ENABLED = false
NGROK_AUTH_TOKEN = YourNgrokAuthToken
TURN_ENABLED = true
TURN_USERNAME = YourTurnUsername
TURN_PASSWORD = YourTurnPassword
TURN_URLS = YourTurnUrls
```
The `Turn credential` you can take it following this part:
https://github.com/miroslavpejic85/mirotalk#setup-turn-and-ngrok
In case you not want to use Turn, just change this part
```
TURN_ENABLED = false
```
Regards

**Comment by kevzs311** [comment]
Thank you @Jaideep25 @miroslavpejic85 
i already deployed it in railway.. as you said its faster deploying in railway

**Comment by Jaideep25** [comment]
Oh great! So we can close this issue now?

**Comment by miroslavpejic85** [comment]
U welcome! 🙂

**Comment by kevzs311** [comment]
> Oh great! So we can close this issue now?

Yes!.. Than you again.

**Comment by Jaideep25** [comment]
No worries 😉

**Comment by Jaideep25** [comment]
@miroslavpejic85  I can't close, so could you...
