### ISSUE TITLE
UI Design Revamp

### ISSUE THREAD

**Issue by Sanyam1427** [miroslavpejic85/mirotalk#210]
# Feature request

Hey I use mirotalk a lot and also used it some times for buisness meets but the thing which I want in mirotalk is a UI Revamp like you can see current design is little off and is nothing compared to other video conferencing platform like brave talk , Zoom , Google meet I would like mirotalk to improve its UI and designs particularly modern design 

## Pros
A neat , modern and user friendly design can help users like me use mirotalk more often 
And I think you will like this idea too

**Comment by miroslavpejic85** [comment]
Hello @Sanyam1427,

I'm agree and we've set up a dedicated thread [here](https://discord.com/channels/838103530979196938/1137259356904226917/1137657131970088970) for our forum community. Before opening an issue here, we encourage to join us on [MiroTalk forum](https://discord.gg/rgGYfeYW3N) and explore existing discussions on questions, improvements, help, and support. 🙏

We value your input and are open to discussing any suggestions or improvements you'd like to see in our current UI. At MiroTalk, we're committed to creating a design that stands out from the rest and being intuitive and user-friendly. One of our latest implementation is the custom theme, which allows you to customize your theme with your preferred colors, learn more [here](https://discord.com/channels/838103530979196938/1113705414190706749/1205113901193367562).🎨

Calling all `UI/UX aficionados!` 💫  We warmly welcome your contributions and PRs to help propel MiroTalk to new heights! Let's collaborate to take our user experience to the next level! 💡 Your insights and expertise are invaluable in shaping the future of MiroTalk. Join us on this exciting journey! 🚀

Thank you for your cooperation and contribution to our community! ❤️
