### ISSUE TITLE
Praises and thanks

### ISSUE THREAD

**Issue by AtmanActive** [miroslavpejic85/mirotalk#215]
Hi,

Please allow me to congratulate you on this tremendous achievement. From the days of Skype, Viber, Telegram, Mumble, Zoom, Duo,  JitsiMeet, Slack and all other audio/video call tools, p2p.MiroTalk has definitely become my #1 go to tool for all online communication needs. It simply combines the best of all traits: lowest latency (on par with Mumble), top-notch noise and echo cancellation (the best ever), crystal-clear video (setting new heights here), and direct and open approach.

For me personally, the peer-to-peer architecture makes it super stable, super reliable and super efficient. Obviously that was the missing ingredient and I wholeheartedly thank you for implementing it and for putting the whole thing together so nicely and so elegantly.

With today's proliferation of chromium based browsers it is easy to whip up a dedicated communication tool with a preset room selection for elderly and other zero-click no-confusion use cases. Fantastic!

I feel like p2p.mirotalk brought in a new era in internet real-time communications to my life.

Kudos, you rock!

Thank you.

Cheers!

AtmanActive

**Comment by miroslavpejic85** [comment]
Hey @AtmanActive,

Thank you so much for your enthusiastic feedback! It's truly heartening to hear that p2p.MiroTalk has become your preferred choice for online communication. We're thrilled that you appreciate the combination of low latency, exceptional noise and echo cancellation, high-quality video, and the simplicity of the peer-to-peer architecture.

We've worked hard to create a communication tool that meets the needs of users like yourself, and we're delighted that you find it stable, reliable, and efficient. The peer-to-peer architecture indeed offers many advantages, and we're glad to hear that it has enhanced your experience.

We kindly invite you to join our community forum [here](https://discord.gg/rgGYfeYW3N), where you can share feedback! It's a good place where you can find many answers and interact with others as well.

Thank you once again for your kind words and for choosing p2p.MiroTalk. We're honored to have you as a satisfied user, and we're committed to providing you with the best possible communication experience.

Best regards,

Miroslav
MiroTalk Team
