### ISSUE TITLE
UI inconsistency: mute audio/video

### ISSUE THREAD

**Issue by AtmanActive** [miroslavpejic85/mirotalk#216]
# Bug Report

## Describe the bug

In-call top row buttons can't decide if they want to be buttons or indicators.

## To reproduce

1. Get on a call
2. Decide you want to turn your video off
3. Notice the little white camera icon in the top right corner of your video screen
4. Click the icon
5. Nothing happens

## Expected behavior

Either these icons CAN mute/unmute camera/microphone, or, mouse pointer DOESN'T show clickable and then they CAN'T.
Right now it is confusing: the mouse pointer shows clickable (finger instead of an arrow), but when we click nothing happens.

## Desktop - Mobile

Please complete the following information:

 - Device or OS: Windows
 - Browser Chrome
 - Version any

## Additional context

I had this situation with my friend the other day. I just invited him to join me on my p2p.mirotalk call for the first time and he was delighted with quality and ease of use. A few minutes later he starts complaining that the UI is broken. I ask him what's the matter and he explained that he is trying to turn his camera off but he can't. After some back and forth we realize that he is clicking on little white icons inside his video feed instead on the main menu icons on the left. The very fact that the user got confused and couldn't figure the UI out shows that there is a bug in the UI as described here.

Thanks.

**Comment by miroslavpejic85** [comment]
> Either these icons CAN mute/unmute camera/microphone, or, mouse pointer DOESN'T show clickable and then they CAN'T. Right now it is confusing: the mouse pointer shows clickable (finger instead of an arrow), but when we click nothing happens.

Done in MiroTalk P2P v1.2.91

![mirotalk-p2p-fix-cursor](https://github.com/miroslavpejic85/mirotalk/assets/70838434/6ca8f1af-ef71-4b0f-b808-9e9f13e99a1e)
