### ISSUE TITLE
Allow us to hold a contextualized conversation with ChatGPT

### ISSUE THREAD

**Issue by hyoretsu** [miroslavpejic85/mirotalk#219]
# Feature request

Right now, all of our prompts are submitted as what seems to be separate conversations, instead of a single conversation per session. Hence, we cannot ask it to, say, refine a previous answer.

**Comment by hyoretsu** [comment]
Judging by these two links, it should be possible with the API:
https://github.com/openai/openai-cookbook/issues/275
https://community.openai.com/t/managing-previous-conversations-with-chatgpt/321402

**Comment by miroslavpejic85** [comment]
1. Update the `CHATGPT_MODEL` environment variable in the `.env`:
   ```bash
   CHATGPT_MODEL=gpt-3.5-turbo
   ```

2. Restart MiroTalk P2P to apply the changes and ensure that the new model configuration takes effect.

**Comment by hyoretsu** [comment]
Proof that it's not working:
![WhatsApp Image 2024-03-11 at 06 19 01_9402391a](https://github.com/miroslavpejic85/mirotalk/assets/20804322/972cffc2-e563-4d41-a0a1-314a0df9f034)
![WhatsApp Image 2024-03-11 at 06 19 10_d2745e9e](https://github.com/miroslavpejic85/mirotalk/assets/20804322/6622ef60-64b7-4295-b4a3-4ace6c6ebc1c)
How it should work:
![image](https://github.com/miroslavpejic85/mirotalk/assets/20804322/b340af18-b3d8-48e4-8892-a5ada58ae0bf)
My `.env` already has CHATGPT_MODEL set to turbo:
![image](https://github.com/miroslavpejic85/mirotalk/assets/20804322/77a77237-cb5f-4cbc-b375-eb9db1d83211)
My docker_compose is exposing that file, albeit the different name:
![image](https://github.com/miroslavpejic85/mirotalk/assets/20804322/8de40b1b-f8ce-4562-81a8-7d7c9ea6fca4)
Proof that this env approach should also work:
![image](https://github.com/miroslavpejic85/mirotalk/assets/20804322/d554c619-6a33-4a2c-962e-5babd8214e46)
Proof that `gpt-3.5-turbo` and `gpt-3.5-turbo-0125` are the same:
![image](https://github.com/miroslavpejic85/mirotalk/assets/20804322/dfecf7d8-0e1a-4075-b235-361ab7aeae42)

**Comment by hyoretsu** [comment]
It seems to be using `gpt-3.5-turbo-instruct`
![image](https://github.com/miroslavpejic85/mirotalk/assets/20804322/0aedfa4c-757a-459d-959a-454e76395705)

I just shut down the container after setting the `.env` to exactly gpt-3.5-turbo, same thing
![image](https://github.com/miroslavpejic85/mirotalk/assets/20804322/4c07f636-e2b6-4d1f-a6e4-3bffe4c5ceed)

**Comment by hyoretsu** [comment]
And it's also not an issue of my `env_file` unusual approach, as disabling CHATGPT in that `.env.mirotalk` works:
![image](https://github.com/miroslavpejic85/mirotalk/assets/20804322/ea77cc55-6997-4934-94fd-6544e6fa23f6)

**Comment by hyoretsu** [comment]
After fixing a typo involving the env variables (in .env.template and app/src/server.js), I'm getting this now:
![image](https://github.com/miroslavpejic85/mirotalk/assets/20804322/c6af9e9c-e812-4a28-b79c-70bcb70ea736)

**Comment by hyoretsu** [comment]
Sorry, I was dumb and didn't notice there was an update in the last 24h.
