### ISSUE TITLE
Fix typo in ChatGPT env variables in `.env.template` and `app/src/server.js`

### ISSUE THREAD

**Issue by hyoretsu** [miroslavpejic85/mirotalk#220]
They have CHATGTP

https://github.com/miroslavpejic85/mirotalk/blob/1c657de2a095c6d6aa151b360636d1be525240de/.env.template#L133
https://github.com/miroslavpejic85/mirotalk/blob/1c657de2a095c6d6aa151b360636d1be525240de/app/src/server.js#L231
https://github.com/miroslavpejic85/mirotalk/blob/1c657de2a095c6d6aa151b360636d1be525240de/app/src/server.js#L232

**Comment by miroslavpejic85** [comment]
Thank you.
