### ISSUE TITLE
Unable to connect to a room in my notebook

### ISSUE THREAD

**Issue by hyoretsu** [miroslavpejic85/mirotalk#221]
It works just fine on my desktop and mobile, but for some reason not on my Notebook.
![image](https://github.com/miroslavpejic85/mirotalk/assets/20804322/12140d85-ef0f-4e16-bac4-c863847d1fff)

**Comment by miroslavpejic85** [comment]
For assistance and support, we encourage you to utilize our forum's dedicated help & support channel. You can join us [here](https://discord.gg/rgGYfeYW3N). Thank you.
