### ISSUE TITLE
Scalability Issue

### ISSUE THREAD

**Issue by JatSh1804** [miroslavpejic85/mirotalk#223]
As I have read through the project I don't see any configuration for interconnecting user in a single room connected across multiple server instances, which means its not scalable if users are connected to different server instances they won't be able to connect to same room. 
Can someone explain it, or am i taking it wrong??
Also, There has to be some turn server configuration for SFU connectivity.

**Comment by miroslavpejic85** [comment]
Thank you for reaching out. We're glad to clarify any confusion you may have regarding the architectures used in various MiroTalk projects. While there are no specific limitations on the number of rooms or times, we highly recommend familiarizing yourself with the architectures employed, which you can find detailed information about [here](https://docs.mirotalk.com/webrtc/architectures/).

For a deeper understanding of the WebRTC SFU-based architecture, we suggest taking a look at [MiroTalk SFU](https://github.com/miroslavpejic85/mirotalksfu). Should you have any further inquiries or uncertainties, please feel free to utilize the designated **discord** forum mentioned in the README file. 

![image](https://github.com/miroslavpejic85/mirotalk/assets/70838434/2025cb6e-3820-4dad-84b7-392f26e6b082)

Your engagement is greatly appreciated. Thank you!
