### ISSUE TITLE
Turn server configuration

### ISSUE THREAD

**Issue by marcus2vinicius** [miroslavpejic85/mirotalk#224]
# MiroTalk forum

Regarding the turn server, I saw that you used coturn. Could you provide the configuration script or dockerfile to configure coturn together with mirotalk?

**Comment by miroslavpejic85** [comment]
We kindly request that for any future inquiries, you join our esteemed [Community forum](https://discord.gg/rgGYfeYW3N). It serves as an excellent platform for addressing questions and exchanging insights.

Please refer to the following resources on [Stun-Turn](https://docs.mirotalk.com/coturn/stun-turn/) and [Installation](https://docs.mirotalk.com/coturn/installation/) for comprehensive information.
