### ISSUE TITLE
Can't disable microphone

### ISSUE THREAD

**Issue by Giorgio-Banani** [miroslavpejic85/mirotalk#225]
## Describe the bug

When you start a call you can choose to start it with a muted microphone. When you try that, you will notice that the microphone is still active even thow its shown as RED and DISABLED.

## To reproduce

1. Start a call on a desktop
2. Join the call with another device (mobile phone), but disable the mic before entering the call
3. Hear yourself on the desktop, even thow the mic should be muted on the mobile phone.

## Expected behavior

Muted should be muted.

## Desktop - Mobile

Please complete the following information:

 - Device or OS: Tried with windows and andriod.
 - Browser Brave / Chrome

**Comment by miroslavpejic85** [comment]
@Giorgio-Banani should be fixed now. Thank you.

**Comment by miroslavpejic85** [comment]
@Giorgio-Banani should be fixed now. Thank you.
