### ISSUE TITLE
Screensharing on Mobile devices

### ISSUE THREAD

**Issue by Giorgio-Germani** [miroslavpejic85/mirotalk#226]
# Feature request

Share the screen of a mobile device (andriod and ios)

## Pros

Thats a quite useful and fairly standard feature for a video conversation app

## Additional context

Maybe it needs native apps in order to achieve this functionality. Flutter might be a good way to get it done easily.

**Comment by miroslavpejic85** [comment]
We're committed to maintaining MiroTalk as a [Progressive Web App](https://www.youtube.com/watch?v=Z8MjdQGyjfA) (PWA). Currently, the `WebRTC getDisplayMedia API` is limited to desktop devices, more about [browser compatibility here](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getDisplayMedia#browser_compatibility) but hope there's potential for its future expansion to include mobile platforms. We encourage you to join our [community forum](https://discord.gg/rgGYfeYW3N), where there is a dedicated channel for suggestions. Let's discuss potential improvements together before submitting it here, as GitHub issue tracker is primarily for confirmed `bugs`. Thank you for the collaboration and you are welcome. We look forward to seeing you on our forum!

**Comment by miroslavpejic85** [comment]
When the **[getDisplayMedia API](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getDisplayMedia#browser_compatibility)** becomes supported on mobile devices, we’ll enable screen sharing. For now, no changes are needed to maintain compatibility with our Progressive Web App (PWA) setup.
