### ISSUE TITLE
BUG: peers can enable each other's camera

### ISSUE THREAD

**Issue by AtmanActive** [miroslavpejic85/mirotalk#229]
# Bug Report

## Describe the bug

The function "open picture in picture" defeats camera enabled/disabled state.

If I join the meeting with my camera ON, and I decide to turn it OFF later on, then, if my peers click on "open picture in picture" for me, they do get a video screenshot of my camera. It is a video feed that's not moving. Could be the last known frame. No big deal since they (peers) already saw my camera before, but still, feels awkward. 
But there's more:

If I join the meeting with my camera OFF, then, if my peer(s) click on "open picture in picture" for me, they get full live video feed of my camera without me even knowing about it. Ouch!

Furthermore, my camera's built-in "recording" LED indicator is enabled the minute I open p2p.mirotalk in my browser, regardless of the actual state of the camera feed (if I keep it ON or OFF) which tells me that my camera is always open by p2p.mirotalk, and thus, effectively preventing me from knowing if my camera feed is enabled for real or not. This makes the above problem even worse (I can't tell if my peers are secretly watching my camera even though I wanted it disabled when I joined the call).

## To reproduce

1. Go to p2p.mirotalk.com, any room.
2. Click on the "disable my camera" button before joining.
3. Ask your peer to click on the "open picture in picture" button above your avatar.
4. Hear them telling you they can now see your camera even though you disabled it before joining the call.

## Expected behavior

When I disable my camera, I expect to:
- see the LED light on my camera turn off
- keep it disabled no matter what my peers do
- have zero video bytes leave my computer

## Desktop - Mobile

Please complete the following information:

 - Device or OS: Windows, Android
 - Browser: Thorium, Chrome
 - Version: latest

Thanks.

**Comment by miroslavpejic85** [comment]
Hey @AtmanActive, Thank you for bringing this to our attention! We've fixed it. Your help means a lot!
