### ISSUE TITLE
On premise : opening a meeting, stuck on a wait screen expecting camera and micro setup ... but nothing to do it

### ISSUE THREAD

**Issue by Nomtest** [miroslavpejic85/mirotalk#230]
Hello,

stuck on a Loading screen without nothing to be connected and no way to enable video or microphone. 

With docker home made image or with the one pull from mirotalk/p2p:latest it is the same behaviour.

Help !

**Comment by miroslavpejic85** [comment]
![image](https://github.com/miroslavpejic85/mirotalk/assets/70838434/4055d1a3-2859-44f4-9a37-6a683e27b615)
