### ISSUE TITLE
Unable to run mirotalk on local wifi only (offline)

### ISSUE THREAD

**Issue by cyberdan77** [miroslavpejic85/mirotalk#232]
I have everything running locally using a MacBook and can access mirotalk with the wifi OFF or... with the internet on. However, when I try and access it via wifi only—and disconnected from the internet—it won't load the room. I get "disconnected { reason: 'transport close' }" when I try to load it. Any ideas? I have self-signed local SSLs installed and can run https. I also installed the coturn server which seems to be running fine as well.

**Comment by miroslavpejic85** [comment]
![image](https://github.com/miroslavpejic85/mirotalk/assets/70838434/febf2b46-1a12-49fa-932b-df6c5aed085e)

👉 https://discord.gg/rgGYfeYW3N
