### ISSUE TITLE
Use OpenAI's Whisper for the captioning system

### ISSUE THREAD

**Issue by EntityinArray** [miroslavpejic85/mirotalk#234]
# Feature request

I couldn't figure out what you use for captioning, but it often fails to recognize simple words. \
Is it possible to use OpenAI's Whisper? It's a lightweight, free and open-source speech-to-text AI model. I think it can run serverside on the CPU.

https://github.com/openai/whisper

It's mindblowingly good at recognizing speech, here's a demo.
https://youtu.be/Ph6K_0ttsSc?t=869

## Pros

- Very reliable speech-to-text recognition in the captioner

**Comment by miroslavpejic85** [comment]
> I couldn't figure out what you use for captioning

We use [SpeechRecognition](https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition)

> Is it possible to use OpenAI's Whisper?

Whisper is coded purely in `Python`, while MiroTalk primarily utilizes `JavaScript`.

Please next time use the `ideas and suggestions` channel on our [mirotalk-forum](https://discord.gg/rgGYfeYW3N).

Thank you!
