### ISSUE TITLE
Please allow the camera or microphone access to use this app.

### ISSUE THREAD

**Issue by troyam** [miroslavpejic85/mirotalk#235]
# Bug Report

`IMPORTANT`: We primarily use GitHub as an issue tracker. Just open an issue here if you have encountered a bug in MiroTalk.
If you have `ideas, suggestions, questions, doubts` about MiroTalk or `need support`, please use the MiroTalk Forum instead:

👉 [https://discord.gg/rgGYfeYW3N](https://discord.gg/rgGYfeYW3N)

## Describe the bug

Uploaded the files to VPS and installed but the page stucks on "Please allow the camera or microphone access to use this app."

## To reproduce

1. Go to https://video.7ty.com.br
2. Click on Join Room
3. See error

## Screenshots

![Captura de tela 2024-06-15 163031](https://github.com/miroslavpejic85/mirotalk/assets/28970728/bbb684a9-7971-4046-9e4a-703156e4ef09)

## Additional context

Using CloudFlare, Apache2 to Proxy Reverse

**Comment by troyam** [comment]
Solved!
Using:

sudo a2enmod proxy_wstunnel
sudo a2enmod rewrite

# WebSocket support
    RewriteEngine On
    RewriteCond %{HTTP:Upgrade} =websocket [NC]
    RewriteRule /(.*) ws://localhost:3000/$1 [P,L]

**Comment by troyam** [comment]
Thanks!

**Comment by miroslavpejic85** [comment]
Please mark this topic as solved in the forum as well and Welcome to our community!

Cheers.
