### ISSUE TITLE
Just some ideas

### ISSUE THREAD

**Issue by Chairnatomy** [miroslavpejic85/mirotalk#238]
Hiding presentation. So just the same way if you're presenter, if you close someone's camera, if they have a presentation you can close it for everyone.
On topic of presentations, could you also try and give them sound?
And for a last small one, do you think you could let us make gradient backgrounds that save in settings? I'm mainly saying this one cause me and one of my friends found how to change any color in the code using inspect but it gets annoying changing it every time I rejoin.

**Comment by miroslavpejic85** [comment]
Hello! For sharing ideas and suggestions, please use the dedicated channel in the MiroTalk community forum. Thanks!
