### ISSUE TITLE
Unstablity if I connect with 6 users at the same time 

### ISSUE THREAD

**Issue by mmodi97** [miroslavpejic85/mirotalk#24]
can you please tell how to make a stable connection for more than 6 users. its disconnecting after sometime and remove peer  reconnect with the stun or turn server. Is there any server requirement and other configuration that you can suggest me ?
 Thanks in advance

**Comment by miroslavpejic85** [comment]
Hi @mmodi97 welcome!
Are the 6 connected users from 6 different devices?

**Comment by mmodi97** [comment]
yes

**Comment by miroslavpejic85** [comment]
`Mirotalk` has `no intermediate media server` for audio-video communication, they are `pure peer to peer` connections between browsers, therefore it requires a `good Bandwidth` and `CPU`.
You tested it on: https://mirotalk.herokuapp.com/ ?

**Comment by mmodi97** [comment]
yes i have tested this i also tested on ec2 instance 72V cpu 192gb ram  and 100 gbps bandwidth server but its still unstabling can you suggest me what can be the configuration to make it smooth for more than 6-7 users.

**Comment by miroslavpejic85** [comment]
The Signaling server doesn't require a lot of ram-cpu as it just sends RTCICECandidate & RTCSessionDescription which is needed to establish the video call. I meant that peer aka devices must all have a good Bandwith - CPU. However, in the future I could also see to change the current architecture, because `WebRTC Mesh` is `not` an `excellent solution` for conferences that require a lot of participants...🤔

**Comment by mmodi97** [comment]
Ok understand @miroslavpejic85  Thanks for your support and for your repository. I learnt a lot .I am  trying to solve the issue and I hope you also will try to fix it 😃 ✌

**Comment by Jaideep25** [comment]
Hey @mmodi97  welcome! Actually for @miroslavpejic85  it's working perfectly... and even for me... as you can see in the image below! I tried connecting using local host using 4 differrent browsers and it crashed.... but with different laptops it worked good!
![image](https://user-images.githubusercontent.com/67269475/120586438-2c538c00-c451-11eb-9b0d-c48ed9bb66a2.png)

**Comment by mmodi97** [comment]
@Jaideep25 Hey you are connected with different network or same network when we connect with different network different devices its reconnect again and again so not running 6 at the same time it removes the peer connection and connect again.

**Comment by Jaideep25** [comment]
This is with different connections... This is the pic which @miroslavpejic85  had taken ;)

**Comment by mmodi97** [comment]
ok I am facing this issue in my region I dont know why its happening  may be because of low bandwidth in connectivity . I also have connected with 6 but it remove anyone after sometime not maintain  the stability. Is it working  fine with 6 there or not remove and reconnect anyone?
🙂 @Jaideep25  Thanks

**Comment by miroslavpejic85** [comment]
@mmodi97 Just out of curiosity try mirotalk here too: https://mirotalk.up.railway.app/
tell me if anything changes?

**Comment by Jaideep25** [comment]
> ok I am facing this issue in my region I dont know why its happening may be because of low bandwidth in connectivity . I also have connected with 6 but it remove anyone after sometime not maintain the stability. Is it working fine with 6 there or not remove and reconnect anyone?
> 🙂 @Jaideep25 Thanks

@mmodi97  hey, sorry for replying so late I was down with fever, 
For me at 1st it wasn't working fine if I connected 6 peers in the same laptop, but if I connected with 6 devices it worked good!
Thanks!

**Comment by mmodi97** [comment]
hey @Jaideep25  I hope you are well now  I got your point and I read about peer to peer and mcu/sfu based web rtc .Mirotalk is based on peer to peer if any peer have low bandwidth it will disconnect from the others and other peers will disturb because it devides the bandwidth as per the peers . if 6 peers are connected and each peer takes 1 Mb bandwidth . now other peers have connection of  which have 6mb bandwidth of downloading and uploading of 1mb. but in sfu there internet connection matters but not that much. and load balance can be manage using sfu device. I was looking for sfu based video calling. video conferencing platforms like zoom, google meet uses media servers to manage the load and quality of streams . I appreciate and thankful to @miroslavpejic85.  he tried best for peer to peer. Thanks  @Jaideep25

**Comment by miroslavpejic85** [comment]
A very nice step would be to integrate an `SFU server` such as [mediasoup] (https://mediasoup.org/) or `similars` on `mirotalk` , to have `more large` number of `users` connected in the `same room` using `less bandwidth`. This will be a very nice goal! 🏆

**Comment by miroslavpejic85** [comment]
I go to close this task and create a new one to achieve this goal! ;)
