### ISSUE TITLE
Mattermost Plugin for Mirotalk Integration

### ISSUE THREAD

**Issue by ajay01994** [miroslavpejic85/mirotalk#243]
We would like to request a new feature: a Mattermost plugin for seamless integration with Mirotalk. This plugin will allow Mattermost users to initiate and join Mirotalk video calls directly from the Mattermost interface.

Pros
Enhanced Communication: Facilitates quick and easy video communication within the Mattermost platform.
Increased Productivity: Reduces the need to switch between different applications for video calling and team communication.
User Convenience: Provides a unified experience for team collaboration, combining messaging and video calling in one place.
Additional context
We believe this feature would greatly benefit users who rely on Mattermost for team communication and Mirotalk for video calls. Integrating these platforms would streamline workflows and improve overall user experience. Here is a link to the Mattermost plugin marketplace for reference: [Mattermost Video Calling Plugins](https://mattermost.com/marketplace-category/video-calling/).

**Comment by miroslavpejic85** [comment]
Perhaps you could also reach out to the Mattermost community to see if anyone is interested in integrating it.

**Comment by ajay01994** [comment]
We have to build ourselves , they have limited bandwidth , i will put my contributions and see if there are many others interested too. it's a missing feature in Mattermost which only Mirotalk can successfully fill in .

**Comment by AdamsGH** [comment]
> We have to build ourselves , they have limited bandwidth , i will put my contributions and see if there are many others interested too. it's a missing feature in Mattermost which only Mirotalk can successfully fill in . I have personally tested and also looked into forums for feedback in terms of quality and effectiveness Miro talk beats all available open source communication softwares its even better than few popular closed source tools and softwares too

Hey! Do you have any updates or some kind of project you working now for this integration to happen? Wanna put my eye on it and maybe contribute if can be useful =)

**Comment by miroslavpejic85** [comment]
### Setting Up a Slash Command in Mattermost

1. Navigate to **Main Menu > Integrations > Slash Commands** in Mattermost.
2. Click on **Add Slash Command** and configure the following settings:
   - **Title**: Enter a descriptive title (e.g., `P2P Command`).
   - **Command Trigger Word**: Set the trigger word to `p2p`.
   - **Callback URLs**: Enter the URL for your Express server (e.g., `https://yourserver.com/mattermost`).
   - **Request Method**: Select **POST**.
   - **Enable Autocomplete**: Check the box for **Autocomplete**.
   - **Autocomplete Description**: Provide a brief description (e.g., `Get MiroTalk P2P meeting room`).

3. Save the slash command and **copy the generated token**; you will need it for your server setup.

4. **Update the MiroTalk P2P `.env` File**: 
   - Add the new parameters required for your configuration.

```env
MATTERMOST_ENABLED=false # true or false
MATTERMOST_SERVER_URL=YourMattermostServerUrl
MATTERMOST_USERNAME=YourMattermostUsername
MATTERMOST_PASSWORD=YourMattermostPassword
MATTERMOST_TOKEN=YourMettarmostToken
```
![mirotalk-p2p-mattermost](https://github.com/user-attachments/assets/67da7b41-b412-46c5-bb2e-1bb603982683)

**Comment by miroslavpejic85** [comment]
Done in MiroTalk SFU and MiroTalk C2C as well!

---

<img width="1527" alt="mirotalk-mattermost" src="https://github.com/user-attachments/assets/b1a0b942-a857-4bbc-9941-35351ae4144d">

**Comment by AdamsGH** [comment]
@miroslavpejic85 many thanks!

**Comment by ajay01994** [comment]
@miroslavpejic85 are you planning to create a separate plugin like mentioned  here -https://mattermost.com/marketplace-category/new-noteworthy/

**Comment by karthikindia** [comment]
> MATTERMOST_TOKEN=YourMettarmostToken
which token to be added here bot token id or /command token id or user personal access token id ?

**Comment by complib2891** [comment]
seeing the same issue, 404 like the screenshot, i'm at mattermost 10.7.0, the slash command did POST to mirotalk. just showing a bunch of html
