### ISSUE TITLE
Users unable to see or hear each other

### ISSUE THREAD

**Issue by surgeNexus** [miroslavpejic85/mirotalk#245]
# Bug Report

## Describe the bug

All users are unable to see or hear each other today however, they were yesterday. The only configuration changes are that I installed c2c and bro, as well as the webrtc. P2P worked fine yesterday.

receiving STUN and TURN failures.

go to SFU or P2P and connect multiple users on separate internet connections. (Works fine on the same network)

## Screenshots
<img width="777" alt="image" src="https://github.com/user-attachments/assets/d183cdd7-d4e5-4118-8d04-25032006c04d">

## Desktop - Mobile

Issue occurs on desktop and mobile

Please complete the following information:

 - Windows, MacOS, Debian, iOS
 - Chrome, Safari, Firefox
 - Latest version on Github. All devices and browsers on current build.

**Comment by miroslavpejic85** [comment]
Hi @surgeNexus,

This is **`not a bug`** but a normal behavior when the default TURN server configuration specified in this repo `.env` file reaches its traffic limit of 50 GB per month. 

<img width="1153" alt="turn" src="https://github.com/user-attachments/assets/c4cd607b-e089-4b30-9e09-e91cad69d5cb">

---

As outlined in the `.env` file, you have two options to address this:

1. **Create Your Own Account**: Sign up for a metered TURN service as specified [here](https://github.com/miroslavpejic85/mirotalk/blob/959c5aba0efef19022a5b033451708ac3d2574d9/.env.template#L89).

2. **Self-Host Your TURN Server**: Set up your own TURN server by following our [installation guide](https://docs.mirotalk.com/coturn/installation/).

For more information, you can also visit our [STUN/TURN documentation](https://docs.mirotalk.com/coturn/stun-turn/).

For future inquiries, please use our 👉 **[community forum](https://discord.gg/rgGYfeYW3N)** or the help & support channel. Many common questions, including this one, have already been addressed there, and it's a great place to find answers and engage with the MiroTalk community.

Warm regards,  
Miroslav
