### ISSUE TITLE
Jitsi Alternative

### ISSUE THREAD

**Issue by bastus11** [miroslavpejic85/mirotalk#246]
Miroslav, first of all, congratulations—I really liked your application. I found it by chance while looking for an alternative to Jitsi.

I have a few questions for you:

Will LDAP authentication be coming?
Are you planning to release a mobile app?
Can ı change frontend config?

**Comment by miroslavpejic85** [comment]
Thank you for your interest and kind words about the application!

For any questions related, please use the community forum.

Thank you for your understanding!
