### ISSUE TITLE
Can this system be deployed and used on a local area network? It cannot connect to the Internet.

### ISSUE THREAD

**Issue by lijun535535** [miroslavpejic85/mirotalk#247]
### Feature request

Can this system be deployed and used on a local area network? It cannot connect to the Internet.

### Pros

Can this system be deployed and used on a local area network? It cannot connect to the Internet.

**Comment by miroslavpejic85** [comment]
MiroTalk can operate without Internet access, provided all necessary resources (e.g., scripts, dependencies) are hosted locally. Ensure that any external dependencies, such as those from CDNs, are bundled locally or replaced with local resources. You can achieve this by creating a `CDNs` folder, storing all CDN files there, and including them in the project.

For Node.js dependencies listed in the `package.json`, you can install them offline by pre-downloading on a connected machine, setting up a local npm registry, or bundling the dependencies for transfer.

I noticed you also asked about this in the community forum, which is the appropriate place for such discussions. We’ll consider this closed here, as there are no immediate plans to prioritize this task. You can also add it to the ideas and suggestions channel.

Thank you for your understanding.
