### ISSUE TITLE
is there a possiblty of connecting over WIFI-direct

### ISSUE THREAD

**Issue by Viper912** [miroslavpejic85/mirotalk#249]
### Feature request

meaning that when 2 devices are on the same network
there is not network data consumed
(i have limited internet in my country)
also can it still be shared with 60fps and low latency?

### Pros

easier conection for peoaple with limited internet usage

**Comment by miroslavpejic85** [comment]
Please join the [community forum](https://discord.gg/rgGYfeYW3N) if you have any questions. Thank you!
