### ISSUE TITLE
DOUBT SIR!!

### ISSUE THREAD

**Issue by LunaticCodeKing** [miroslavpejic85/mirotalk#25]
why u r using ngrok...please explain?

**Comment by Jaideep25** [comment]
Hello @LunaticCodeKing  Welcome! @miroslavpejic85  uses ngrok to check whether the app works on other devices, locally, it's good for testing and if you want to host on your servr it's useful!

**Comment by miroslavpejic85** [comment]
Hi @LunaticCodeKing 😉
[Ngrok](https://ngrok.com/) you can use to `exposing mirotalk` to `outside world` directly from `your local PC`.
More details regarding ngrok you can found it here: https://ngrok.com/product
After you have created your account and saved your token in .env just enable this feature in this way:
``` bash
NGROK_ENABLED = true
NGROK_AUTH_TOKEN = YourNgrokAuthToken
```
ref:https://github.com/miroslavpejic85/mirotalk#setup-turn-and-ngrok

When you start mirotalk `npm start` you can see in the console logs something like this

![image](https://user-images.githubusercontent.com/70838434/120653786-52912000-c481-11eb-9de8-f86a928a73cb.png)

The generated link `https ....` open it in your browser and share the room link to whoever you want.
Without ngrok mirotlak started from your local PC, cannot be reached from the outside world. And you can only use it in your local network.

As  @Jaideep25 said, you can use ngrok, to test mirotalk before releasing it on [Heroku](https://www.heroku.com/)-[Railway](https://railway.app) etc.

Hope we have solved your doubts?

**Comment by LunaticCodeKing** [comment]
you are great...thank u so much!!!

**Comment by miroslavpejic85** [comment]
u welcome! 😉
