### ISSUE TITLE
I am unable to establish the connection between the two different networks example (joining from phone(internet) as a peer1 and desktop (wifi) as a peer 2 

### ISSUE THREAD

**Issue by charantejchintu** [miroslavpejic85/mirotalk#252]
### Describe the bug

![within the network ](https://github.com/user-attachments/assets/35e95fab-5d0b-416b-8ebd-50503122fc0a)
unable to establish the connection between the two different networks 

### Steps to reproduce

establish the connection between the two different networks

### Expected behavior

it should work when  you join the meeting from any network

### Device

- [X] Android
- [ ] iPhone
- [ ] Linux
- [ ] Mac
- [X] Windows

### Browser

- [X] Chrome (or Chromium based)
- [ ] Firefox
- [X] Safari
- [ ] Android browser
- [ ] iOS browser
- [ ] Other desktop browser

### Reproducibility

No

### Additional context

i am hosted on my own server but they couldn't establish the connection between the two different networks 
![within the network ](https://github.com/user-attachments/assets/333616ea-fee8-45f5-a37e-07bc350bb1da)

**Comment by miroslavpejic85** [comment]
This is `not a bug`. For `help and support`, please use the dedicated channel on the **[community forum](https://discord.gg/rgGYfeYW3N)**. 

Please double-check the `STUN/TURN` configuration in your `.env` file. We recommend creating your own account for TURN or self-hosting your own server by following the documentation provided.

Note that the GitHub repository is specifically related to our **[live demo](https://p2p.mirotalk.com)** not about private instances of the project.

Thank you!

**Comment by charantejchintu** [comment]
i have updated in the .env file also

 🟢 Your Public IP Address is 14.97.200.243

🟢 The STUN server is reachable!

🟢 The TURN server is reachable!
even though it is not establishing the connection between the two different networks

**Comment by miroslavpejic85** [comment]
I have answered in the community forum. Thank you!
