### ISSUE TITLE
Docker P2P - Enabling volume fails server to start

### ISSUE THREAD

**Issue by collse** [miroslavpejic85/mirotalk#254]
### Describe the bug

When adding the /app volume from the .env template, the server fails to start, removing it works perfectly fine:

```
mirotalk  | > mirotalk@1.3.79 start
mirotalk  | > node app/src/server.js
mirotalk  | 
mirotalk  | node:internal/modules/cjs/loader:1228
mirotalk  |   throw err;
mirotalk  |   ^
mirotalk  | 
mirotalk  | Error: Cannot find module '/src/app/src/server.js'
mirotalk  |     at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
mirotalk  |     at Module._load (node:internal/modules/cjs/loader:1051:27)
mirotalk  |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
mirotalk  |     at node:internal/main/run_main_module:28:49 {
mirotalk  |   code: 'MODULE_NOT_FOUND',
mirotalk  |   requireStack: []
mirotalk  | }
mirotalk  | 
mirotalk  | Node.js v20.18.0
```

seems similar to https://github.com/miroslavpejic85/mirotalk/issues/182

### Steps to reproduce

install via docker

enable the ./app volume

### Expected behavior

if still supported, the volume should mount else it should be removed from .env template

### Device

- [ ] Android
- [ ] iPhone
- [X] Linux
- [ ] Mac
- [ ] Windows

### Browser

- [ ] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Android browser
- [ ] iOS browser
- [ ] Other desktop browser

### Relevant log output

```shell
mirotalk  | > mirotalk@1.3.79 start
mirotalk  | > node app/src/server.js
mirotalk  | 
mirotalk  | node:internal/modules/cjs/loader:1228
mirotalk  |   throw err;
mirotalk  |   ^
mirotalk  | 
mirotalk  | Error: Cannot find module '/src/app/src/server.js'
mirotalk  |     at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
mirotalk  |     at Module._load (node:internal/modules/cjs/loader:1051:27)
mirotalk  |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
mirotalk  |     at node:internal/main/run_main_module:28:49 {
mirotalk  |   code: 'MODULE_NOT_FOUND',
mirotalk  |   requireStack: []
mirotalk  | }
mirotalk  | 
mirotalk  | Node.js v20.18.0
```
```


### Reproducibility

No

### Additional context

_No response_

**Comment by miroslavpejic85** [comment]
In the Dockerfile, the `WORKDIR` is set to `/src`, not `/app`. 

To correctly run the application in Docker, please follow the documented steps:

```bash
cp .env.template .env
cp docker-compose.template.yml docker-compose.yml
docker pull mirotalk/p2p:latest
docker-compose up  # Add -d for daemon mode
docker-compose down
```

The volume mount is configured correctly, as shown in the image below:

<img width="804" alt="mirotalk-p2p-docker-compose" src="https://github.com/user-attachments/assets/0c1b8bcd-b5c3-475b-beb6-0d0bae17e6dc">

If you have any questions or need further clarification, feel free to ask in our [mirotalk community forum](https://discord.gg/rgGYfeYW3N). Thank you!

**Note**: If you want to change the `WORKDIR` or adjust the volume mounts, you will need to build your own image.

**Comment by collse** [comment]
that is exactly how it has been setup - hence the report
<img width="1411" alt="image" src="https://github.com/user-attachments/assets/cc00d90d-f7aa-40ec-83d8-b6d9d99566d8">

**Comment by miroslavpejic85** [comment]
Ref: https://hub.docker.com/repository/docker/mirotalk/p2p/general
