### ISSUE TITLE
Passphrase room name generation

### ISSUE THREAD

**Issue by trymeouteh** [miroslavpejic85/mirotalk#257]
### Feature request

The option to generate a room URL using a passphrase of three words instead of a random string.

### Pros

Easier to manually type in room name.

### Additional context

A common feature on alternative services

**Comment by miroslavpejic85** [comment]
As mentioned earlier, please check our **[community forum](https://discord.gg/rgGYfeYW3N)** before requesting new features.

By default, we generate room names using `random strings, numbers`, or `UUID4` to avoid room name collisions between different users. This ensures that each room is unique and prevents unintentional overlaps. 

If you'd like to use your own custom room name, simply type it into the input field before joining. This way, you have the flexibility to create a recognizable room name without compromising the system’s reliability.

**Benefits of our current setup:**
- **Collision Prevention**: Random or UUID-generated room names ensure that each room is unique, minimizing accidental overlap with other users’ rooms.
- **Security**: Randomized room names make it harder for unauthorized users to guess room links.
- **Simplicity**: Users who prefer quick room creation can rely on auto-generated names without the need to create a custom name each time. 

Our setup strikes a balance between security, simplicity, and flexibility!

![mirotalk-p2p-room-name](https://github.com/user-attachments/assets/fd0641dd-1e4e-4cc3-b443-2f559b6dbe2b)

You can also join a specific room directly by using query parameters in the URL, like so:

- https://p2p.mirotalk.com/join?room=MY-ROOM-NAME
- https://p2p.mirotalk.com/join?room=MY-ROOM-NAME&name=MY-NAME
- https://p2p.mirotalk.com/join?room=MY-ROOM-NAME&name=MY-NAME&video=false&audio=false
- ...
