### ISSUE TITLE
Profile Picture

### ISSUE THREAD

**Issue by trymeouteh** [miroslavpejic85/mirotalk#258]
### Feature request

The option to upload a profile picture to be shown when your camera is off.

### Pros

A custom image of your choice instead of letters from your username.

**Comment by miroslavpejic85** [comment]
The feature you mentioned is already available! Please check with our **[community forum](https://discord.gg/rgGYfeYW3N)** before requesting new features.
 
Gravatar (Globally Recognized Avatar) is a free service that associates an image (avatar) with an email address, allowing you to have a profile image automatically show up on supported sites and applications whenever you use your email address.

Go to **[Gravatar’s website](https://gravatar.com)** and Create Your Own Gravatar.

Your Gravatar will automatically appear on websites and applications that support Gravatar whenever you use that specific email address. The image is fetched based on your email, so if a site supports Gravatar, it should automatically display your profile image.

![mirotalk-p2p-avatar](https://github.com/user-attachments/assets/2a524ce0-12ac-4de2-b41d-69f3de2ceb2a)

Here are the top benefits of using Gravatar:

1. **Universal Profile**: Your Gravatar is recognized across thousands of websites, ensuring a consistent profile picture wherever you go online.

2. **Simple and Automatic**: Set it up once, and your profile picture updates automatically across all Gravatar-enabled sites whenever you make a change.

3. **Enhanced Recognition**: A consistent photo helps build trust and recognition, especially valuable for professionals, bloggers, and developers. 

4. **Lightweight for Websites**: Websites don’t need to store your image, helping them run faster while keeping your profile visible.
