### ISSUE TITLE
Socket.IO access url for client

### ISSUE THREAD

**Issue by fredericpetit02** [miroslavpejic85/mirotalk#26]
Hello, 

i install the app in a nodejs16 srv, but at the first try, i have ERR_CONNECTION_REFUSED for socket.IO url on client side : the port is not included in the url so that's why. Did i made a mistake ? i did not touch the original code.

thks

**Comment by miroslavpejic85** [comment]
Hi @fredericpetit02, welcome! 
Try with `nodejs v12.X`: https://nodejs.org/en/blog/release/v12.22.1/
ref: https://github.com/miroslavpejic85/mirotalk#quick-start
Let me know if ok? 😉

**Comment by miroslavpejic85** [comment]
@fredericpetit02 any news? 😅
