### ISSUE TITLE
Support for Custom Client Integration with Self-hosted P2P Server

### ISSUE THREAD

**Issue by techteamyooli** [miroslavpejic85/mirotalk#260]
### Feature request

A feature or guide for custom client integration would allow users to build more flexible and tailored meeting interfaces, enhancing the usability and customization of self-hosted MiroTalk instances.
Ideally, this feature would allow for full control over the meeting experience, including UI, controls, and user interactions, outside the iframe embedding method.
Use Case:
As a self-hosted MiroTalk user, I want to integrate my own front-end client, allowing for a unique user experience and better control over meeting functionality.

### Pros

- Increased Flexibility and Customization: A custom client would allow users to design and implement a meeting interface that fits their specific needs and branding, without being constrained by the iframe limitations. This can include custom layouts, features, and controls that better align with an organization's workflow or user preferences.

- Improved User Experience: By removing the iframe, users could build a more seamless and native experience, enhancing performance and reducing the need for workarounds.
Tailored UI/UX elements can make the platform feel more integrated with other tools and services, improving usability.

- Tailored Branding and Theming: Organizations can customize the look and feel of the client to match their own branding, which is important for customer-facing services. This allows companies to provide a more professional and consistent experience that aligns with their corporate identity.

- Adaptation to Unique Use Cases: Some use cases, such as large-scale conferences, education platforms, or health consultations, may have specific requirements (e.g., additional features, room management, or specialized controls) that a generic iframe client cannot easily accommodate. A custom client would allow for more specialized features and configurations tailored to these needs.

- Increased Collaboration and Community Engagement: Opening up the possibility for custom clients would foster a more active development community, as developers can contribute new ideas, integrations, and improvements. This can lead to an ecosystem of third-party tools, plugins, and extensions that enhance the platform's capabilities over time.

### Additional context

Expected Outcome:
Official support or a comprehensive guide on how to integrate a custom client with the self-hosted MiroTalk P2P server for meetings.

**Comment by miroslavpejic85** [comment]
Hi there! 😄  

Everything you've mentioned is already implemented!  

- **[Brand](https://github.com/miroslavpejic85/mirotalk/blob/f3be35403a128a27d5635af7022ec6473f49b502/public/js/brand.js#L31):** Customize the brand, a `Regular license` is required, which you can purchase directly from CodeCanyon [here](https://codecanyon.net/item/mirotalk-p2p-webrtc-realtime-video-conferences/38376661).  
- **[UI Buttons and Features](https://github.com/miroslavpejic85/mirotalk/blob/master/public/js/config.js):** You can customize the buttons displayed during meetings by editing this file.
- **Documentations**:
   - [Self-Hosting Guide](https://docs.mirotalk.com/mirotalk-p2p/self-hosting/)
   - [Host Protection Mode](https://docs.mirotalk.com/mirotalk-p2p/host-protection/)
   - [Direct Room Join](https://docs.mirotalk.com/mirotalk-p2p/join-room/)
   - [REST API Documentation](https://docs.mirotalk.com/mirotalk-p2p/api/)  
- **[Community Forum](https://discord.gg/rgGYfeYW3N):** For `ideas and suggestions`, please use the dedicated channel in the forum next time.  

Thanks for your input! 😊
