### ISSUE TITLE
Hide/Disable AI

### ISSUE THREAD

**Issue by trymeouteh** [miroslavpejic85/mirotalk#262]
### Feature request

I do not have a discord account so therefore I am unable to ask in the community forum.

I would like to ask weather it is possible to disable the AI integration and AI features in the UI if you wish to host a instance?

### Pros

To not have AI feature showing to discourage users from using the service if the users is not comfortable using AI services.

### Additional context

A setting to disable all the AI stuff in the back end and front end

**Comment by miroslavpejic85** [comment]
> I do not have a discord account so therefore I am unable to ask in the community forum.

Simple Create a Discord account at [discord.com](https://discord.com/), verify your email, and join the community using the invite link!

Disable it from the `.env` file

```bash
# ChatGPT/OpenAI
# 1. Goto https://platform.openai.com/
# 2. Create your account
# 3. Generate your APIKey https://platform.openai.com/account/api-keys

CHATGPT_ENABLED=false # ---------------------------> set to false
CHATGPT_BASE_PATH=https://api.openai.com/v1/
CHATGPT_APIKEY=YourOpenAiApiKey
CHATGPT_MODEL=gpt-3.5-turbo
CHATGPT_MAX_TOKENS=1000
CHATGPT_TEMPERATURE=0
```
