### ISSUE TITLE
Disable Video/Camera

### ISSUE THREAD

**Issue by trymeouteh** [miroslavpejic85/mirotalk#263]
### Feature request

I do not have a discord account so therefore I am unable to ask in the community forum.

Is there a setting for instances to now allow video/camera at all except for screen sharing. To have an instance that only is for audio and screen sharing? Would be great feature to have if it is not possible to do for a self hosted instance.

### Pros

To have a simpler instance with more privacy by not having a video feed at all.

**Comment by miroslavpejic85** [comment]
> I do not have a discord account so therefore I am unable to ask in the community forum.

Simple Create a Discord account at [discord.com](https://discord.com/), verify your email, and join the community using the invite link!

> Is there a setting for instances to now allow video/camera at all except for screen sharing. To have an instance that only is for audio and screen sharing? Would be great feature to have if it is not possible to do for a self hosted instance.

You can customize the room by editing the `config.js` file to hide unwanted buttons or features: [Edit config.js](https://github.com/miroslavpejic85/mirotalk/blob/master/public/js/config.js).
