### ISSUE TITLE
Dedicated app

### ISSUE THREAD

**Issue by stemy2** [miroslavpejic85/mirotalk#265]
### Feature request

Hello,

Using mobile web browsers for video conferences is not very practical, especially for non techy people.
You have to set manually Android to be able to even have the autorisation to use camera ans microphone and even then, it doesn't work on some browsers.

### Pros

Using a dedicated app would prevent the need of fastidious configuration.

**Comment by miroslavpejic85** [comment]
Hi steamy2, 

We understand your point but for now we want to keep it as a Progressive Web App.

Keeping MiroTalk P2P as a Progressive Web App (PWA) has several advantages, especially for video conferencing solutions. Here’s a list of key pros:

1. No Installation Required

	•	Easy Access: Users can simply open a link in their browser without downloading or installing an app.
	•	Storage-Friendly: PWAs consume minimal device storage compared to native apps, making them ideal for users with limited space.

2. Cross-Platform Compatibility

	•	PWAs work seamlessly on any device with a modern browser (Android, iOS, Windows, macOS, Linux).
	•	No need to develop and maintain separate apps for each platform (e.g., Android, iOS).

3. Automatic Updates

	•	PWAs always run the latest version, as updates are delivered through the server.
	•	No need for users to manually update through app stores.

4. Native App-Like Experience

	•	PWAs can be added to the home screen and launched like a native app.
	•	Full-screen mode eliminates the browser interface, providing a cleaner user experience.
	•	Push notifications and offline capabilities (e.g., saving meeting links or chat data) mimic native app functionality.

5. Cost-Effective Development

	•	Developing and maintaining a single PWA is far cheaper than creating separate native apps for multiple platforms.
	•	Saves time and resources, especially for small or independent teams.

6. Accessibility

	•	Users can access MiroTalk P2P instantly via a link without worrying about app store restrictions or availability.
	•	Perfect for one-time or occasional users who don’t want to install a dedicated app.

7. Browser Features

	•	Modern browsers provide robust WebRTC support, enabling MiroTalk P2P to deliver high-quality video and audio without relying on platform-specific APIs.
	•	Easy integration with browser-based tools like screen sharing and tab capture.

8. Avoids App Store Limitations

	•	No need to comply with stringent app store guidelines or pay fees for app distribution.
	•	Direct control over distribution and branding.

9. Faster Iterations

	•	Changes and fixes can be deployed instantly, without waiting for app store approvals.
	•	Ensures quicker responses to user feedback or bug reports.

10. Ideal for Non-Tech-Savvy Users

	•	Users unfamiliar with app stores can simply use a web link.
	•	Minimal setup complexity makes it easier for less tech-savvy participants to join meetings.

Please we invite you to Join and share your insights and suggestions in our MiroTalk dedicated community forum next time!

Thank you!
