### ISSUE TITLE
Remove unnecessary tracking domains

### ISSUE THREAD

**Issue by stemy2** [miroslavpejic85/mirotalk#266]
### Feature request

Hello,

While checking the requests with ublock, i had a bad surprise seeing that there were some of the requests originating from tracking domains like:

-Cloudflares
-gstatic
-google
-Googleapis

I checked, they can be blocked without compromizing the software usability.

### Pros

Your software pretend to respect our privacy. I get you personally collect our private informations, but not so muche the included tracking domains

**Comment by miroslavpejic85** [comment]
> Your software pretend to respect our privacy. I get you personally collect our private informations, but not so muche the included tracking domains

As outlined in our [Privacy Policy](https://p2p.mirotalk.com/privacy), you can ensure compliance by simply disabling the **stats** option in the `.env` file.

```
# Stats
# Umami: https://github.com/umami-software/umami
# We use our Self-hosted Umami to track aggregated usage statistics in order to improve our service.

STATS_ENABLED=false # ------> set to false
STATS_SCR=https://stats.mirotalk.com/script.js
STATS_ID=c7615aa7-ceec-464a-baba-54cb605d7261
```

As we've mentioned before, we kindly encourage you to use our community forum for requests, ideas, or suggestions before posting here. Thank you for your collaboration! 🙌✨

**Comment by IT-Canify** [comment]
Short comment to that. I also used your software last year and wanted to make it the standard in our company. Then I stumbled across the CDNs and had to stop.

GDPR in the EU
https://wideangle.co/blog/content-delivery-network-cdn-and-gdpr

A simple request to a hidden server (for the user) is a problem. If several pages integrate Google Fonts, Google can see how I move through the web etc.

Often I solve the problem by selfhosting or by using a simple cached proxy without header forwarding. I am not sure whether this is perfectly legal but for example via the cdn https://bunny.net/ which is GDPR conform, you could proxy all the other cdns. It is more or less configured in 5min and the only thing that changes is the domain, the path is the same. They also provide a Data Processing Agreement that you could simply transfer further to your users from the EU

Please check for yourself what I'm saying, I think it fits but I'm not a lawyer :-)

**Comment by haerth** [comment]
Short comment to that. I also used your software last year and wanted to make it the standard in our company. Then I stumbled across the CDNs and had to stop.

GDPR in the EU
https://wideangle.co/blog/content-delivery-network-cdn-and-gdpr

A simple request to a hidden server (for the user) is a problem. If several pages integrate Google Fonts, Google can see how I move through the web etc.

Often I solve the problem by selfhosting or by using a simple cached proxy without header forwarding. I am not sure whether this is perfectly legal but for example via the cdn https://bunny.net/ which is GDPR conform, you could proxy all the other cdns. It is more or less configured in 5min and the only thing that changes is the domain, the path is the same. They also provide a Data Processing Agreement that you could simply transfer further to your users from the EU

Please check for yourself what I'm saying, I think it fits but I'm not a lawyer :-)
