### ISSUE TITLE
Support CORS *

### ISSUE THREAD

**Issue by nbao** [miroslavpejic85/mirotalk#267]
### Feature request

we use mirotalk as a service (work with drupal https://www.drupal.org/project/mirotalk_sfu). instead of embedding into web using iframe we write our own js code to call to server but i get error **stric-orgin-when-cross-origin**.

### Pros

I don't know if there is a way to add an option in the config.js that allows to add **Access-Control-Allow-Origin: *** or Access-Control-Allow-Origin: https://MySite.com

**Comment by miroslavpejic85** [comment]
This is the MiroTalk P2P repository, not the MiroTalk SFU. For details on MiroTalk SFU, please refer to [this repository](https://github.com/miroslavpejic85/mirotalksfu).

Both repositories support CORS settings. For the P2P version, you can find the CORS configuration [here](https://github.com/miroslavpejic85/mirotalk/blob/master/.env.template#L27), and for the SFU version, it’s located [here](https://github.com/miroslavpejic85/mirotalksfu/blob/6f3c3681b37b4ba8ca67a03d54db34dac9f39042/app/src/config.template.js#L60).

We also encourage you to join our [community forum](https://discord.gg/rgGYfeYW3N), where you can find many answers to your questions, often without needing to open issues here.

Thank you!
