### ISSUE TITLE
Screen sharing time full screen not available for who is view shared screen , there block is full show other people

### ISSUE THREAD

**Issue by ugale-deepak3010** [miroslavpejic85/mirotalk#27]
Please resolve that issue as soon as possible

**Comment by Jaideep25** [comment]
Hey @ugale-deepak3010  Welcome!
As you can see am sharing my screen here....
![image](https://user-images.githubusercontent.com/67269475/120958674-d5fa8c00-c775-11eb-86d8-59e47566b65d.png)
Now if I click on that sharing it becomes bigger and you can see the screen share fully
![image](https://user-images.githubusercontent.com/67269475/120958748-f9253b80-c775-11eb-9bd4-2e8a58e6dd90.png)

**Comment by miroslavpejic85** [comment]
Hi @ugale-deepak3010. 
As @Jaideep25  said or `click` on the `video element` with the mouse to see the screen sharing in `full size` and then `Click again to exit` or press `ESC` on your Keyboard. Or you can also use this `button` at the top right. 

![image](https://user-images.githubusercontent.com/70838434/120973116-cd528780-c76e-11eb-81f4-0dae8f6013ab.png)

This is also valid for the WebCam to.
Regards

**Comment by Jaideep25** [comment]
@ugale-deepak3010  can we close this issue now?

**Comment by ugale-deepak3010** [comment]
> @ugale-deepak3010  can we close this issue now?

Actually in this village power problem ,
I tested your all comments but I need check for atleast check once
But power problem so unable to test properly
Please be patience.
I will definately the remove it after checking 
Unfortunately today Indian standard full day power is not coming.
I commented this on my android mobile.
Thank for caring  project .![IMG_20210607_174126.jpg](https://user-images.githubusercontent.com/65403702/121014426-994f8480-c7b7-11eb-84c2-df646d6331ae.jpg)

**Comment by ugale-deepak3010** [comment]
> Hey @ugale-deepak3010  Welcome!
> As you can see am sharing my screen here....
> ![image](https://user-images.githubusercontent.com/67269475/120958785-0b9f7500-c776-11eb-8ef1-9b2d296950b1.png)
> 
> Now if I click on that sharing it becomes bigger and you can see the screen share fully
> ![image](https://user-images.githubusercontent.com/67269475/120958748-f9253b80-c775-11eb-9bd4-2e8a58e6dd90.png)
> 



Hello friend 
Late for discussion but please guide me where I click to see full screen presentation on my device

Latest chrome browser on my android phone.

I shared my laptop screen on my phone.

Please see image and tell me.
🙏🏻🙏🏻🙏🏻
![Screenshot_2021-06-08-18-19-49-996_com.android.chrome.jpg](https://user-images.githubusercontent.com/65403702/121188078-61fbd900-c886-11eb-81d6-f64828392a04.jpg)

**Comment by Jaideep25** [comment]
> > Hey @ugale-deepak3010  Welcome!
> > As you can see am sharing my screen here....
> > ![image](https://user-images.githubusercontent.com/67269475/120958785-0b9f7500-c776-11eb-8ef1-9b2d296950b1.png)
> > Now if I click on that sharing it becomes bigger and you can see the screen share fully
> > ![image](https://user-images.githubusercontent.com/67269475/120958748-f9253b80-c775-11eb-9bd4-2e8a58e6dd90.png)
> 
> Hello friend
> Late for discussion but please guide me where I click to see full screen presentation on my device
> 
> Latest chrome browser on my android phone.
> 
> I shared my laptop screen on my phone.
> 
> Please see image and tell me.
> 🙏🏻🙏🏻🙏🏻
> ![Screenshot_2021-06-08-18-19-49-996_com.android.chrome.jpg](https://user-images.githubusercontent.com/65403702/121188078-61fbd900-c886-11eb-81d6-f64828392a04.jpg)

Click on the picture which you wanna make it full screen...

**Comment by ugale-deepak3010** [comment]
Which image, not work  Click anywhere I am till online in this meet

**Comment by miroslavpejic85** [comment]
Hi @ugale-deepak3010, you right! Now i understand the problem.
Yes `on Mobile device` on video click event not works..., and also there isn't a full screen button on right top. 
I need to found the solution for mobile devices if some one share desktop to see it correctly. Thanks

**Comment by ugale-deepak3010** [comment]
> Hi @ugale-deepak3010, you right! Now i understand the problem.
> Yes `on Mobile device` on video click event not works..., and also there isn't a full screen button on right top. 
> I need to found the solution for mobile devices if some one share desktop to see it correctly. Thanks 

Thanks for reply
 and one more issues I think that already you know while mobile device using
When I share screen there show something error.

**Comment by Jaideep25** [comment]
Actually you can't screenshare in mobile devices...

**Comment by miroslavpejic85** [comment]
Hi @ugale-deepak3010. Good news 🚀
I have enabled the full screen mode when you clicking on a video element also for mobile devices: wellhttps://github.com/miroslavpejic85/mirotalk/commit/af7406c40b927a04a7527d7b9b84c9afac976b8c You should now be able to see the shared screen.

![image](https://user-images.githubusercontent.com/70838434/121247189-3c7cc880-c8a2-11eb-8dc3-424d895c2743.png)

**Comment by ugale-deepak3010** [comment]
Thank you very much.

**Comment by miroslavpejic85** [comment]
u welcome! 
PS: I don't like that every click enters on FS, if necessary use this button:
![full-screen-mode](https://user-images.githubusercontent.com/70838434/121956472-75fd7a00-cd61-11eb-9b6a-91a724c0075b.png)
