### ISSUE TITLE
request

### ISSUE THREAD

**Issue by catur515** [miroslavpejic85/mirotalk#3]
[#ask, #request]
Hi, how to make accept or reject incoming calls while joining.

**Comment by miroslavpejic85** [comment]
Hi catur515, welcome!
Why do you need to reject the join in the room?
You can create your own personal room, for example 
https://mirotalk.herokuapp.com/catur515 
and then share it with only whoever you want to be in the conference.
Thank you to using mirotalk, you can adapt it based off your exigence :)

**Comment by catur515** [comment]
@miroslavpejic85  I tried to make a video call.
for example like this user 1 (inisiator) share room catur515, 
before user 2 joining this room , inisiator gets a notification that a user 2 will join.
so the user 2 cannot join if inisiator hasn't accepted it.
thankyou.
