### ISSUE TITLE
Video Is Not Showing

### ISSUE THREAD

**Issue by Harikishnan** [miroslavpejic85/mirotalk#30]
When I Am Connecting to The Same internet The Video Is Showing But When I Used Two Different Connections The Other Users Video Is In black Colour Only And Not Showing...

Please Help Mee

**Comment by Jaideep25** [comment]
Hey @Harikishnan  Welcome!
Did you check your internet speed of both connections? If yes could you please tell what was it....

**Comment by Jaideep25** [comment]
And could you press ctrl+shift+j and send a ss of both laptops? Thanks!

**Comment by Harikishnan** [comment]
it worked on localhost which is on the same device with a different tab and worked on the same Internet with two devices but not working on two different devices

**Comment by Harikishnan** [comment]
is any problem with hosting the server in Heroku app

**Comment by Harikishnan** [comment]
I checked you tell its not working. i checked the same thing In mirortalk heroku video chat link the same thing happening plss help me

**Comment by Harikishnan** [comment]
it's only working on mirrortalk railway app video chat link..

**Comment by Harikishnan** [comment]
> Hey @Harikishnan Welcome!
> Did you check the internet speed of both connections? If yes could you please tell me what was it...

I checked my connection. it is connecting in mirotalk railway app chat link but not in Heroku video chat link

**Comment by Jaideep25** [comment]
> is any problem with hosting the server in Heroku app

I don't think so.... please press ctrl+shift+j and show me the logs....

**Comment by miroslavpejic85** [comment]
Hi @Harikishnan, welcome! 😉 
I didn't understand why you have problems on [heroku](https://mirotalk.herokuapp.com/) (maybe a temporary problem on heroku service...) The `code` and the `same deployed on both servers`. You can also try to run some tests using [ngrok](https://ngrok.com/) directly from your PC. More details here: 
https://github.com/miroslavpejic85/mirotalk/issues/25
As @Jaideep25 said, to see `mirotalk` console logs on your PC devices, you can press `ctrl+shift+j` or `F12` 
If you see some error related to this issue, you can report it here.
Thanks to using `mirotalk` ❤️

**Comment by Viitservices** [comment]
> When I Am Connecting to The Same internet The Video Is Showing But When I Used Two Different Connections The Other Users Video Is In black Colour Only And Not Showing...
> 
> Please Help Mee

having the same issue any solution?

**Comment by Viitservices** [comment]
> > > When I Am Connecting to The Same internet The Video Is Showing But When I Used Two Different Connections The Other Users Video Is In black Colour Only And Not Showing...
> > > Please Help Mee
> > 
> > 
> > having the same issue any solution?
> 
> Can you show the logs please?

Uncaught DOMException: Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'
    at RTCDataChannel.send (https://webrtc.github.io/adapter/adapter-latest.js:1438:34)
    at https://still-ridge-51074.herokuapp.com/js/client.js:2968:34
    at Array.map (<anonymous>)
    at emitMsg (https://still-ridge-51074.herokuapp.com/js/client.js:2967:37)
    at HTMLButtonElement.<anonymous> (https://still-ridge-51074.herokuapp.com/js/client.js:1796:5)
    at HTMLInputElement.<anonymous> (https://still-ridge-51074.herokuapp.com/js/client.js:1769:20)

**Comment by Viitservices** [comment]
> > > > When I Am Connecting to The Same internet The Video Is Showing But When I Used Two Different Connections The Other Users Video Is In black Colour Only And Not Showing...
> > > > Please Help Mee
> > > 
> > > 
> > > having the same issue any solution?
> > 
> > 
> > Can you show the logs please?
> 
> Uncaught DOMException: Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'
> at RTCDataChannel.send (https://webrtc.github.io/adapter/adapter-latest.js:1438:34)
> at https://still-ridge-51074.herokuapp.com/js/client.js:2968:34
> at Array.map ()
> at emitMsg (https://still-ridge-51074.herokuapp.com/js/client.js:2967:37)
> at HTMLButtonElement. (https://still-ridge-51074.herokuapp.com/js/client.js:1796:5)
> at HTMLInputElement. (https://still-ridge-51074.herokuapp.com/js/client.js:1769:20)

that is from the message when im trynig to use the in app chat but when someone joins the video its shows a black screen and you cant send messages or hear them but when im on the same internet or local everything works

**Comment by Jaideep25** [comment]
@miroslavpejic85  sir you can also edit messages? 😂😂
Hey @Viitservices this is the problem of RTCDataChannel... For more info see [here](https://stackoverflow.com/questions/38986297/failed-to-execute-send-on-rtcdatachannel-rtcdatachannel-readystate-is-not)

**Comment by miroslavpejic85** [comment]
Ok by the logs, i understand where is the problem... `RTCDataChannel  for chat issue` For some reason it isn't `opened`.
I will try to understand what caused it.  👀

**Comment by Harikishnan** [comment]
> Ok by the logs, I understand where is the problem... Chat `RTCDataChannel issue` For some reason, it isn't `opened`.
> I will try to understand what caused it. 
> have 2 questions:
> 
> 1. The devices involved are mobile?
> 2. And what browsers?
> 
> Thanks

I'm Using Mobile And My Laptop
Both Google Chrome

**Comment by Harikishnan** [comment]
This Error Also In mirotalk Heroku Deployed Link. When Opened In Same Internet Connection In Two Different Medium Is That Working But Different Internet Connection In Two Different Mediums. In The Video Section, It Is Full Dark. But The Name And Camera Off Image Is Shown And Cannot Send Chats Also!..
Hope You Find A Good Solution

**Comment by Viitservices** [comment]
i should add note this is only for when i deploy to heroku you link is working just fine

**Comment by Harikishnan** [comment]
is there any other platform either than Heroku and railway

**Comment by miroslavpejic85** [comment]
Hi @Viitservices
A ok, so it's not an actual mirotalk bug on [heroku](https://mirotalk.herokuapp.com/) - [railway](https://mirotalk.up.railway.app/) right?
Did this happen to you when you tried to deploy it on your heroku?

If you use `Heroku`, remember to go in to `your app settings` on heroku and also add `Reveal Config Vars`:

```env
HEROKU_ENVIRONMENT = prod
NGROK_ENABLED = false
NGROK_AUTH_TOKEN = YourNgrokAuthToken
TURN_ENABLED = true
TURN_USERNAME = YourTurnUsername
TURN_PASSWORD = YourTurnPassword
TURN_URLS = YourTurnUrls
```

The `Turn credential` you can take it following this part:
https://github.com/miroslavpejic85/mirotalk#setup-turn-and-ngrok
In case you not want to use Turn, just change this part

```env
TURN_ENABLED = false
```
Regards

**Comment by Jaideep25** [comment]
Hey @miroslavpejic85  i don't think you need to add vars for railway... for me it worked without doing that!

**Comment by miroslavpejic85** [comment]
Hey @Jaideep25 `Turn` is `not mandatory` but recommended: https://webrtc.org/getting-started/turn-server

**Comment by Jaideep25** [comment]
Oh okk... Thanks for the information!

**Comment by Viitservices** [comment]
THANK YOU 

after adding those Reveal Config Vars in my heroku it worked but you have to put the turn server on as well otherwise it wont work if you on a difrent network

thanks for the great app

**Comment by miroslavpejic85** [comment]
u Welcome! So i can close this issue... 🙂
