### ISSUE TITLE
Error during docker install 

### ISSUE THREAD

**Issue by MohamedElashri** [miroslavpejic85/mirotalk#33]
I'm trying to install the docker version and I get this error. I'm trying to install it on my ubuntu VPS 

## Error log
```
ERROR: for mirotalk  Cannot start service mirotalk: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: rootfs_linux.go:59: mounting "/home/mirotalk/.env" to rootfs at "/var/lib/docker/overlay2/c63536f034d94903738c0cb154ea2609baa91a708baff8eb8ffa845536533142/merged/usr/src/app/.env" caused: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for mirotalk  Cannot start service mirotalk: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: rootfs_linux.go:59: mounting "/home/mirotalk/.env" to rootfs at "/var/lib/docker/overlay2/c63536f034d94903738c0cb154ea2609baa91a708baff8eb8ffa845536533142/merged/usr/src/app/.env" caused: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.
```
## steps

```
git clone https://github.com/miroslavpejic85/mirotalk
cd mirotalk
```

```docker-compose up -d```

Then image built happened successfully but when trying to deploy I get the error message above.

**Comment by Jaideep25** [comment]
@MohamedElashri  so hence it got solved?

**Comment by MohamedElashri** [comment]
> @MohamedElashri  so hence it got solved?
> 
> 

No, I still not able to deploy the container.

**Comment by Jaideep25** [comment]
@MohamedElashri  try doing it with npm....

**Comment by miroslavpejic85** [comment]
Hi @MohamedElashri, welcome! 🙂
Did you do this before running docker?
```bash
cp .env.template .env
```

**Comment by MohamedElashri** [comment]
> Hi @MohamedElashri, welcome! 🙂
> 
> Did you do this before running docker?
> 
> ```bash
> 
> cp .env.template .env
> 
> ```
> 
> The Docker is trying to `mounting "/home/mirotalk/.env"` which seems `not to exist` 😉 

Thank you for this quick catch. Sorry I created the.env file in different place and forget to edit the path. 

It works now.

**Comment by miroslavpejic85** [comment]
Good! No problem, it's my pleasure help! 🙂
