### ISSUE TITLE
MCU - SFU architecture

### ISSUE THREAD

**Issue by miroslavpejic85** [miroslavpejic85/mirotalk#35]
`Mirotalk` has no a `intermediate media server` for audio - video communication, they are `pure peer to peer` connections `between browsers`, therefore it requires a `good Bandwidth - CPU`.

The current `WebRTC Mesh` architecture is not optimal for conferences with `more than 6-8 users` in the `same room`. The quality of the call is inversely proportional to the number of people on the call. The approximative users supported in a single room should be `around 6-8` in an average `high-speed connection`. 

The `goal` is to have a `support media server` and `adapt` the current `architecture` to `MCU` (MultiPoint Control Unit) or `SFU` (Selective Forwarding Unit). To have `more users` connected in the `same room`, consuming `less bandwidth`!

![mirotalk-mesh](https://user-images.githubusercontent.com/70838434/121813880-62251b80-cc6e-11eb-999f-f10e11a14850.png)

Any `idea`, `best solution`, `contributions` to `reach this goal` is `very appreciated`! ❤️

`Thank you so much` to all those who `believe` in this project and who `support me`!

**Comment by vcdev87** [comment]
`Hello`, @miroslavpejic85 `!`

**Comment by miroslavpejic85** [comment]
Hi @vcdev87, welcome! 🙂

**Comment by vcdev87** [comment]
Welsome `also to` you @miroslavpejic85 ! :)
When is timeline for `this feature`? 🚀 🎸

**Comment by miroslavpejic85** [comment]
I created this issue to `collect ideas`, `suggestions`, etc. on what could be the `best solution` to achieve this goal. 🏆
Obviously, the collaborators on the project are also welcome. 😎

**Comment by vcdev87** [comment]
>  Obviously, the collaborators are also welcome. 😎

`I forgot` to mention `that` 🤒 

How many **_`collaborators`_** working on this now, and is `there` space for more? 💥  🥇 💯

**Comment by miroslavpejic85** [comment]
Currently about `98% of the code` is `done by me`, look on [commits](https://github.com/miroslavpejic85/mirotalk/commits/master), I've had a `couple of pull requests` which are `which are highly appreciated` ❤️ , and `of course` anyone `who wants to contribute` to the project is `welcome`! 😇

**Comment by vcdev87** [comment]
> Currently about 98% of the code is done by me

Wow, very good @miroslavpejic85 🕺 🎉 , `but also the` 

1. collaborators

did good job `with the` 2% of the code`.` 

Is anyone `collaborator` working on MCU - SFU now? Maybe `space` for more collaborators on MCU `-` SFU ? 🌕 🚀 🎸 

Together we can do `this 💪`

**Comment by miroslavpejic85** [comment]
In my spare time, I'm `looking for` the `possible solutions`, but I `would like` to have some `suggestions` here as well. 🙂
Yeah `Alone we walk fast, but together we go far....` 💪

**Comment by vcdev87** [comment]
`How much time`  y`o`u estimate for this to be im`plemented!`  I want to have 100 and 100 of `people`, friends, family and `collaborators in same room at once` 🎂

**Comment by miroslavpejic85** [comment]
I `want it too`! 🙂 As for the implementation, I can't tell you exactly how long it will take.
`I'd also like` to create `discussions about` it here.

**Comment by vcdev87** [comment]
H`ow `do you think  I should start to `fix this` right now? 💯 💵

**Comment by miroslavpejic85** [comment]
`Studying` a bit how the `WebRTC` works, the current `mirotalk code`, and looking for `possible` and `best solutions` to get to the `goal`. 🙂 💪

**Comment by vcdev87** [comment]
hi @miroslavpejic85 ! `Thank you very much` 🥮 
What I wan`ted`to know is `can I fix` this ri`ght now`? Maybe 

1. YOU
`2.` Could tell 
3. Me `how I can start to` implement MCU - SFU right now.

This way we will `have bigger ` meetings with more `participants`, and everyone will be happy 🤯 💯 👍 
To me, `teamwork is t`he beauty of _**our sport**_, where you have five acting as `one. You` become selfless. `!!!!`

**Comment by vcdev87** [comment]
1. `Is` this fixed @miroslavpejic85  ?

**Comment by miroslavpejic85** [comment]
No, I'm just collecting some information around concerning the SFU servers...

**Comment by vcdev87** [comment]
@miroslavpejic85  When will this `bugs` be 
2. `Done?` 🚀 

`Timeline?`. OFC i am `contribrutor` and `will help` 🤣 🚀 🎸

**Comment by miroslavpejic85** [comment]
Hi @vcdev87 !
I `remind you` that I also `have a job` (8h x day), on `mirotalk` I put my hand in `free time`! 

The code `is open source`, if you are able to adapt it to an SFU architecture, work on it!, and then let's see the `PR` ... `instead` of asking when it `will be ready`! 

There is no need to specify certain things, the others can see who are you.

And if I can just ask you the `courtesy to not spam too much` with `self-made emoji reactions`.
`Let others interact`. I `hope` you `understand me`. `Thank you so much` and have a nice day.

Regards

**Comment by miroslavpejic85** [comment]
> No, I'm just collecting some information around concerning the available SFU servers...

And I `don't understand` this reaction 👎 ?
Have `respect` for those who `work on open source` in general, and for those `who give you` the opportunity `to use it for free`! 
Doing research etc., it seems to me a `positive thing`, and in `my free time` I try to `improve the project that's all` ;)

**Comment by vcdev87** [comment]
@miroslavpejic85 .

I am `SORRY` for me pushing `too much`. `Sometimes I want` too much. 
I am `very HAPPY` with 
1. you and 
2. contributrotrs on this `project` ❤️

Have a `nice DAY`

**Comment by vcdev87** [comment]
Hi @miroslavpejic85 
`18 days` was last `comment` on `this bug`.  
As promised will `check STATUS on issues` when I have `time`.
Can we 
1. `CONTRIbrurtors`
get `STATUS` update on `this`? 💤 🥇 🙄 🚀 

> Coming together is a beginning. Keeping together is progress. Working together is success.

**Comment by vcdev87** [comment]
@miroslavpejic85 🆘 🆘 `🆘 !!`!! Any `news`? 🥎 I performance `test`ed now and `still not` possible with more then 
1. `5-6` `PEERS` in `same room`!! 🥉 🔢

**Comment by pragmatech** [comment]
Hi,
Thanks for sharing this. I've been slogging through WEBRTC and its challenges for a while and your implementation is really nice (i.e. works well). Fwiw, having a toggle, to sharescreen w/ audio, would open up some nice mutual streaming, I'd think. Anyway, as a caveman dev, I might not be able to offer much; however, it seems that, in the SFU-area, that the Mediasoup server is really backing some of the current robust webrtc implementations.

**Comment by vcdev87** [comment]
Hi @pragmatech , `welcome` 😃 
THANKS for `feedback`. I think `maintainer` 
2. @miroslavpejic85  is no `longer work`ing on this `bug` 🆘 🆘 . And in future `only 3-5` people can `be in same room at ONCE`. But `latency` will be `better with peer to peer ` then SFU at `least` 🎸

**Comment by Jaideep25** [comment]
@vcdev87  May I know from where did you get this `INFORMATION` that @miroslavpejic85  isn't working on this? And it's a feature not a bug for your information....

**Comment by miroslavpejic85** [comment]
Hi @pragmatech. 
I'm very happy you like MiroTalk.
Thanks for the tips! :)

**Comment by vcdev87** [comment]
Hi @Jaideep25 ! You can `SEE` from comment`s above` that `NO` answers is provided by `maintainer on my` requests. `Therefore`
1. I think `progress has stopped`! 🆘 🆘 `🎸` 🤣

**Comment by Jaideep25** [comment]
To see the progress i guess you can see the commits, and their is nothing to laugh! Please don't check on his progress, he's even seeing other problems with RTCDataChannel which I guess you din't see today's commit... Please don't say anything until you don't know.... and I guess if you're behind a person, he/she will ignore you.... Thanks!

**Comment by vcdev87** [comment]
THanks for `clarification` @Jaideep25 ! I appreciate

**Comment by miroslavpejic85** [comment]
Done: https://github.com/miroslavpejic85/mirotalksfu
