### ISSUE TITLE
Error with Microphone and Camera [Deploy mirotlak on Ubuntu Server]

### ISSUE THREAD

**Issue by jrnovak** [miroslavpejic85/mirotalk#36]
Here is the error that I am getting when I try to access Mirotalk via the browser.  https://imgur.com/a/2lChgFH

**Comment by miroslavpejic85** [comment]
Hi @jrnovak welcome! 
Open it on http://localhost:3000 `instead of` http://10.0.1.18:3000
Tell me if something change? 
Thanks

**Comment by jrnovak** [comment]
I have it installed on a Ubuntu Server and I am not able to access it directly via a browser locally.

**Comment by miroslavpejic85** [comment]
The `browser client` is trying `to connect` to `signaling server` that is listen on `localhost:3000`, it's `not` a `problem` of `microphone and camera`.

 Ok `no problem` try this:

- `Create a free account on`:  https://ngrok.com/ 
- Write this on `.env` file:

```bash
 NGROK_ENABLED=true
 NGROK_AUTH_TOKEN=YourNgrokAuthToken
 ```
 
Then after `nom start` in the `terminal logs` you should see something like this:

```bash
[2021-06-13 20:44:15.784] settings {
  http: 'http://localhost:3000',
  https: 'https://873c6b9a6029.ngrok.io',
```
Open your https://.......... link generated in the browser.

**Comment by jrnovak** [comment]
It works!  Thank you so much for your patience in helping me to get it operational.

**Comment by miroslavpejic85** [comment]
U welcome! 😉
