### ISSUE TITLE
White Board not working!!!!

### ISSUE THREAD

**Issue by vcdev87** [miroslavpejic85/mirotalk#39]
When one `user draw` on white board, other users `can not` 
1. see drawing`!`? 

`😱 `

**Comment by Jaideep25** [comment]
Welcome @vcdev87 , if you screenshare, then others can see the whiteboard!
Thanks.

**Comment by vcdev87** [comment]
Welcome also to `you` @Jaideep25 !
This is `BIG `problem that needs solution from contributors ❤️ 
If users cannot collaborate on same white `Board than` they might use `draw.io ` instead of mirotalk!! 😱 🎸 💯

**Comment by miroslavpejic85** [comment]
Hi @vcdev87 
You're right, that's a `first version` of the `whiteboard` (not collaborative at the now), it needs to be finished. 
As @Jaideep25 said, you can use it in this way for now.
I'm also looking at other solutions to improve it even more 😉

**Comment by vcdev87** [comment]
Hi @miroslavpejic85 , welcome to `conversation` :)
Maybe this `can` be solvet w`ith socket.io ?`

**Comment by miroslavpejic85** [comment]
It will be done...

**Comment by vcdev87** [comment]
I want to `thanks very to you` @miroslavpejic85. 
How Can `I help` to fix this `BUG`. ? 🎸

**Comment by miroslavpejic85** [comment]
I'm not the one who has to give you instructions, as I said, try to understand the code, do some tests, improve it, we also have channels [gitter](https://gitter.im/mirotalk/community) to talk about it, feel free to give ideas, respect other ideas too,  talk to others too, and so on ... What @Jaideep25  said (that I respect ❤️) is just an alternative until the whiteboard is completed… ;)

**Comment by vcdev87** [comment]
HI @miroslavpejic85 , thanks `very mcuh ` for answer! 🎧 

Maybe I can start on this to fix this bug once and for `ALL`? Together `we` can do this! 👍 🏅 🚀 🎸

**Comment by miroslavpejic85** [comment]
Before starting changes of any kind, try to understand the current one, feel free to have mirotalk modified, there are `derivative projects` such as: https://github.com/anshuman2166AppproDev/Dogemeet that @anshuman2166AppproDev deployed and i `appreciated` her `sharing`! ❤️

**Comment by vcdev87** [comment]
`Derivative projects` are boring. My `family `is mirotalk! ❤️  I am also mirotalk `contributor` now when my PR mer`ged`! Thank you very much @miroslavpejic85 ! 🚀 🎸 

Do you have tips to become better progra`mmer so I can make` more PR to mirotalk??

**Comment by Jaideep25** [comment]
@vcdev87 , actually it's an amazing site, you can get some better ideas also! Not gonna lie but pls do see how he tried to give a new look to `mirotalk`

**Comment by vcdev87** [comment]
I want more `contribut`ions to `mirotalk`! plz help

**Comment by miroslavpejic85** [comment]
@vcdev87 Let's stay on issue please. 😇
 I'm work to make whiteboard drawing for all user in the same room, will be done asap.

**Comment by vcdev87** [comment]
@miroslavpejic85 How much `duration`? 
And how `can`:

1.  I help `as con`tributor to speed up dur`atìon` ??

`Together we` are strong 💪

**Comment by miroslavpejic85** [comment]
There still needs to be improved, but it should `resolve this issue`: https://github.com/miroslavpejic85/mirotalk/commit/5c1a66e905d5e8b06ffcdb5ec432898822e9b32b ;)
Now, everything you draw is `shared` with `everyone` in the `same room`. 
Regards

**Comment by vcdev87** [comment]
@miroslavpejic85 ok`.`
How I ca`n become` better programmer, any `tips for ` collaborators like my? `🚀 🎸`

**Comment by miroslavpejic85** [comment]
Start taking some online courses for example here: https://www.sololearn.com/
Regards

**Comment by vcdev87** [comment]
`OK` 
1. @miroslavpejic85
