### ISSUE TITLE
a doubt

### ISSUE THREAD

**Issue by joaochris** [miroslavpejic85/mirotalk#4]
On this site you could create something like Skype's NDI or have a solution that can capture participants and we were able to insert it into OBS Studio. It would be very good, because Zoom has not yet developed this feature :(

**Comment by miroslavpejic85** [comment]
Hi joaochris, Welcome!
Thanks for suggestions!
It would be nice to implement also this feature too!

**Comment by miroslavpejic85** [comment]
For the moment I close this task but I have marked it for the future, at the moment there are `other priorities`.
