### ISSUE TITLE
write the whiteboard with pen stylus

### ISSUE THREAD

**Issue by franky-tampubolon** [miroslavpejic85/mirotalk#41]
i use tablet monitor. then i write the whiteboard with pen stylus. the response more slowly than i write the whiteboard with mouse...

**Comment by miroslavpejic85** [comment]
Hi @franky-tampubolon, welcome! 🙂
I don't have a pen stylus and a tablet to try it out 👀, I usually use the mouse on the PC. 
It's slowly even if you `don't have users in the room`?

**Comment by Jaideep25** [comment]
Hey @franky-tampubolon welcome,
1 more question, did the other sites, or apps lag during that time??

**Comment by vcdev87** [comment]
Welcome @franky-tampubolon .
I am con`tributor `at mirotalk. How can I help
1. You?
2. Maybe `some bug i`n your stylus rathen than `MIROTALK`?

Together `we can` solve this ` 🪂 🎸`

**Comment by miroslavpejic85** [comment]
@franky-tampubolon ? 😅

**Comment by franky-tampubolon** [comment]
my english not good....

sorry i'm late to response. I got this problem with or without user joined
in room... i dont know the problem maybe issue about sensitivity of the
whiteboard.

i tried write in pptx, my stylus pen working well.


thank you sir...

Pada tanggal Sel, 22 Jun 2021 05.27, vcdev87 ***@***.***>
menulis:

**Comment by franky-tampubolon** [comment]
> Welcome @franky-tampubolon .
> I am con`tributor `at mirotalk. How can I help
> 
> 1. You?
> 2. Maybe `some bug i`n your stylus rathen than `MIROTALK`?
> 
> Together `we can` solve this ` 🪂 🎸`

sorry i'm late to response. I got this problem with or without user joined
in room... i dont know the problem maybe issue about sensitivity of the
whiteboard.

i tried write in pptx, my stylus pen working well.


thank you sir...
