### ISSUE TITLE
Record Meeting like teams, zoom as webm

### ISSUE THREAD

**Issue by bayrhuusrs** [miroslavpejic85/mirotalk#42]
Please make this program to record all actions. Such as everyone's web camera, audio and screen share.

**Comment by miroslavpejic85** [comment]
Hi @bayrhuusrs, welcome! 
At the now, the `recording` is done on `your own video-audio` stream `due to privacy`. I could `extend the recording` function in the future to `record also the audio of other users in the room` as well, obviously warning them with a popup alert.

**Comment by miroslavpejic85** [comment]
Very interesting! https://github.com/muaz-khan/RecordRTC

**Comment by vcdev87** [comment]
Did yo`u` imple`ment` this`:`
1. https://github.com/muaz-khan/RecordRTC already?? @miroslavpejic85 
Ofc I am
2. `contrirbrutor an`d can `help with` THIS! 🤣 🤣 🚀 🎸 🥇

**Comment by vcdev87** [comment]
@miroslavpejic85 ` 3 PING`? 🤣 🚀

**Comment by miroslavpejic85** [comment]
Hi @vcdev87 hope you well?
Actually not, I'm using MediaRecorder as you can see here:
https://github.com/miroslavpejic85/mirotalk/blob/master/www/js/client.js#L2786
I linked that open source for remainder, because it looks very interesting to me and has a lot more options, 
It looks complete, not hard to integrate and allows you to record whatever you want.

**Comment by vcdev87** [comment]
Hi @miroslavpejic85 , `wel`come 🔥
1. All I would `say` is 
3. if you `need help` I am also `contrirbrutor` and can `help with this` 🙄 🤣 🤣 🙄 🥇 💯 🚀 🎸

**Comment by miroslavpejic85** [comment]
There is **PR** for that ... **Anyone can feel free to contribute**. 
And You keep putting emoji reactions by yourself? 
If you are confused in the previous answer, how can I help you not to be? 
What is it that confuses you? 
And what makes you laugh at that answer?

**Comment by vcdev87** [comment]
`I also` work 8 `hours EVERY DAY` so I CANNOT 
2. `PR` all `features NEEDED!` I as `contrirbrutor in project` need `GUIDANCE AND CLEAR HELP` to `fix bugs`!!!
3. `NO NEED BE ` quasky 
4. 3 .`towards` other `contrir`brutors becasue you are `MAINTAINER!!`

6. But as I `said before MA`NY TIMES `I CAN HELP` with SFU `AND MCU` 🙄 🤣 🤣 👍

**Comment by Jaideep25** [comment]
@vcdev87 Hello!
I guess @miroslavpejic85 just asked you not to keep askin the status about the project.... He has clearly metioned that he'll do when he's free and wants to do... And the 2nd point please don't use unessessary emojis, what is the use of them? Laughing, Spammin reactions to your comment, it clearly looks Awkward please do understand, You even told that you can help with this, now you're tellin that you can't help, decide one option! And am sorry if you felt this rude... But it's even the truth what @miroslavpejic85  is tryin to tell you, and you're not able to understand....

**Comment by miroslavpejic85** [comment]
> `I also` work 8 `hours EVERY DAY` so I CANNOT
> 2. `PR` all `features NEEDED!` I as `contrirbrutor in project` need `GUIDANCE AND CLEAR HELP` to `fix bugs`!!!
> 3. `NO NEED BE ` quasky
> 4. 3 .`towards` other `contrir`brutors becasue you are `MAINTAINER!!`
> 
>     1. But as I `said before MA`NY TIMES `I CAN HELP` with SFU `AND MCU` roll_eyes rofl rofl +1

Hi @vcdev87, If you like, you and others can help me in anything in the project, `feel free`, if you want to try the SFU part (not easy) try to find solutions, and we discuss it here: I created this issue aka discussion [here](https://github.com/miroslavpejic85/mirotalk/issues/35#issue-919771551), on purpose.
Thanks  and have a good day.

**Comment by vcdev87** [comment]
`OK ` @miroslavpejic85 , just let `contrirbrutor  know` if you need `help with project a`nd I can 
7. `fix it` 🙄 🙄  🥇 
You `are RIGHT` @Jaideep25 , 
I WILL try to check in on `status of ISSUES and PR` when I have time, to make `SURE PROGRESS IS FORWARD`  🚀 🎸 BUT `REMEMBER AS SAID` I also `have job `8-10 hours a day as `JANITOR` 💯 👍 👍 💯 🤖

**Comment by miroslavpejic85** [comment]
https://github.com/miroslavpejic85/mirotalk/issues/50#issue-946380809

**Comment by Owned-by-Luce** [comment]
I hope you will make this recording enhancement 👍

**Comment by miroslavpejic85** [comment]
Hi @Owned-by-Luce, yes of course! 
Work in progress ;) I moved this issue here: https://github.com/miroslavpejic85/mirotalk/issues/50#issue-946380809
