### ISSUE TITLE
join room without web camera. 

### ISSUE THREAD

**Issue by bayrhuusrs** [miroslavpejic85/mirotalk#43]
Please make this program to join room without webcam or microphone. If I don't have a camera, I can chat.

**Comment by Jaideep25** [comment]
Hey @bayrhuusrs , actually, without camera is understandable, but without mic why do we even need a video call? We can chat, using other platforms ;) I don't think it would be resonable

**Comment by bayrhuusrs** [comment]
Thanks for response. 
What i want is chat while hearing other people talking each other.

**Comment by miroslavpejic85** [comment]
Hi @bayrhuusrs, welcome!
`Interesting observation`. I'll be thinking about how to make `mirotalk` work even in these conditions 🙂
So `allowing` to using it also `without webcam`, if someone not had it and using all the other features!

**Comment by Panther-42** [comment]
Erm my question is the same... Why we cannot use this very good program without camera? Any other this type of programs(Like zoom, jisti meet, blue button ect) are useable without camera and with microphone and screensharing... Is there a quick workaround for this?(commenting rewriting a few line of code somehow?) :\ I mean it cannot be skipped? It is very puzzling... working well though if i install a fake camera, but, this is just..... erm... "out of ordinary" btw i love this program...

**Comment by miroslavpejic85** [comment]
Hi @Panther-42,  welcome!
I agree with you. It will be implemented. 
Thank you very much.

**Comment by miroslavpejic85** [comment]
Duplicate: https://github.com/miroslavpejic85/mirotalk/issues/59#issue-963320136
