### ISSUE TITLE
Is this `Open` Source

### ISSUE THREAD

**Issue by vcdev87** [miroslavpejic85/mirotalk#44]
hi and `welcome`.
Thanks for `time to` make `this p`roject 🚀 
1. License is `Creative Commons Attribution-NonCommercial 4.0 International Public License`
2. Readme says `Is 100% Free and Open Source`
3. But `your license is **not**` open source ?

READ `THIS` --> https://www.gnu.org/licenses/license-list.en.html#NonFreeDocumentationLicenses

**Comment by miroslavpejic85** [comment]
My mistake, correct. Thanks for the warning.
