### ISSUE TITLE
white board in web browser chrome handphone

### ISSUE THREAD

**Issue by franky-tampubolon** [miroslavpejic85/mirotalk#46]
i try to join a room with handphone browser. The other user try to open whiteboard in the room. And my handphone browser chrome cannot see the whiteboard...

thank you

**Comment by miroslavpejic85** [comment]
Hi @franky-tampubolon, welcome! 
The whiteboard is supported on Desktop devices, only Who have desktop device can see and draw on it. Thanks to you.
