### ISSUE TITLE
Stuck on Webpage Loading

### ISSUE THREAD

**Issue by vaishnav24khaitan** [miroslavpejic85/mirotalk#47]
I have tried this but it's stuck on the webpage of Loading Please allow the camera and microphone to use this app even though the permissions have already been granted.

**Comment by miroslavpejic85** [comment]
Hi @vaishnav24khaitan, welcome!
Probably for some reason the browser cannot connect to the signaling server, please in `your browser` press `F12` and see if there are any errors regarding `connection in socket.io`? Thanks

**Comment by vaishnav24khaitan** [comment]
No there are not any errors regarding socket.io, it's showing init peer is not defined.
