### ISSUE TITLE
Error: port is undefined

### ISSUE THREAD

**Issue by Salamafet** [miroslavpejic85/mirotalk#48]
Hi,

I run mirotalk behind a reverse proxy with docker-compose. 
When I start a meeting, I don't have the video and the sound of the other participant.

In the console of browser, I have this error every 100 milliseconds ~ : Error: port is undefined.

What am I doing wrong ?

**Comment by miroslavpejic85** [comment]
Hi @Salamafet, welcome!
Could you show me the whole error in the console? A screenshot is fine too.
Have you changed the code? 
Thanks.

**Comment by Salamafet** [comment]
Hi and thanks for your time

Here is a screenshot of Firefox Console:
![Firefox_2021-07-05 20-07-18](https://user-images.githubusercontent.com/783351/124506997-23960300-ddcd-11eb-9d15-81108afa55e8.png)

I have modified a bit of HTML and JS for translating a part of mirotalk.

In the docker compose file, I have changed the port binding because Synology services already use this port.
```
ports:
      - "8088:3000"
```
Is the problem here ?

**Comment by miroslavpejic85** [comment]
Ok no problem, try this:
https://github.com/miroslavpejic85/mirotalk/blob/master/server.js#L52
Instead of `3000` change to `8088`
https://github.com/miroslavpejic85/mirotalk/blob/master/www/js/client.js#L69
Instead of `3000` change to `8088`
https://github.com/miroslavpejic85/mirotalk/blob/master/docker-compose.yml#L15
Instead of `3000:3000` change to `8088:8088`

Then rebuild the images
```bash
docker-compose build
Docker-compose up
```

Let me know if ok ;)

**Comment by Salamafet** [comment]
I have already tried to change the port in those files unsuccessfully.

Has explained, I use a reverse proxy. The reverse proxy connects to the container on port 8088 but his listening on port 80/443 (HTTP redirect to HTTPS).

I have tried to redirect the port 8088 directly on the container, but I'm not certain if I can use reverse proxy plus direct.

**Comment by miroslavpejic85** [comment]
And that I haven't tried it in that scenario in order to tell you exactly what the problem may be.  But try again with the changes you made but remember that every change you make to mirotalk stop it rebuilds the image so it takes your changes and run it again.  Let me know if you're stuck yet?

**Comment by Salamafet** [comment]
Still have the error, but it's working now.
I can hear and see other participants.

Thanks :)

**Comment by miroslavpejic85** [comment]
Good news! Thanks to you. ❤️ 
So, network configuration issue.
