### ISSUE TITLE
Allow screensharing while recording

### ISSUE THREAD

**Issue by pravi** [miroslavpejic85/mirotalk#50]
Curretnly we cannot switch between screen sharing and webcam during recordings. Once recording is started I cannot start or stop screensharing (pressing the screen sharing button has not effect). This feature is essential for recording a talk.

**Comment by miroslavpejic85** [comment]
Hi @pravi, thanks for trying **MiroTalk**.
It will be implemented.

**Comment by miroslavpejic85** [comment]
Hi @pravi ;)
You should now be able to select what you want to record, from full screen, to a window etc. including audio. 
Using all the other functions of MiroTalk. Commit: https://github.com/miroslavpejic85/mirotalk/commit/59950567e7d7a625988e4967546c9e756a99b5af

**Comment by pravi** [comment]
@miroslavpejic85 thanks this is nice. One problem still is, I might want to do an introduction with webcam first and then siwtch to screenshare later in the meeting, but currently as soon as you click record, you are forced to share the screen. So now we can't record webcam at all, it always records the screen.

**Comment by miroslavpejic85** [comment]
Hey @pravi
I understand now what you mean, ;) I must see if possible with `MediaRecorder` do something like this: 
Collect more stream (cam-screen) recorded in the Blobs, then merge all them when stop recording, and create only one final video output to save it on device.
But you can do something like this for now:
Start to share the screen and click on your video element in this way he goes on full screen mode, and is like you recording your webcam, do an introduction, then click again on your video to exit from full screen mode, then share what you want on your screen. :)
Thanks to you for use MiroTalk.
