### ISSUE TITLE
MCU - SFU architecture

### ISSUE THREAD

**Issue by miroslavpejic85** [miroslavpejic85/mirotalk#51]
`Mirotalk` not has a `intermediate media server` for audio - video communication, they are `pure peer to peer` connections `between browsers`, therefore it requires a `good Bandwidth - CPU`.

The current `WebRTC Mesh` architecture is not optimal for conferences with `more than 6-8 users` in the `same room`. The quality of the call is inversely proportional to the number of people on the call. The approximative users supported in a single room should be `around 6-8` in an average `high-speed connection`. 

The `goal` is to have a `support media server` and `adapt` the current `architecture` to `MCU` (MultiPoint Control Unit) or `SFU` (Selective Forwarding Unit). To have `more users` connected in the `same room`, consuming `less bandwidth`.

![mirotalk-mesh](https://user-images.githubusercontent.com/70838434/121813880-62251b80-cc6e-11eb-999f-f10e11a14850.png)

**Comment by vcdev87** [comment]
HI @miroslavpejic85 ! Why `you` delete `an`d create `again this issue`?? 
Discussion in `old issue` is 
1. `LOST` and `contribrutors`  will not know what is 
2. `history and status` of this and what `have been discussed` by `mirotalk contribrutors` on this `ISSUE before`? 🆘 🆘 🎸 👎

**Comment by miroslavpejic85** [comment]
A Small preview... `Unlimited users in the same room`...

![mirotalk-sfu](https://user-images.githubusercontent.com/70838434/127736066-6c4d9f23-17b7-4f9a-b829-88e54fd91f8a.gif)

**Comment by miroslavpejic85** [comment]
First release here: https://github.com/miroslavpejic85/mirotalksfu
