### ISSUE TITLE
Node.js simple websocket implementation

### ISSUE THREAD

**Issue by aloproducao** [miroslavpejic85/mirotalk#53]
Hi, Great job!!
I would like help to implement a simple websocket server like the one in steave, I think it's something interesting to have a private server.

https://github.com/steveseguin/websocket_server

Thanks!

**Comment by miroslavpejic85** [comment]
Hi @aloproducao.
Thanks so much, I'm glad you like it. :) 
`MiroTalk` use `RTCDataChannel` for `chat messaging`. 
With RTCDataChannel, all data is secured with Datagram Transport Layer Security (DTLS). 
I don't currently think there is a need for a private server, but thank you anyway. 
Regards
