### ISSUE TITLE
Upgrade to current version

### ISSUE THREAD

**Issue by jrnovak** [miroslavpejic85/mirotalk#54]
I currently have MiroTalk installed an working, I am not certain of what version that I have installed.  I backed up the Mirotalk directory and attempted to install the most current version and I received many errors.  What is the location of the log file?  Is there a simple way to upgrade to the current version without a reinstallation?

**Comment by miroslavpejic85** [comment]
Hi @jrnovak,

Did you deploy it with docker or what? 
And what type of error you have?

- to see client side logs :  press `F12` on your browser
- to see server side logs :  you see it in `real time` when start MiroTalk `npm start`
- if you use docker, you can run it with `docker compose up` and also see the log in real time...

Thanks
