### ISSUE TITLE
How is file getting transfered

### ISSUE THREAD

**Issue by raghavkh2710** [miroslavpejic85/mirotalk#55]

**Comment by miroslavpejic85** [comment]
Hi @raghavkh2710, welcome ;)
For File Sharing, we're using WebRTC's [RTCDataChannel](https://developer.mozilla.org/en-US/docs/Web/API/RTCDataChannel) to transfer data directly from one peer to another. With RTCDataChannel, all data is secured with [Datagram Transport Layer Security](https://en.wikipedia.org/wiki/Datagram_Transport_Layer_Security) (DTLS). DTLS is a derivative of SSL, meaning your data will be as secure as using any standard SSL-based connection.
