### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by Shaileshsaravanan** [miroslavpejic85/mirotalk#57]
Even after allowing audio and video permission, it shows Permission denied, Maybe it is a problem on my side can you please help me email -shaileshsaravanan385@gmail.com

**Comment by Jaideep25** [comment]
Hey @Shaileshsaravanan  Could you please send a screenshot of the error?

**Comment by miroslavpejic85** [comment]
Hi @Shaileshsaravanan, welcome! 
as @Jaideep25 said, could you please report here the error you have, and in what OS - Browser?
Remember that actually you need to have both cam and the microphone on your device,  and  take a look also of this: https://blog.addpipe.com/common-getusermedia-errors/ if solves you issue?
Thanks
