### ISSUE TITLE
Screen share and whiteboard button is not visible

### ISSUE THREAD

**Issue by Sanyam2007** [miroslavpejic85/mirotalk#58]
The screen share and whiteboard button is not visible in the meeting
I have seen this in demo 
I am using Android and my browser is chrome

**Comment by Jaideep25** [comment]
Hey @Sanyam2007  ;) Actually the whiteboard and screen share buttons are disabled in mobile devices, because of compatibility problems, and whiteboard... if someone writes on it... it wont be visible for you because of the canvas....

**Comment by miroslavpejic85** [comment]
Hi @Sanyam2007, welcome!

- `getDisplayMedia()` is not supported on mobile devices, This is a `limitation` of the `API itself`, not MiroTalk.
- `whiteboard` is not supported on mobile devices. 

For any other doubt, we are available.
Regards

**Comment by miroslavpejic85** [comment]
Whiteboard is now supported also on mobile devices thanks to fabricjs. https://github.com/miroslavpejic85/mirotalk/issues/69
