### ISSUE TITLE
Request regarding camera/mic access.

### ISSUE THREAD

**Issue by DillFrescott** [miroslavpejic85/mirotalk#59]
It would be great if you were able to join mirotalk without a camera. I mainly just use microphone and screen sharing with my friends.

**Comment by miroslavpejic85** [comment]
Hi @DillFrescott, I agree with you. 
It will be implemented.
Regards

**Comment by sandro2205** [comment]
Hi @miroslavpejic85 
I think this is possible when using connection.dontAttachStream = true; from RTCMultiConnection.js
https://www.webrtc-experiment.com/RTCMultiConnection/join-with-or-without-camera.html

**Comment by miroslavpejic85** [comment]
Hi @sandro2205, 
Thanks, but MiroTalk-P2P not using  that lib.
Anyway the access without webcam - audio now is possible on MiroTalk-SFU version:
https://github.com/miroslavpejic85/mirotalksfu

**Comment by miroslavpejic85** [comment]
Joining room without webcam now is possible also on MiroTalk P2P: https://github.com/miroslavpejic85/mirotalk/commit/dc51c1c8d9b82ab81f893aab20de62d29fd44a19

![mirotalk-p2p-no-webcam](https://user-images.githubusercontent.com/70838434/178135804-49122251-3f63-47b6-914b-6ed6aaaba627.png)

**Comment by yezhenhuitony** [comment]
Hi   miroslavpejic85 
   I tested versions: Jul 10, 2022, and the latest version. If the computer does not have WEBCAM, it cannot enter the room. 
 The prompt is as follows:
![image](https://user-images.githubusercontent.com/95296844/226308550-e777369a-5b34-49d1-99e7-e0c199c24d45.png)
![image](https://user-images.githubusercontent.com/95296844/226309061-3eb2a496-0276-4ba4-8f6b-92910fcce134.png)
I would be grateful if you could help me solve this problem
