### ISSUE TITLE
Few problems

### ISSUE THREAD

**Issue by shrisha108** [miroslavpejic85/mirotalk#61]
Hi Miroslav. thanks for nice work!
Just want to report few issues that I en counted. First is that  on your demo website "https://mirotalk.up.railway.app/newcall" I wasn't able to connect even for one to one. Each persont can see and hear only themselves. Seems like signaling server issue. Here is a console log from Firefox:

```
WebRTC: ICE failed, your TURN server appears to be broken, see about:webrtc for more details
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at data:text/plain;base64,Cg==. (Reason: CORS request not http).
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://googleads.g.doubleclick.net/pagead/id. (Reason: CORS request did not succeed)
```

Tried with Google Chrome and errors are different but some result. I'm on Fedora 34 if it is matter.

And second thing is that I tried to install mirotalk on Oracle VM with Ubuntu 18.04 and got this:

```
root@shrisha:~/mirotalk# npm install
npm ERR! Linux 5.4.0-1052-oracle
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>
WARN engine dotenv@10.0.0: wanted: {"node":">=10"} (current: {"node":"8.10.0","npm":"3.5.2"})
WARN engine ngrok@4.1.0: wanted: {"node":">=10.19.0"} (current: {"node":"8.10.0","npm":"3.5.2"})

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/mirotalk/npm-debug.log
```
Is npm is too old?

Thank you.

**Comment by Jaideep25** [comment]
Hey @shrisha108  welcome!
Could you please type npm -v && node -v and show the result? And please do try installing ngrok and try again! Thanks!

**Comment by shrisha108** [comment]
Thanks for quick replay!
Installed ngrok didn't make any difference. Here is the result of npm -v && node -v
3.5.2
v8.10.0

**Comment by Jaideep25** [comment]
@shrisha108  please do uninstall node, restart your system, and install it again! It's the problem with the node version... And after you do that please type `npm install -g npm@latest` in a `ADMINISTRATOR CMD` and check if it works!
Thanks

**Comment by miroslavpejic85** [comment]
Hi @shrisha108, welcome!
Thanks @Jaideep25 ;) Just Try with node [12.X](https://nodejs.org/en/blog/release/v12.22.1/) or `14.X` and update also the `npm`. 
Regarding The first question, You have the same problem also here: https://mirotalk.herokuapp.com/newcall ?

**Comment by shrisha108** [comment]
@miroslavpejic85 Thank you, yes that's did the trick. Mirotalk is installed and running. Now I have to configure nginx for having access from internet. I have installed on secure server with registered domain.
Regarding first question, yes same problem is there. That's why I decide to try on my server since I have turnserver running there. To try if I will fix it with my turnserver if it's google faults. For this I have to edit Mirotalk configuration, right?

**Comment by miroslavpejic85** [comment]
U welcome ;)

```bash
cp .env.template .env

# then edit on .env this part

TURN_ENABLED=true
TURN_URLS=YourTurnUrl
TURN_USERNAME=YourTurnUsername
TURN_PASSWORD=YourTurnPassword
```
To test if your Turn Server is configured correctly, try [this](https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/)

**Comment by shrisha108** [comment]
@miroslavpejic85 
Ok, just tried. Same thing :( Log attached.
[connection_log.txt](https://github.com/miroslavpejic85/mirotalk/files/6975885/connection_log.txt)

**Comment by Jaideep25** [comment]
Hey @shrisha108  did you update npm and node ?

**Comment by shrisha108** [comment]
@Jaideep25 Yes I did and it installed smoothly.
@miroslavpejic85 Is it can be because I'm on Linux and some ports should be opened?

**Comment by Jaideep25** [comment]
@shrisha108  umm, maybe cuz of Linux, port 3000 should be open....

**Comment by miroslavpejic85** [comment]
Hey @shrisha108 
I'm also using MiroTalk on Linux, but not able for now reproduce this issue, :) 
But yes, you can try to `allow all traffic` and see if something change? 
Let me know ;)

**Comment by shrisha108** [comment]
Hi Miroslav. So I fully disabled firewall on my system and still no video or audio is going through. I can see that another person is joined but that's it, nothing else.

**Comment by Jaideep25** [comment]
Hey @shrisha108  please do connect both of them on 2 different networks and try, or better connect one on hotspot other on wifi and please do confirm if the problem persists! Thanks!
Regards!

**Comment by shrisha108** [comment]
@Jaideep25 Yes thats what I'm doing. My computer connected through lan to internet my friend connecting his phone through 4G mobile network. But we are not able to see or hear each other.

**Comment by shrisha108** [comment]
Ok, I just tried with my macbook and it's worked. Weird. So that's probably my Fedora is causing it even with firewall fully disabled.

**Comment by shrisha108** [comment]
@miroslavpejic85 Miroslav, which distro you are on?

**Comment by miroslavpejic85** [comment]
Hi @shrisha108 :)
I tested it on Mobile `Android - iPhone` and on PC `Mac-Linux-Windows 10-11` with all browsers and seems ok :) 
`On Fedora never`, try also to update browser to the latest version. And look, if something changes?
But why do you need to use it on Fedora? Maybe Install an Ubuntu Linux distribution ... In your case, it could be something related to some network configuration ...

**Comment by shrisha108** [comment]
I can't. I'm 3D artist and all my soft is for RPM based systems. Red Hat, Centos, Fedora. etc. But I'll investigate what causing this problem. I tried in both Chrome 92.0.4515.159 and firefox 91.0, which is latest versions. So problem some where else.

**Comment by miroslavpejic85** [comment]
Ok no problem. Tell me what version of fedora you have? Workstation, CoreOS? 
I will install it in my VM to see if I have the same issues as you.

**Comment by shrisha108** [comment]
Fedora 34. Also just for experiment sake I installed Red Hat 8.4 this morning and tried there with firewall off. Result is the same. :(

**Comment by miroslavpejic85** [comment]
@shrisha108 on Discord now you will be able to read... ;)
Regarding Fedora 34, I Just installed and tested it for you. 
In my case, I installed the latest chrome and test MiroTalk on Railway between Fedora and my Mac, and seems all ok. 

Chrome

<img width="1202" alt="fedora-chrome" src="https://user-images.githubusercontent.com/70838434/130649227-7b365df7-2f7d-40e7-9f37-2e77ecb450ec.png">

Mac-Fedora

<img width="1608" alt="mirotalk-mac-fedora" src="https://user-images.githubusercontent.com/70838434/130649313-923d833e-753e-4465-9ae7-a313ad0fdb75.png">

Also, when enable the cam, I see correctly and audio seems ok.

**Comment by shrisha108** [comment]
Thank you so much for spending your time for this. Yes I can connect and talk as well but problem is with video. We cannot see each other only hear. Me and my friend only can see our-selfs but not each other.

**Comment by miroslavpejic85** [comment]
Then:

- You have Fedora with the latest version of chrome [92.0.4515.159 (Official Build) (64bit)] like mine, right? 
- What OS do your friends have and browser version?

Try doing some cross-testing with different browsers (`important must be updated to last version`) and see if the problem persists. Something like this:

|  BROWSERS     | CHROME   | FIREFOX  |  OPERA   |
|---------------|----------|----------|----------|
| `CHROME`      | OK/KO    | OK/KO    | OK/KO    |
| `FIREFOX`     | OK/KO    | OK/KO    | OK/KO    |
| `OPERA`       | OK/KO    | OK/KO    | OK/KO    |

What I tested for you is this

|  BROWSERS     | CHROME   |
|---------------|----------|
| `CHROME`      | OK       |

Where 

|  BROWSERS     |  VERSION                                | OS                    		|
|---------------|-----------------------------------------|----------------------------------|
| `CHROME`      | 92.0.4515.159 (Official Build) (x86_64) | macOS Big Sure 11.5.2 		|
| `CHROME`      | 92.0.4515.159 (Official Build) (64 bit) | Fedora 34 (Workstation Edition) 	|

...

Don't worry, thanks to you ;)
