### ISSUE TITLE
Testing in windows 10 , chrome and firefox 

### ISSUE THREAD

**Issue by 0xDante** [miroslavpejic85/mirotalk#62]
i'm testing this application in **WINDOWS 10**  ,  and i got this error **Cross-Origin Request** in firefox browser and **Failed to load resource: net::ERR_CERT_AUTHORITY_INVALID** in Chrome browser so how can we fix it ? and thanks in advance 
the first screen in firefox browser , the second screen in chrome browser 
![Capturefirefox](https://user-images.githubusercontent.com/88215410/129150551-da6f3336-6103-4545-8167-a2178f64f00f.PNG)
![Capturechrome](https://user-images.githubusercontent.com/88215410/129150682-05e57b4a-0baa-47eb-9d04-594d82293d78.PNG)

**ps i followed this documentation :** 
# clone this repo
git clone https://github.com/miroslavpejic85/mirotalk.git

# mirotalk dir
cd mirotalk

# copy .env.template to .env
cp .env.template .env

# install dependencies
npm install

# start the server
npm start

**Comment by Jaideep25** [comment]
Hey @0xDante  which site you're getting this error? And please do confirm that your browser is up-to-date!

**Comment by 0xDante** [comment]
hi can i contact you in google meet to demonstrate you the problemes

**Comment by 0xDante** [comment]
this is my email saadkingj5@gmail.com

**Comment by Jaideep25** [comment]
I guess we chatting here can solve it, no need for a call.... 😅

**Comment by miroslavpejic85** [comment]
Hi @0xDante, 
I just tried now on Windows 10 for you:

```bash
firefox version: 91.0
chrome version: 92.0.4515.131
node version: v14.16.1
npm version: 6.14.12
```
Seems all ok.

As @Jaideep25 said, make sure to have browsers updated and also the node must be 12.X or 14.X not higher versions.

**Comment by 0xDante** [comment]
i have the latest version of chrome and firefox , i uploaded the application in heroku it works good (show me **the authorization for activating the camera and mic**) but when i run it locally it's show me nothing : **this picture in heroku** 
![heroku](https://user-images.githubusercontent.com/88215410/129157274-d076120c-130a-41dc-8406-c64f16bdad56.PNG)
and the second picture of **my local host** 
![Capture22](https://user-images.githubusercontent.com/88215410/129157458-8f1c3a04-f935-4084-a281-590a3e1d8e89.PNG)
the same problem for edge navigator

**Comment by 0xDante** [comment]
ps: I launched it in windows 10

**Comment by miroslavpejic85** [comment]
I also to test it for you on my VM.

But in my case:

`firefox`

<img width="1380" alt="firefox" src="https://user-images.githubusercontent.com/70838434/129161792-5e168ab4-e73c-407f-b683-a7cd2905e209.png">

`chrome`

<img width="1000" alt="chrome" src="https://user-images.githubusercontent.com/70838434/129161840-d6fb3f47-e495-43a1-ba66-5fde77869050.png">

Try to check also this: https://github.com/miroslavpejic85/mirotalk/issues/13#issuecomment-830136119

**Comment by 0xDante** [comment]
the main problem i think is in Access-Control-Allow-Origin 
![allow](https://user-images.githubusercontent.com/88215410/129167113-45ae909d-5d2b-4e50-b204-33cabdc8bd4c.PNG)

**Comment by miroslavpejic85** [comment]
Just for test, can you try this:

Add this line on `package.json` in `dependencies`

```bash
        "cors": "^2.8.5",
```

On `server.js` add these 2 lines and restart it.

```
const cors = require('cors');
app.use(cors());
```

In this way in theory I `Enable All CORS Requests`...

Let me know if solve the problem?
Thanks

**Comment by 0xDante** [comment]
I did what you told me but it didn't work

**Comment by miroslavpejic85** [comment]
Very Strange O.o
Read also this: https://www.section.io/engineering-education/how-to-use-cors-in-nodejs-with-express/
Anyway, I made a commit, try again now.

**Comment by 0xDante** [comment]
I test it in my new windows 10 vm also the same problem as you can see in the first comment , the problem only in localhost but when i passed it on line to heroku it works perfectly good in all the browser 
And thanks in advance

**Comment by miroslavpejic85** [comment]
Change this `127.0.0.1` with `localhost` so
http://localhost:3000 instead of http://127.0.0.1:3000

**Comment by 0xDante** [comment]
it's work finally thank you so much for your help so , i have just a simple question how many person  can connect to this app

**Comment by 0xDante** [comment]
and if a user share a file or a image where can we find it ??

**Comment by miroslavpejic85** [comment]
How many users can handle in a single room MiroTalk read [this](https://github.com/miroslavpejic85/mirotalk/issues/51) I’m also working for the MiroTalk SFU version with no users limits in the room :) Regarding the File Sharing is sent from your Device PC-Mobile by SECURE [RTCDataChannal](https://developer.mozilla.org/en-US/docs/Web/API/RTCDataChannel) between browsers (p2p) and saved on partecipants browsers in the [Blob](https://developer.mozilla.org/en-US/docs/Web/API/Blob) When they receive a file can save it from they Blob to the Device or discard. For any others question l’m available. Thanks to using MiroTalk and have a nice day. 
Regards
