### ISSUE TITLE
Please make button to see all the meeting participants list

### ISSUE THREAD

**Issue by Sanyam2007** [miroslavpejic85/mirotalk#63]
Please make a button to see all the participants list

**Comment by miroslavpejic85** [comment]
Hi @Sanyam2007,
In chat, You can see all participants in the room by clicking this button

<img width="47" alt="participants" src="https://user-images.githubusercontent.com/70838434/129733832-e170f51e-c81c-4ab2-8aca-ab92adf6afb7.png">

It's used to send `private message` to them, but here you have also the `lists` of `all participants`. 
Here you have also the `search`, to `find` specified participant `by name`.
