### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by Dibyayan8992** [miroslavpejic85/mirotalk#64]
Hi, Please Help Me. I Am Facing A Problem That When I Downloaded The Mirotalk Zip File After Download I Have Extracted And Opening That Extracted File In Web Server 200 OK And Running It On Microsoft Edge When I Put A New Meeting URL Then It Is Showing File Does Not Exist... Please Help Me Or Give Me The Full Source Code Please...

**Comment by Jaideep25** [comment]
Hey @Dibyayan8992  you need node.js for this, web server wont work for this....

**Comment by Dibyayan8992** [comment]
> Hey @Dibyayan8992 you need node.js for this, web server wont work for this....

So Please Tell Me The Steps Or Please Send Me The Video....

**Comment by Jaideep25** [comment]
Umm the readme.md tells what are the requirements ;)

**Comment by miroslavpejic85** [comment]
Hi @Dibyayan8992, 
As @Jaideep25  said, In order to make it works, You need to deploy it on hosts that support node.js. 
Regards
