### ISSUE TITLE
Voice not in sync with audio

### ISSUE THREAD

**Issue by ioscanner** [miroslavpejic85/mirotalk#66]
So far great product!

Is there a way to sync the video and audio better?  It is off enough that it is very noticeable.  I am on 1G internet so bandwidth is not an issue.

**Comment by miroslavpejic85** [comment]
Hi @ioscanner, thanks.

The current `WebRTC Mesh` architecture `is not optimal` for conferences with more than `4-5 users` in the `same room`. The quality of the call is inversely proportional to the number of people on the call, therefore it requires all peers to have good bandwidth and CPU, not just you.

![image](https://user-images.githubusercontent.com/70838434/131634380-6f8800ea-1207-48d6-a539-33ca8d3d7654.png)

I also released the `first version` of `MiroTalk SFU`, more details [here](https://github.com/miroslavpejic85/mirotalksfu) 
Which should be able to handle `large numbers of users` in the `single room` based on the power of the host you run it on ...

![image](https://user-images.githubusercontent.com/70838434/131634721-112f0fa2-b6cf-42c0-914c-077219705ae0.png)

Regards

**Comment by ioscanner** [comment]
Thanks.  I was just using two devices iPad Pro and Mac.  I will try the SFU version.  I am sure that will help.

**Comment by miroslavpejic85** [comment]
Sure. You are welcome and thanks for use the MiroTalk.
