### ISSUE TITLE
White board not working on iOS

### ISSUE THREAD

**Issue by ioscanner** [miroslavpejic85/mirotalk#67]
The whiteboard doesn’t work on iOS devices.  I see the whiteboard, but can’t write in the box.  It works on chrome on windows 10 and Mac in Safari and chrome.  Would be nice to use apple pen to draw on the white board

**Comment by ioscanner** [comment]
Ok seems with iPad You can use the magic keyboard, but not the touch screen or apple pen.

**Comment by miroslavpejic85** [comment]
Hi @ioscanner,
I'm sorry, I have no way to test it, You can try to modify the [canvas](https://github.com/miroslavpejic85/mirotalk/blob/master/www/js/client.js#L4033) draw part of the whiteboard, in order to handle not only the [mousemove](https://github.com/miroslavpejic85/mirotalk/blob/master/www/js/client.js#L4041) events ...

**Comment by ioscanner** [comment]
It would be the same for iPhone.  It doesn’t detect finger drag to draw as input.  I am not sure what event is need for the touch input.  I am willing to give it a try and test so we can patch.

**Comment by miroslavpejic85** [comment]
Would be great. Update me on progress.
Thanks

**Comment by miroslavpejic85** [comment]
Hi @ioscanner, With this whiteboard settings you will be able to handle also the touch event ;)
```js
function setupCanvas() {
    
    ...
    
    // whiteboard touch listeners
    canvas.addEventListener( 'touchstart', touchStart);
    canvas.addEventListener( 'touchmove', touchMove);
    canvas.addEventListener( 'touchend', touchEnd);
    
    function touchStart(e) {
        x = e.touches[0].pageX;
        y = e.touches[0].pageY;
        isDrawing = true;
    };
    
    function touchMove(e){
        if (!isDrawing) return;

        draw(e.touches[0].pageX, e.touches[0].pageY, x, y);
        // send draw to other peers in the room
        if (thereIsPeerConnections()) {
            sendToServer('wb', {
                room_id: roomId,
                peer_name: myPeerName,
                act: 'draw',
                newx: e.offsetX,
                newy: e.offsetY,
                prevx: x,
                prevy: y,
                color: color,
                size: drawsize,
            });
        }
        x = e.touches[0].pageX;
        y = e.touches[0].pageY;
    };
    
    function touchEnd(e){
        if (isDrawing) isDrawing = false;
    };
}
```

**Comment by miroslavpejic85** [comment]
Done: Added whiteboard support on touch screen : https://github.com/miroslavpejic85/mirotalk/commit/5ffcd64b45ddb1d504bff8a28f79f1b453cfd528 www/client.js

**Comment by ioscanner** [comment]
Sorry I moved over to the SFU version.  The audio sync was off enough It was annoying.  The SFU version is working great now that you patched the iOS video issue.

I tested the Whiteboard and it works perfect in Safari, but doesn't show up in Chrome on iOS devices.  Can you add this to the SFU version?

**Comment by miroslavpejic85** [comment]
Whiteboard is not supported on mobile devices.

**Comment by miroslavpejic85** [comment]
Now is supported also on mobile done: https://github.com/miroslavpejic85/mirotalk/issues/69
