### ISSUE TITLE
Can't hear audio and see video of other person

### ISSUE THREAD

**Issue by Jaideep25** [miroslavpejic85/mirotalk#7]
Hi! I tried to connect using 2 different browsers I wasn't able to hear or see the other person

**Comment by miroslavpejic85** [comment]
Hi @Jaideep25, welcome!

- Could you tell me the browsers in question?
- Are updated to the latest version?
- And what is your OS?

Thanks

**Comment by Jaideep25** [comment]
Hi @miroslavpejic85 !
 
- The browsers are Edge and Chrome
- They are updated to the latest version!
- OS of both laptops is Windows 10 OS Build of both the laptops are 19042.928
- And a question did you try to run on 2 laptops and try?

**Comment by Jaideep25** [comment]
1 more problem; When I click on the other person's video (which isn't comming for me) It shows this
![image](https://user-images.githubusercontent.com/67269475/115993690-857a0580-a5f1-11eb-9438-58eee79ab2e4.png)

**Comment by miroslavpejic85** [comment]
Can you try running this WebRTC [demo](https://webrtc.github.io/samples/src/content/getusermedia/gum/)
see if that is able to successfully access your camera and microphone?
I'm guessing that the browser is not able to detect your media devices (video) for some reason.

Take a look also on this if can solve your problem: 
- [camera-doesn-t-work-in-windows-10](https://support.microsoft.com/en-us/windows/camera-doesn-t-work-in-windows-10-32adb016-b29c-a928-0073-53d31da0dad5#:~:text=When%20your%20camera%20isn't,app%20you%20want%20to%20use)

Regards

**Comment by Jaideep25** [comment]
I can run the demo too... And Gimme sometime, I'll check using [common-getusermedia-errors](https://blog.addpipe.com/common-getusermedia-errors/) this! Thank you for your concern! And  did you try to use 2 laptops and try it?
Waiting for your reply!

**Comment by anshuman2166AppproDev** [comment]
I tried on Opera, Safari, Chrome and Edge but, it worked like a charm. Maybe you must check your internet connection 
Regards

**Comment by Jaideep25** [comment]
@anshuman2166AppproDev  did you try with 2 different laptops?? Or 2 different browsers?

**Comment by Jaideep25** [comment]
This is the error
![image](https://user-images.githubusercontent.com/67269475/116033976-10a1dc80-a680-11eb-8759-f54e3c025a6c.png)
![image](https://user-images.githubusercontent.com/67269475/116033991-17305400-a680-11eb-9833-30662dc92bec.png)

**Comment by Jaideep25** [comment]
When I did a call with my friends they could see each other, but I couldn't....

**Comment by anshuman2166AppproDev** [comment]
Is this the modified code by you ? Or the code as it doesn't is ?

Did u tested at mirotalk.herokuapp.com

**Comment by Jaideep25** [comment]
The code isn't modified

**Comment by Jaideep25** [comment]
Hi! Now the program is running good, I found out their was a problem with my other laptop.... and a doubt, when u share the screen and then the video gets turned on why is that, and when u stop sharing u can see urself...?

**Comment by miroslavpejic85** [comment]
Hi @Jaideep25, Good news :)
Can you explain what was the problem on your laptop?
Thanks

**Comment by Jaideep25** [comment]
I'll need to find out! Once I do will tell!
And why does the video turn on when you screenshare?

**Comment by miroslavpejic85** [comment]
@Jaideep25,
Ok, no problem.
Fixed: https://github.com/miroslavpejic85/mirotalk/commit/ba8daa9760c07c6c9e8fe123df7e71d5f08a7bbc

**Comment by Jaideep25** [comment]
Oh amazing thanks a lot, so... You'll close the issue?

**Comment by Jaideep25** [comment]
@anshuman2166AppproDev @miroslavpejic85  another error....
![image](https://user-images.githubusercontent.com/67269475/116803414-13e01100-ab35-11eb-9892-f8da1d62d0fd.png)
As you can see, when you erase the whiteboard the white color comes... not the board's original colour...

**Comment by miroslavpejic85** [comment]
whiteboard eraser fixed thanks for report it: https://github.com/miroslavpejic85/mirotalk/commit/756198e4501e454bb45b6379df8bf326afe3787f

**Comment by miroslavpejic85** [comment]
Regarding the webcam after screen sharing, ok i now understand what you means.
You not want cam on if you before the screen sharing you disabled it.

**Comment by Jaideep25** [comment]
> Regarding the webcam after screen sharing, ok i now understand what you means.
> You not want cam on if you before the screen sharing you disabled it.

I din't get you...
Sorry.

**Comment by Jaideep25** [comment]
> whiteboard eraser fixed thanks for report it: [756198e](https://github.com/miroslavpejic85/mirotalk/commit/756198e4501e454bb45b6379df8bf326afe3787f)

Thanks!

**Comment by miroslavpejic85** [comment]
> Actually that's happening now also... I just tried it, I turned off my cam, started sharing the screen, and when I stop sharing my cam is on...
I understood the problem with this explanation :)

**Comment by Jaideep25** [comment]
> > Actually that's happening now also... I just tried it, I turned off my cam, started sharing the screen, and when I stop sharing my cam is on...
> 
> I understood the problem with this explanation :)

Oh thanks!

**Comment by Jaideep25** [comment]
@miroslavpejic85  just thought that, if you added a border around the vid when the hand is raised it would look much better because, if someone's background is green and then when you raise your hand it won't be so noticeable, so I just thought, if you want you can implement it!

**Comment by miroslavpejic85** [comment]
Ok, but I go to close this issue, as the initial problem is already self-solved.
You can open others for any bugs or correction to be made as this last. For example
issue:  whiteboard eraser color (already solved here) 
and soo on.
Thanks you so much for the support.

**Comment by Jaideep25** [comment]
Ok! Thanks!
