### ISSUE TITLE
Same Network Room Join Freezes Loading ...

### ISSUE THREAD

**Issue by yassinemaalejchtr** [miroslavpejic85/mirotalk#71]
<img width="811" alt="Screen Shot 2021-10-13 at 1 35 57 PM" src="https://user-images.githubusercontent.com/77020230/137201424-f3692b32-54d3-42b9-a309-0a20be15fd6c.png">

How do I join another room in the same network with getting stuck in the Loading ...

**Comment by Jaideep25** [comment]
Hello @yassinemaalejchtr ! If possible could you share the logs? :)
Thanks!
