### ISSUE TITLE
Erase tool on whiteboard lock mouse cursor to not-allowed

### ISSUE THREAD

**Issue by sandro2205** [miroslavpejic85/mirotalk#74]
On the whiteboard, after selecting the erase tool, the mouse cursor remains as "not-allowed" when you select the arrow tool (object mode).
The solution is to add an else statement in the MouseMove function, in the client.js file, e.g.:

function mouseMove() {
    if (wbIsEraser) {
        wbCanvas.hoverCursor = 'not-allowed';
        return;
    }
	else {
		wbCanvas.hoverCursor = 'move';
	}
    if (!wbIsDrawing) return;
}

This worked for me.

**Comment by miroslavpejic85** [comment]
Hey @sandro2205, 
You're right, thank you very much. 
Do you want to do a PR, or do I correct it on the fly by appointing you in the commit?

![fix-whiteboard](https://user-images.githubusercontent.com/70838434/139927540-b19d1ae5-96bc-4a71-ada4-0160874cfe73.png)

Thanks

**Comment by sandro2205** [comment]
> Hey @sandro2205, You're right, thank you very much. Do you want to do a PR, or do I correct it on the fly by appointing you in the commit?
> 
> ![fix-whiteboard](https://user-images.githubusercontent.com/70838434/139927540-b19d1ae5-96bc-4a71-ada4-0160874cfe73.png)
> 
> Thanks

Hi @miroslavpejic85 , as you wish. 👌

**Comment by miroslavpejic85** [comment]
Hello @sandro2205,
If you want to give me a PR with this fix, in this way you will be also part of contributors ;) 
No matter how much code you do etc., you have found the small bug :)
Let me know what you prefer. 
Anyway thanks

**Comment by miroslavpejic85** [comment]
Thanks to **sandro2205** done: https://github.com/miroslavpejic85/mirotalk/commit/8628a9ead3bb43365072c8705d83848d3711cf79
