### ISSUE TITLE
Whiteboard behavior

### ISSUE THREAD

**Issue by jegueer** [miroslavpejic85/mirotalk#79]
Hello!
Right now, the whiteboard does not open to other participants unless the user who opened it draws something on the canvas. Is there a way to change this behavior so that everyone sees the whiteboard as soon as somebody opens it, even if it's an empty canvas? I tried coding my own "open whiteboard" action, but it was not showing for the user who opened it.
Thanks!

**Comment by miroslavpejic85** [comment]
@jegueer done: https://github.com/miroslavpejic85/mirotalk/commit/04ec05680dcff23950acd78b1989fa02d3566bf2

**Comment by jegueer** [comment]
Thanks! I will test the new whiteboard behavior and let you know.

**Comment by jegueer** [comment]
Hello again.
Now the whiteboard behaves as expected. Thank you very much.

**Comment by miroslavpejic85** [comment]
Good, You are welcome.
