### ISSUE TITLE
Adding Raise Hand feature using some backend code of socket.io

### ISSUE THREAD

**Issue by anshuman2166AppproDev** [miroslavpejic85/mirotalk#8]
Hello @miroslavpejic85 your project is really awesome. I suggest you to add a raise hand option as it is present in most of new video calling apps. BTW I am coming soon with a pull request adding a whiteboard in it. Hope this project will bring the fire

**Comment by miroslavpejic85** [comment]
Hello @anshuman2166AppproDev, Welcome and Thank you so much!
Aha, Ok i will add also the raising of the hand ;)
Any pull request are welcome to improve it.
Thanks for contribution!

**Comment by anshuman2166AppproDev** [comment]
Ok sir, whiteboard pull request is coming soon too 😁

**Comment by anshuman2166AppproDev** [comment]
Whiteboard done @miroslavpejic85 😊 now making a modal

**Comment by miroslavpejic85** [comment]
@anshuman2166AppproDev implemented: https://github.com/miroslavpejic85/mirotalk/commit/a379a3da31a3ccb80e99b1929a1d1ca0e1cae176

**Comment by anshuman2166AppproDev** [comment]
Thank you sir u are epic
