### ISSUE TITLE
Ability to add custom data about peers

### ISSUE THREAD

**Issue by jegueer** [miroslavpejic85/mirotalk#80]
Hello!
I need to modify Mirotalk so that users have roles, which will–either by CSS or JS–change the UI and other functionality based on the user's role. I am using the localStorage API so that I can set some persisting information about the peer before the call starts. However, that information is not accessible to other peers and I am struggling to come up with the logic to implement a way to let everyone know each other's roles that doesn't require using a database.
Is there a way to implement roles, such as hosts, co-hosts, etc. using the current code base of Mirotalk?
Thanks!

**Comment by miroslavpejic85** [comment]
Currently, there are no roles, everyone is free to share the webcam, audio, screen, whiteboard, files etc. These,  that you ask me, are personal customizations. Thanks for understanding.
