### ISSUE TITLE
turn server

### ISSUE THREAD

**Issue by dotnethii** [miroslavpejic85/mirotalk#82]
thanks for good source.
Turn server cannot run.

**Comment by miroslavpejic85** [comment]
Hello @dotnethii, you are welcome.
Could you please explain in detail what problem you encountered ?
For the Turn part, follow this:
 - cp .env.template .env
 - Then [Setup your Turn server](https://github.com/miroslavpejic85/mirotalk/blob/master/.env.template#L9)
 Regards

**Comment by dotnethii** [comment]
I enter 3 types of Turn server accounts but it does not work in the program.
iceServers.push({

    //    urls: turnUrls,
    //    username: turnUsername,
    //    credential: turnCredential,
          urls: 'turn:numb.viagenie.ca',
       username: 'username',
        credential: 'password',
        //   urls: 'turn:134.209.28.98:3478',
        //   credential: 'te8V62xqLQ2GOEibYHCsRBnNE6M=',
        //    username: 'anyass'
    });

**Comment by miroslavpejic85** [comment]
Check [here](https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/) if you have configured correctly your Turn.
You're not needed to modify the code instead of _MiroTalk_ just add it on `.env` file:
```bash
TURN_ENABLED=true
TURN_URLS=turn:numb.viagenie.ca
TURN_USERNAME=YourUsername
TURN_PASSWORD=YourPassword
```

**Comment by dotnethii** [comment]
Thank you for your attention, great programmer.
I activated the Turn this way.
//if (turnEnabled == 'true') {
    iceServers.push({

   //     urls: turnUrls,
    //    username: turnUsername,
     //   credential: turnCredential,
    
        //   urls: 'turn:134.209.28.98:3478',
        //   credential: '123=',
        //    username: 'anyass'
    });
//}

Please explain how to limit the number of users in the room.
Thanks.

**Comment by dotnethii** [comment]
Thank you for your attention, great programmer.
I activated the Turn this way.
//if (turnEnabled == 'true') {
iceServers.push({

// urls: turnUrls,
// username: turnUsername,
// credential: turnCredential,

       urls: 'turn:134.209.28.98:3478',
      credential: '123=',
        username: 'anyass'
});
//}

Please explain how to limit the number of users in the room.
Thanks.

**Comment by miroslavpejic85** [comment]
```js
let limitPeers = 4;
if (Object.keys(peerConnections).length === limitPeers) {
    .....
}
```

**Comment by dotnethii** [comment]
Hello, dear master.
Please make sure the source is able to specify the number of users and the
class name when logged in.
Also have all the tools enabled for him.
But when the client user enters the link, only the rain RiseHand button is
active and his camera and microphone are opened with the admin permission.
Thanks

**Comment by dotnethii** [comment]
Please add the ability to translate into other languages to the app. Thanks

**Comment by miroslavpejic85** [comment]
@dotnethii Please no spam, you can use google translate extension for that without touching any code of MiroTalk, and translate it on all languages with a simple click. Thanks for understanding.

**Comment by dotnethii** [comment]
Please design the program so that the language of the program can be
changed.
Because if this program is used inside the intranet, you will not work as a
Google translator.
