### ISSUE TITLE
A question please

### ISSUE THREAD

**Issue by worddevfr** [miroslavpejic85/mirotalk#83]
How to join a room directly? ex: https://mirotalk.herokuapp.com/join/room-name/name/my-name/ without the "Enter your name" window

https://mirotalk.herokuapp.com?join=room-name&peerName=my-name

Thanks

**Comment by miroslavpejic85** [comment]
Hello @worddevfr, all done here: https://github.com/miroslavpejic85/mirotalk/commit/a485a83d8b4710d286cbbd860e75ff101625e15c Updated also the [Readme](https://github.com/miroslavpejic85/mirotalk#direct-join) Regards
