### ISSUE TITLE
app is not working in aws EC2 instance 

### ISSUE THREAD

**Issue by smitchaute** [miroslavpejic85/mirotalk#84]
i have configured ec2 instance with 16gb ram but the app is not working for me. can u please let me know your configuration which u applied in heroku while deploying.
thanks .

**Comment by miroslavpejic85** [comment]
Hello @smitchaute 

1. Make sure you have configured correctly the `inbound rules`

|  Port range  |  Protocol | Source    | Description.      |
|--------------|-----------|-----------|-------------|
|  3000        | TCP       | 0.0.0.0/0 | App listen on tcp |
|  3000        | UDP       | 0.0.0.0/0 | App listen on udp |

...

2. Make sure to have configured correctly the Turn in `.env`

```bash

# Turn
# 1. Goto http://numb.viagenie.ca/
# 2. Create an account
# 3. Check: https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/

TURN_ENABLED=true
TURN_URLS=turn:numb.viagenie.ca
TURN_USERNAME=YourNumbUsername
TURN_PASSWORD=YourNumbPassword
```

Regards
