### ISSUE TITLE
Joining room immediately crashes firefox

### ISSUE THREAD

**Issue by shaneknysh** [miroslavpejic85/mirotalk#89]
When I try to join a room Firefox immediately crashes. 

Trying to get error logs but it shutsdown too quickly. No error displayed firefox crash report pops up momentarily. 

Chrome on same machine displays page asking for micophone access.

**Comment by miroslavpejic85** [comment]
Hello @shaneknysh,

What do you mean shuts down too quickly, in theory, if there is some problem with your cam or microphone, the error is shown on the web page something like:

![image](https://user-images.githubusercontent.com/70838434/149729305-97b67cae-bf96-4069-80d6-b961d17388f9.png)

What version of Firefox do you have? (`update it`)
 - I tested here the latest and seems ok, both on local and live demo:
  - http://localhost:3000/join?room=firefox&name=mirotalk&audio=1&video=1
  - https://mirotalk.up.railway.app/join?room=firefox&name=mirotalk&audio=1&video=1

Make sure also to you have given all video-audio access in Firefox: https://github.com/miroslavpejic85/mirotalk/issues/13#issuecomment-830136119  

![image](https://user-images.githubusercontent.com/70838434/149729509-2920e642-ceac-4206-90aa-da26a629755f.png)

**Comment by shaneknysh** [comment]
No error is displayed on the webpage in Firefox. 

As soon as I click join room Firefox crashes - all Firefox windows close and the Firefox crash reporter is displayed. 

If I select reopen Firefox I can recover the session but no errors are in the console.

I can click join room again and trigger another crash.

I'll update with Firefox version when I'm at the keyboard tomorrow but it should be latest non beta release. Windows is at the latest patch level as well. 

On Chrome I see an error similar to your example, but I've already granted permission to use mic and camera.

I think there is some conflict with a setting or extension on my end. Containers, ublock, or something else. But without any error it's hard to figure out what is the trigger.

**Comment by miroslavpejic85** [comment]
Try to reinstall Firefox to the latest version, from the texts I made everything seems ok to me, 

I don't think your problem depends on MiroTalk.

**Comment by shaneknysh** [comment]
I was going to try reproduce the error but if the ticket is already closed there is no point of that. 

I will continue to investigate on my own - disabling all extensions and enabling one at a time to identify which - if any - is conflicting with MiroTalk. I will open a ticket with those extensions to let them know of any known conflicts with MiroTalk.

**Comment by miroslavpejic85** [comment]
You can continuing write here if you found something interesting regarding, no matter if is close or open anyone that read this ticket can see the comments ;) I closed it because after a test on Firefox (latest) it didn't give me any problems. Thank you.

**Comment by shaneknysh** [comment]
This is as far as I was able to get. 

I was able to find the issue with the Firefox crash - but I still can not get into a room. 

![image](https://user-images.githubusercontent.com/158361/150661192-e807fab4-8efa-4756-aa4a-f43ce766beef.png)

I'm giving up at this point

**Comment by shaneknysh** [comment]
> You can continuing write here if you found something interesting regarding.
> 
> No matter if is close or open anyone that read this ticket can see the comments ;)
> 
> I closed it because after a test on Firefox (latest) it didn't give me any problems.

For people to find these comments and any answers included they will have to specifically view closed issues. 

![image](https://user-images.githubusercontent.com/158361/150661382-e54454be-ddc4-41c2-b276-d0c72696acf8.png)

**Comment by miroslavpejic85** [comment]
Hello shaneknysh,

The error that I see is the NotFoundError, when you click on `here`, this page will be opened:

https://blog.addpipe.com/common-getusermedia-errors/

Have you checked the part regarding `NotFoundError`?

Another question, this happen only on Direct Join? And could you please specify the device (OS) and browser version in question?

Thank you so much.

**Comment by shaneknysh** [comment]
Yes I read the documentation. If the error you pointed out is the root
cause I'm uncertain how to confirm this as none of the cases listed fit my
configuration. I have a mic, a web cam, they are not disabled, and they are
functional in the same browser as well as in other apps in the same
computer (including the sfu version of your app, zoom, discord, teams,
meet, etc).

If I disable the camera on my PC I get a different error. Not the instant
crash error but I also do not get the error screen posted here. I get a
blank page - forever loading - never reaching the enter name and join room
state.

This is a windows 10 of with the latest windows update and latest security
patch installed.

Firefox is up to date as well.

But I'm away from the computer so I don't have the exact versions ATM.

I'd like - actually prefer - to have cameras at best optional and by
default not required.

I will need to find another solution in any case as at least one
participant has no camera at all. So even if I can solve the issue I have
it will not be available to the group. I can get it working in Edge and
Chrome but at least one participant only uses Firefox.

It's looking more and more like Discord is going to be the solution we use
and we will just have to live with the screen sharing lag.

**Comment by miroslavpejic85** [comment]
Hi @shaneknysh,

I'm sorry, but I'm not able to reproduce it, I have tested for you, on Mac-Linux-Windows on Firefox latest version. 

Are you able to try it on another PC that is not yours, with Firefox?

NB: MiroTalk P2P doesn't work if you don't have a video-audio source to work, you must have both: https://github.com/miroslavpejic85/mirotalk/issues/59

**Comment by shaneknysh** [comment]
Steps to reproduce

1. Install powertoys
2. Run power toys as admin
3. Crash mirotalk any time you want
4. Turn off powertoys conference call mute
5. Run mirotalk and hit the other error I reported
6. Uh? Profit?

**Comment by miroslavpejic85** [comment]
Hey @shaneknysh,

Another question, are the `Windows` installed on `virtual machine`?

I tell you this because I reproduced your issue on my virtual machine, installing Windows 11 and Firefox. 

I solved it, going to add new device in the virtual machine settings, and then I select my default webcam.

<img width="640" alt="add-webcam" src="https://user-images.githubusercontent.com/70838434/150869977-aec8714b-8ca0-4a57-bc87-35efdd3a63d9.png">

On MiroTalk SFU version you probably can join in the room because it works also without the connected webcam. MiroTalk P2P as mentioned not for now.

**Comment by shaneknysh** [comment]
No virtual machine. MSI GF75 Thin.  

I am on my phone. I will fix the layout of the previous response when I am back at the computer.

**Comment by miroslavpejic85** [comment]
Check out : https://www.drivereasy.com/knowledge/how-to-fix-msi-camera-not-working/

**Comment by shaneknysh** [comment]
Since the camera works with other apps and including the sfu mirotalk I
assume the camera is not disabled.

However, I have gone through those steps and the camera is not disabled by
MSI.

**Comment by miroslavpejic85** [comment]
Hi @shaneknysh any news?
Can you test it on another PC with a clean install of latest firefox? Not Found Error could be caused if the camera is used by another app (may be in the background etc) Thanks

**Comment by shaneknysh** [comment]
I haven't tested it since the last post. I don't have another PC to use to do a fresh install of Firefox.

I've given up on getting Mirotalk to work. As I stated in another issue report at least one person I need to communicate with has no camera at all. So _if_ I do a fresh install and _if_ that corrects the problem I still can't use mirotalk.

Currently I can launch one version of mirotalk but not the other. How do I determine what app took control of the camera between switching from one to the other? Or what is triggering MSI to disable my camera only in Firefox and only when I try to use one version on mirotalk? And then re-enable it if I want to use it in Teams or Discord or...

The instant crash is reproduced by the steps provided above. It isn't a mirotalk nor Firefox issue.
