### ISSUE TITLE
MiroTalk is not showing video of participant

### ISSUE THREAD

**Issue by mwimmer-bcx** [miroslavpejic85/mirotalk#90]
On the MiroTalk Heroku Demo page and on our local installation, i have the problem that i can not see the participants video. i can see that someone joined but the half of the page is black and i can only see my camera.
I can not here the other persons as well. The colleagues in the same room can see and hear each others.

We have the same notebooks, in the same domain but there seems some problem with it. does anyone had this problem before?

i can see in the console, that there is connectionStatus: failed. Does anyone have a hint for it?

Kind regards,
Manuel

**Comment by Jaideep25** [comment]
Hey @mwimmer-bcx! 
1. Can you please clarify that are you all connected to the same network?
2. Can your colleagues see you, and see each other too?
Thanks :)

**Comment by mwimmer-bcx** [comment]
hey @Jaideep25 

1) We are not connected to the same network. 3 Persons, 3 Networks and 3 Client. The other two are seeing each other, only im not able to talk to anyone or see anyone.
2) the other two persons are seeing each others.

Thanks!

**Comment by miroslavpejic85** [comment]
Hi @mwimmer-bcx,
Do you see any errors or interesting things in your browser console? 

Maybe it could be a NAT/Turn Server problem?
What is Turn: https://webrtc.org/getting-started/turn-server

The current MiroTalk P2P architecture is the following and as a Turn-Server it uses: http://numb.viagenie.ca/ which maybe doesn't work well? 

![image](https://user-images.githubusercontent.com/70838434/150571886-824156a3-319a-4d9f-9eb3-b741d9527a12.png)

Todo:

- Step to reproduce the problem (explain in detail)
- Devices involved (Mobile, Desktop)
- Browser version (update it always to latest)
- Browawer console logs (F12)

And if related to Turn, try changing it with [coturn](https://github.com/coturn/coturn) which looks very good to me and see if it happens again.

Once you have setup your `coturn`, I found this [article](https://ourcodeworld.com/articles/read/1175/how-to-create-and-configure-your-own-stun-turn-server-with-coturn-in-ubuntu-18-04) on the fly, that could help, check if all configured correctly here: https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/, then change the credentials in the `.env` file.

```bash
TURN_ENABLED=true
TURN_URLS=turn:turn.YourDomainName:5349
TURN_USERNAME=YourCoturnUsername
TURN_PASSWORD=YourCoturnPassword
```
 
Let me know, and thank you so much for trying MiroTalk.
