### ISSUE TITLE
Appear white screen when join from MacOS -> Safari15

### ISSUE THREAD

**Issue by i4udevstar1001** [miroslavpejic85/mirotalk#94]
I'm using miratalk library but there are several problems.
Main problem:
  Sometimes can't get video stream (appear white screen).
OS: MacOS, Web Browser: Safari15 and iPhone 11 Pro
It works good on Windwos and Ubuntu.
I was going to find problem, so I think it's navigator.mediaDevices.getUserMedia() function can't get stream sometimes on MacOS -> Safari.
I didn't find any solution yet.
I hope to help me.
Thanks.

**Comment by miroslavpejic85** [comment]
Hello @i4udevstar1001, I think can be a Safari issue:

- Open https://webrtc.github.io/samples/src/content/getusermedia/gum/ in 2 different tab on Safari browser 
- click Open camera

On first tab the camera is displayed, when you Open camera on the second tab the first turn black.
I'm also not see errors on navigator.mediaDevices.getUserMedia.
If you try the same test with other browsers this not happen.
Sometimes it doesn't depend on MiroTalk, browsers can also introduce bugs.
You may have entered the same room with two different tabs, with the same safari browser? 
If yes, the problem can be above mentioned.
Make sure you've maybe closed all browser tabs on mobile devices.
Thanks

**Comment by i4udevstar1001** [comment]
I got it... so it was WebRTC problem.
Thanks.

**Comment by miroslavpejic85** [comment]
Good, Safari problem, use a different browser for now, until they fix it.
