### ISSUE TITLE
New deploy

### ISSUE THREAD

**Issue by Nikolai980** [miroslavpejic85/mirotalk#95]
### Feature request
Add deploy option for replit users.

**Comment by miroslavpejic85** [comment]
Hello @Nikolai980, 

Just import this project and run it on [replit](https://replit.com/)
I did it for you, to test it and seems OK: https://mirotalk.miroslavpejic85.repl.co/

![image](https://user-images.githubusercontent.com/70838434/160409597-49b92c01-e087-403b-a001-832e59126d24.png)

Thanks for trying MiroTalk.
