### ISSUE TITLE
Excalidraw integration

### ISSUE THREAD

**Issue by xplosionmind** [miroslavpejic85/mirotalk#98]
### Feature request

Instead of developing and maintaining a custom whiteboard, why not using [Excalidraw](https://excalidraw.org)?

### Pros

- implementing a widely used whiteboard software
- not having to code from scratch and maintain a whole custom board

**Comment by GerryGit** [comment]
$7 per user/month

**Comment by xplosionmind** [comment]
> $7 per user/month

Please, take a better look. The free version has a lot of features and it works wonderfully. The price you indicated is for extra features only.

**Comment by miroslavpejic85** [comment]
Hello @xplosionmind, 
Thank you for your suggestion, much appreciated and I will take this into consideration anyway. 
However having an external collaborative whiteboard projects becomes difficult for me to make customized changes if requested and I would depend on an external project. 
Excalidraw is nice, I had even recommended it in some forums when some required a collaborative whiteboard projects.
Join with us on [discord](https://discord.gg/rgGYfeYW3N) where we can talk about interesting topics like this too.
Many thanks.
